// Code generated by go-sdk-generator. DO NOT EDIT.

package wallets

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedWalletsClient provides delegated user action signing for wallets operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedWalletsClient struct {
	client *client.Client
}

// NewDelegatedWalletsClient creates a new DelegatedWalletsClient.
func NewDelegatedWalletsClient(c *client.Client) *DelegatedWalletsClient {
	return &DelegatedWalletsClient{client: c}
}

// AbortTransactionInit starts delegated user action signing for the abortTransaction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to AbortTransactionComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) AbortTransactionInit(ctx context.Context, walletID string, transactionID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/abort"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// AbortTransactionComplete finishes delegated signing for the abortTransaction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the AbortTransactionInit challenge.
func (c *DelegatedWalletsClient) AbortTransactionComplete(ctx context.Context, walletID string, transactionID string, challengeID string, assertion *signer.CredentialAssertion) (*AbortTransactionResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/abort"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result AbortTransactionResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// AbortTransferInit starts delegated user action signing for the abortTransfer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to AbortTransferComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) AbortTransferInit(ctx context.Context, walletID string, transferID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/abort"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// AbortTransferComplete finishes delegated signing for the abortTransfer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the AbortTransferInit challenge.
func (c *DelegatedWalletsClient) AbortTransferComplete(ctx context.Context, walletID string, transferID string, challengeID string, assertion *signer.CredentialAssertion) (*AbortTransferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/abort"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result AbortTransferResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ActivateWalletInit starts delegated user action signing for the activateWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivateWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) ActivateWalletInit(ctx context.Context, walletID string, body ActivateWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/activate"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// ActivateWalletComplete finishes delegated signing for the activateWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivateWalletInit challenge.
func (c *DelegatedWalletsClient) ActivateWalletComplete(ctx context.Context, walletID string, body ActivateWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*ActivateWalletResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivateWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of transactions requests for the specified wallet.
func (c *DelegatedWalletsClient) ListTransactions(ctx context.Context, walletID string, query *ListTransactionsQuery) (*ListTransactionsResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListTransactionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SignAndBroadcastTransactionInit starts delegated user action signing for the signAndBroadcastTransaction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to SignAndBroadcastTransactionComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) SignAndBroadcastTransactionInit(ctx context.Context, walletID string, body SignAndBroadcastTransactionRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// SignAndBroadcastTransactionComplete finishes delegated signing for the signAndBroadcastTransaction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the SignAndBroadcastTransactionInit challenge.
func (c *DelegatedWalletsClient) SignAndBroadcastTransactionComplete(ctx context.Context, walletID string, body SignAndBroadcastTransactionRequest, challengeID string, assertion *signer.CredentialAssertion) (*SignAndBroadcastTransactionResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result SignAndBroadcastTransactionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelTransactionInit starts delegated user action signing for the cancelTransaction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CancelTransactionComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) CancelTransactionInit(ctx context.Context, walletID string, transactionID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/cancel"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// CancelTransactionComplete finishes delegated signing for the cancelTransaction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CancelTransactionInit challenge.
func (c *DelegatedWalletsClient) CancelTransactionComplete(ctx context.Context, walletID string, transactionID string, challengeID string, assertion *signer.CredentialAssertion) (*CancelTransactionResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/cancel"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CancelTransactionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CancelTransferInit starts delegated user action signing for the cancelTransfer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CancelTransferComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) CancelTransferInit(ctx context.Context, walletID string, transferID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/cancel"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// CancelTransferComplete finishes delegated signing for the cancelTransfer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CancelTransferInit challenge.
func (c *DelegatedWalletsClient) CancelTransferComplete(ctx context.Context, walletID string, transferID string, challengeID string, assertion *signer.CredentialAssertion) (*CancelTransferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/cancel"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CancelTransferResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Proxies a request to the Canton Ledger API associated with this wallet, using the validator's OAuth2 credentials. Restricted to a curated allow-list of read-style resources. Used to satisfy the Canton WalletConnect `canton_ledgerApi` method.
func (c *DelegatedWalletsClient) ProxyARequestToTheCantonLedgerAPI(ctx context.Context, walletID string, body ProxyARequestToTheCantonLedgerAPIRequest) (interface{}, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/canton/ledger-api"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// SpeedUpTransactionInit starts delegated user action signing for the speedUpTransaction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to SpeedUpTransactionComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) SpeedUpTransactionInit(ctx context.Context, walletID string, transactionID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/speed-up"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// SpeedUpTransactionComplete finishes delegated signing for the speedUpTransaction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the SpeedUpTransactionInit challenge.
func (c *DelegatedWalletsClient) SpeedUpTransactionComplete(ctx context.Context, walletID string, transactionID string, challengeID string, assertion *signer.CredentialAssertion) (*SpeedUpTransactionResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID) + "/speed-up"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result SpeedUpTransactionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// SpeedUpTransferInit starts delegated user action signing for the speedUpTransfer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to SpeedUpTransferComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) SpeedUpTransferInit(ctx context.Context, walletID string, transferID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/speed-up"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// SpeedUpTransferComplete finishes delegated signing for the speedUpTransfer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the SpeedUpTransferInit challenge.
func (c *DelegatedWalletsClient) SpeedUpTransferComplete(ctx context.Context, walletID string, transferID string, challengeID string, assertion *signer.CredentialAssertion) (*SpeedUpTransferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID) + "/speed-up"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result SpeedUpTransferResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the list of Wallets in your organization. You can filter the results by owner (either by owner id or owner username). Pagination is supported via limit and paginationToken parameters.
func (c *DelegatedWalletsClient) ListWallets(ctx context.Context, query *ListWalletsQuery) (*ListWalletsResponse, error) {
	path := "/wallets"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Owner != nil {
			q.Set("owner", fmt.Sprintf("%v", *query.Owner))
		}
		if query.OwnerID != nil {
			q.Set("ownerId", fmt.Sprintf("%v", *query.OwnerID))
		}
		if query.OwnerUsername != nil {
			q.Set("ownerUsername", fmt.Sprintf("%v", *query.OwnerUsername))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListWalletsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateWalletInit starts delegated user action signing for the createWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) CreateWalletInit(ctx context.Context, body CreateWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateWalletComplete finishes delegated signing for the createWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateWalletInit challenge.
func (c *DelegatedWalletsClient) CreateWalletComplete(ctx context.Context, body CreateWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateWalletResponse, error) {
	path := "/wallets"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific transaction.
func (c *DelegatedWalletsClient) GetTransaction(ctx context.Context, walletID string, transactionID string) (*GetTransactionResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transactions/" + url.PathEscape(transactionID)
	var result GetTransactionResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a Wallet Transfer Request by its ID.
func (c *DelegatedWalletsClient) GetTransfer(ctx context.Context, walletID string, transferID string) (*GetTransferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers/" + url.PathEscape(transferID)
	var result GetTransferResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a Wallet information by its ID.
func (c *DelegatedWalletsClient) GetWallet(ctx context.Context, walletID string) (*GetWalletResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID)
	var result GetWalletResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWalletInit starts delegated user action signing for the updateWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) UpdateWalletInit(ctx context.Context, walletID string, body UpdateWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateWalletComplete finishes delegated signing for the updateWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateWalletInit challenge.
func (c *DelegatedWalletsClient) UpdateWalletComplete(ctx context.Context, walletID string, body UpdateWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateWalletResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of assets owned by the specified wallet.  Return values vary by chain as shown below.
func (c *DelegatedWalletsClient) GetWalletAssets(ctx context.Context, walletID string, query *GetWalletAssetsQuery) (*GetWalletAssetsResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.NetWorth != nil {
			q.Set("netWorth", fmt.Sprintf("%v", *query.NetWorth))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetWalletAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of historical on chain activities for the specified wallet.
// 
// The list reflects the indexed on-chain activity: it includes confirmed transactions only.
func (c *DelegatedWalletsClient) GetWalletHistory(ctx context.Context, walletID string, query *GetWalletHistoryQuery) (*GetWalletHistoryResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/history"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Direction != nil {
			q.Set("direction", fmt.Sprintf("%v", *query.Direction))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.Contract != nil {
			q.Set("contract", fmt.Sprintf("%v", *query.Contract))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetWalletHistoryResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of NFTs owned by the specified Wallet.
func (c *DelegatedWalletsClient) GetWalletNfts(ctx context.Context, walletID string) (*GetWalletNftsResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/nfts"
	var result GetWalletNftsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ImportWalletInit starts delegated user action signing for the importWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ImportWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) ImportWalletInit(ctx context.Context, body ImportWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/import"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// ImportWalletComplete finishes delegated signing for the importWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ImportWalletInit challenge.
func (c *DelegatedWalletsClient) ImportWalletComplete(ctx context.Context, body ImportWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*ImportWalletResponse, error) {
	path := "/wallets/import"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ImportWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of transfer requests for the specified wallet.
func (c *DelegatedWalletsClient) ListTransfers(ctx context.Context, walletID string, query *ListTransfersQuery) (*ListTransfersResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListTransfersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TransferAssetInit starts delegated user action signing for the transferAsset operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to TransferAssetComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) TransferAssetInit(ctx context.Context, walletID string, body TransferAssetRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// TransferAssetComplete finishes delegated signing for the transferAsset operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the TransferAssetInit challenge.
func (c *DelegatedWalletsClient) TransferAssetComplete(ctx context.Context, walletID string, body TransferAssetRequest, challengeID string, assertion *signer.CredentialAssertion) (*TransferAssetResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/transfers"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result TransferAssetResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// TagWalletInit starts delegated user action signing for the tagWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to TagWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) TagWalletInit(ctx context.Context, walletID string, body TagWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/tags"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// TagWalletComplete finishes delegated signing for the tagWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the TagWalletInit challenge.
func (c *DelegatedWalletsClient) TagWalletComplete(ctx context.Context, walletID string, body TagWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*TagWalletResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/tags"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result TagWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// UntagWalletInit starts delegated user action signing for the untagWallet operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UntagWalletComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) UntagWalletInit(ctx context.Context, walletID string, body UntagWalletRequest) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/tags"
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, body)
}

// UntagWalletComplete finishes delegated signing for the untagWallet operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UntagWalletInit challenge.
func (c *DelegatedWalletsClient) UntagWalletComplete(ctx context.Context, walletID string, body UntagWalletRequest, challengeID string, assertion *signer.CredentialAssertion) (*UntagWalletResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/tags"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UntagWalletResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific offer received on your wallet.
func (c *DelegatedWalletsClient) GetOffer(ctx context.Context, walletID string, offerID string) (*GetOfferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers/" + url.PathEscape(offerID)
	var result GetOfferResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all offers received on a specific wallet.
func (c *DelegatedWalletsClient) ListOffers(ctx context.Context, walletID string, query *ListOffersQuery) (*ListOffersResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListOffersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AcceptOfferInit starts delegated user action signing for the acceptOffer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to AcceptOfferComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) AcceptOfferInit(ctx context.Context, walletID string, offerID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers/" + url.PathEscape(offerID) + "/accept"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// AcceptOfferComplete finishes delegated signing for the acceptOffer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the AcceptOfferInit challenge.
func (c *DelegatedWalletsClient) AcceptOfferComplete(ctx context.Context, walletID string, offerID string, challengeID string, assertion *signer.CredentialAssertion) (*AcceptOfferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers/" + url.PathEscape(offerID) + "/accept"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result AcceptOfferResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// RejectOfferInit starts delegated user action signing for the rejectOffer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to RejectOfferComplete
// along with the same arguments given here.
func (c *DelegatedWalletsClient) RejectOfferInit(ctx context.Context, walletID string, offerID string) (*signer.UserActionChallenge, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers/" + url.PathEscape(offerID) + "/reject"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// RejectOfferComplete finishes delegated signing for the rejectOffer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the RejectOfferInit challenge.
func (c *DelegatedWalletsClient) RejectOfferComplete(ctx context.Context, walletID string, offerID string, challengeID string, assertion *signer.CredentialAssertion) (*RejectOfferResponse, error) {
	path := "/wallets/" + url.PathEscape(walletID) + "/offers/" + url.PathEscape(offerID) + "/reject"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result RejectOfferResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the transaction history across all wallets within a specified timeframe. The time range is unbounded, but the CSV export is capped at 100,000 rows.
func (c *DelegatedWalletsClient) ListOrgWalletHistory(ctx context.Context, query *ListOrgWalletHistoryQuery) (interface{}, error) {
	path := "/wallets/all/history"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		q.Set("startTime", fmt.Sprintf("%v", query.StartTime))
		q.Set("endTime", fmt.Sprintf("%v", query.EndTime))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}
