// Code generated by go-sdk-generator. DO NOT EDIT.

package wallets

import (
	"github.com/dfns/dfns-sdk-go/types"
)

// ActivateWalletRequest represents the request body for the activateWallet operation.
type ActivateWalletRequest = any

// Activate Wallet
type ActivateWalletResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// List Transactions
type ListTransactionsResponse struct {
	WalletID string `json:"walletId"`
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListTransactionsQuery represents query parameters.
type ListTransactionsQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// SignAndBroadcastTransactionRequest represents the request body for the signAndBroadcastTransaction operation.
type SignAndBroadcastTransactionRequest = any

// Sign and Broadcast Transaction
type SignAndBroadcastTransactionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Cancel Transaction
type CancelTransactionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Cancel Transfer
type CancelTransferResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Speed Up Transaction
type SpeedUpTransactionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Speed Up Transfer
type SpeedUpTransferResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// List Wallets
type ListWalletsResponse struct {
	Items []types.Wallet `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListWalletsQuery represents query parameters.
type ListWalletsQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	Owner *string `json:"owner,omitempty"`
	OwnerID *string `json:"ownerId,omitempty"`
	OwnerUsername *string `json:"ownerUsername,omitempty"`
}

// Create Wallet
type CreateWalletRequest struct {
	Network string `json:"network"`
	Name *string `json:"name,omitempty"`
	SigningKey *map[string]interface{} `json:"signingKey,omitempty"`
	DelegateTo *string `json:"delegateTo,omitempty"`
	DelayDelegation *bool `json:"delayDelegation,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags []string `json:"tags,omitempty"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// Create Wallet
type CreateWalletResponse struct {
	ID string `json:"id"`
	Network string `json:"network"`
	Address *string `json:"address,omitempty"`
	SigningKey map[string]interface{} `json:"signingKey"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	DateDeleted *string `json:"dateDeleted,omitempty"`
	Name *string `json:"name,omitempty"`
	Custodial bool `json:"custodial"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags []string `json:"tags"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// Delegate Wallet
type DelegateWalletRequest struct {
	UserID string `json:"userId"`
}

// Delegate Wallet
type DelegateWalletResponse struct {
	WalletID string `json:"walletId"`
	Status string `json:"status"`
}

// Export Wallet
type ExportWalletRequest struct {
	EncryptionKey string `json:"encryptionKey"`
	SupportedSchemes []map[string]interface{} `json:"supportedSchemes"`
}

// Export Wallet
type ExportWalletResponse struct {
	PublicKey string `json:"publicKey"`
	Protocol interface{} `json:"protocol"`
	Curve string `json:"curve"`
	MinSigners float64 `json:"minSigners"`
	EncryptedKeyShares []map[string]interface{} `json:"encryptedKeyShares"`
}

// List Signatures
type ListSignaturesResponse struct {
	KeyID string `json:"keyId"`
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListSignaturesQuery represents query parameters.
type ListSignaturesQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// GenerateSignatureRequest represents the request body for the generateSignature operation.
type GenerateSignatureRequest = any

// Generate Signature
type GenerateSignatureResponse struct {
	ID string `json:"id"`
	KeyID string `json:"keyId"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	Signature *map[string]interface{} `json:"signature,omitempty"`
	Signatures []map[string]interface{} `json:"signatures,omitempty"`
	SignedData *string `json:"signedData,omitempty"`
	Network string `json:"network"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateSigned *string `json:"dateSigned,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	WalletID string `json:"walletId"`
}

// Get Signature
type GetSignatureResponse struct {
	ID string `json:"id"`
	KeyID string `json:"keyId"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	Signature *map[string]interface{} `json:"signature,omitempty"`
	Signatures []map[string]interface{} `json:"signatures,omitempty"`
	SignedData *string `json:"signedData,omitempty"`
	Network *types.Network `json:"network,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateSigned *string `json:"dateSigned,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Get Transaction
type GetTransactionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Get Transfer
type GetTransferResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Metadata map[string]interface{} `json:"metadata"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	FeeSponsorID *string `json:"feeSponsorId,omitempty"`
}

// Get Wallet
type GetWalletResponse struct {
	ID string `json:"id"`
	Network string `json:"network"`
	Address *string `json:"address,omitempty"`
	SigningKey map[string]interface{} `json:"signingKey"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	DateDeleted *string `json:"dateDeleted,omitempty"`
	Name *string `json:"name,omitempty"`
	Custodial bool `json:"custodial"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags []string `json:"tags"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// Update Wallet
type UpdateWalletRequest struct {
	Name interface{} `json:"name,omitempty"`
	ExternalID interface{} `json:"externalId,omitempty"`
}

// Update Wallet
type UpdateWalletResponse struct {
	ID string `json:"id"`
	Network string `json:"network"`
	Address *string `json:"address,omitempty"`
	SigningKey map[string]interface{} `json:"signingKey"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	DateDeleted *string `json:"dateDeleted,omitempty"`
	Name *string `json:"name,omitempty"`
	Custodial bool `json:"custodial"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags []string `json:"tags"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// Get Wallet Assets
type GetWalletAssetsResponse struct {
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Assets []map[string]interface{} `json:"assets"`
	NetWorth *map[string]interface{} `json:"netWorth,omitempty"`
}

// GetWalletAssetsQuery represents query parameters.
type GetWalletAssetsQuery struct {
	NetWorth *string `json:"netWorth,omitempty"`
}

// Get Wallet History
type GetWalletHistoryResponse struct {
	Items []interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
}

// GetWalletHistoryQuery represents query parameters.
type GetWalletHistoryQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	Direction *string `json:"direction,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Contract *string `json:"contract,omitempty"`
}

// Get Wallet Nfts
type GetWalletNftsResponse struct {
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Nfts []interface{} `json:"nfts"`
}

// Import Wallet
type ImportWalletRequest struct {
	Name *string `json:"name,omitempty"`
	Curve string `json:"curve"`
	Protocol interface{} `json:"protocol"`
	MinSigners int64 `json:"minSigners"`
	EncryptedKeyShares []map[string]interface{} `json:"encryptedKeyShares"`
	Network string `json:"network"`
	ExternalID *string `json:"externalId,omitempty"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// Import Wallet
type ImportWalletResponse struct {
	ID string `json:"id"`
	Network string `json:"network"`
	Address *string `json:"address,omitempty"`
	SigningKey map[string]interface{} `json:"signingKey"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	DateDeleted *string `json:"dateDeleted,omitempty"`
	Name *string `json:"name,omitempty"`
	Custodial bool `json:"custodial"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags []string `json:"tags"`
	ValidatorID *string `json:"validatorId,omitempty"`
}

// List Transfers
type ListTransfersResponse struct {
	WalletID string `json:"walletId"`
	Items []types.TransferRequest `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListTransfersQuery represents query parameters.
type ListTransfersQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// TransferAssetRequest represents the request body for the transferAsset operation.
type TransferAssetRequest = any

// Transfer Asset
type TransferAssetResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Metadata map[string]interface{} `json:"metadata"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	FeeSponsorID *string `json:"feeSponsorId,omitempty"`
}

// Tag Wallet
type TagWalletRequest struct {
	Tags []string `json:"tags"`
}

// Tag Wallet
type TagWalletResponse struct {
}

// Untag Wallet
type UntagWalletRequest struct {
	Tags []string `json:"tags"`
}

// Untag Wallet
type UntagWalletResponse struct {
}

// Get Offer
type GetOfferResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Kind string `json:"kind"`
	Metadata map[string]interface{} `json:"metadata"`
	TxHash string `json:"txHash"`
	Status string `json:"status"`
	From string `json:"from"`
	To string `json:"to"`
	Value string `json:"value"`
	Timestamp string `json:"timestamp"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
	Memo *string `json:"memo,omitempty"`
	SettlementTransactionID *string `json:"settlementTransactionId,omitempty"`
	DateSettled *string `json:"dateSettled,omitempty"`
}

// List Offers
type ListOffersResponse struct {
	Items []types.Offer `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListOffersQuery represents query parameters.
type ListOffersQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Accept Offer
type AcceptOfferResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Kind string `json:"kind"`
	Metadata map[string]interface{} `json:"metadata"`
	TxHash string `json:"txHash"`
	Status string `json:"status"`
	From string `json:"from"`
	To string `json:"to"`
	Value string `json:"value"`
	Timestamp string `json:"timestamp"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
	Memo *string `json:"memo,omitempty"`
	SettlementTransactionID *string `json:"settlementTransactionId,omitempty"`
	DateSettled *string `json:"dateSettled,omitempty"`
}

// Reject Offer
type RejectOfferResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Kind string `json:"kind"`
	Metadata map[string]interface{} `json:"metadata"`
	TxHash string `json:"txHash"`
	Status string `json:"status"`
	From string `json:"from"`
	To string `json:"to"`
	Value string `json:"value"`
	Timestamp string `json:"timestamp"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
	Memo *string `json:"memo,omitempty"`
	SettlementTransactionID *string `json:"settlementTransactionId,omitempty"`
	DateSettled *string `json:"dateSettled,omitempty"`
}

// ListOrgWalletHistoryQuery represents query parameters.
type ListOrgWalletHistoryQuery struct {
	StartTime string `json:"startTime"`
	EndTime string `json:"endTime"`
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}
