// Code generated by go-sdk-generator. DO NOT EDIT.

package payouts

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// PayoutsClient provides methods for payouts operations.
type PayoutsClient struct {
	client *client.Client
}

// NewPayoutsClient creates a new PayoutsClient.
func NewPayoutsClient(c *client.Client) *PayoutsClient {
	return &PayoutsClient{client: c}
}

// List payouts with optional filtering and pagination.
func (c *PayoutsClient) ListPayouts(ctx context.Context, query *ListPayoutsQuery) (*ListPayoutsResponse, error) {
	path := "/payouts"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.WalletID != nil {
			q.Set("walletId", fmt.Sprintf("%v", *query.WalletID))
		}
		if query.Status != nil {
			q.Set("status", fmt.Sprintf("%v", *query.Status))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayoutsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new payout to convert crypto assets to fiat currency.
func (c *PayoutsClient) CreatePayout(ctx context.Context, body CreatePayoutRequest) (interface{}, error) {
	path := "/payouts"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Request a quote from a given provider for a payout. Returns estimated fiat amount and fees.
func (c *PayoutsClient) RequestPayoutQuote(ctx context.Context, body RequestPayoutQuoteRequest) (*RequestPayoutQuoteResponse, error) {
	path := "/payouts/quote"
	var result RequestPayoutQuoteResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the current status of a payout by its ID.
func (c *PayoutsClient) GetPayoutStatus(ctx context.Context, payoutID string) (interface{}, error) {
	path := "/payouts/" + url.PathEscape(payoutID)
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Perform an action on a payout, such as confirming or canceling.
func (c *PayoutsClient) CreatePayoutAction(ctx context.Context, payoutID string, body CreatePayoutActionRequest) (*CreatePayoutActionResponse, error) {
	path := "/payouts/" + url.PathEscape(payoutID) + "/action"
	var result CreatePayoutActionResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
