// Code generated by go-sdk-generator. DO NOT EDIT.

package payouts

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedPayoutsClient provides delegated user action signing for payouts operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedPayoutsClient struct {
	client *client.Client
}

// NewDelegatedPayoutsClient creates a new DelegatedPayoutsClient.
func NewDelegatedPayoutsClient(c *client.Client) *DelegatedPayoutsClient {
	return &DelegatedPayoutsClient{client: c}
}

// List payouts with optional filtering and pagination.
func (c *DelegatedPayoutsClient) ListPayouts(ctx context.Context, query *ListPayoutsQuery) (*ListPayoutsResponse, error) {
	path := "/payouts"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.WalletID != nil {
			q.Set("walletId", fmt.Sprintf("%v", *query.WalletID))
		}
		if len(query.Status) > 0 {
			q.Set("status", fmt.Sprintf("%v", query.Status))
		}
		if len(query.Provider) > 0 {
			q.Set("provider", fmt.Sprintf("%v", query.Provider))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayoutsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePayoutInit starts delegated user action signing for the createPayout operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePayoutComplete
// along with the same arguments given here.
func (c *DelegatedPayoutsClient) CreatePayoutInit(ctx context.Context, body CreatePayoutRequest) (*signer.UserActionChallenge, error) {
	path := "/payouts"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePayoutComplete finishes delegated signing for the createPayout operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePayoutInit challenge.
func (c *DelegatedPayoutsClient) CreatePayoutComplete(ctx context.Context, body CreatePayoutRequest, challengeID string, assertion *signer.CredentialAssertion) (interface{}, error) {
	path := "/payouts"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return result, nil
}

// Request a quote from a given provider for a payout. Returns estimated fiat amount and fees.
func (c *DelegatedPayoutsClient) RequestPayoutQuote(ctx context.Context, body RequestPayoutQuoteRequest) (*RequestPayoutQuoteResponse, error) {
	path := "/payouts/quote"
	var result RequestPayoutQuoteResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the current status of a payout by its ID.
func (c *DelegatedPayoutsClient) GetPayoutStatus(ctx context.Context, payoutID string) (interface{}, error) {
	path := "/payouts/" + url.PathEscape(payoutID)
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// CreatePayoutActionInit starts delegated user action signing for the createPayoutAction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePayoutActionComplete
// along with the same arguments given here.
func (c *DelegatedPayoutsClient) CreatePayoutActionInit(ctx context.Context, payoutID string, body CreatePayoutActionRequest) (*signer.UserActionChallenge, error) {
	path := "/payouts/" + url.PathEscape(payoutID) + "/action"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePayoutActionComplete finishes delegated signing for the createPayoutAction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePayoutActionInit challenge.
func (c *DelegatedPayoutsClient) CreatePayoutActionComplete(ctx context.Context, payoutID string, body CreatePayoutActionRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreatePayoutActionResponse, error) {
	path := "/payouts/" + url.PathEscape(payoutID) + "/action"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreatePayoutActionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
