// Code generated by go-sdk-generator. DO NOT EDIT.

package payouts

// List Payouts
type ListPayoutsResponse struct {
	Items []interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListPayoutsQuery represents query parameters.
type ListPayoutsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	WalletID *string `json:"walletId,omitempty"`
	Status []string `json:"status,omitempty"`
}

// CreatePayoutRequest represents the request body for the createPayout operation.
type CreatePayoutRequest = any

// RequestPayoutQuoteRequest represents the request body for the requestPayoutQuote operation.
type RequestPayoutQuoteRequest = any

// Request Payout Quote
type RequestPayoutQuoteResponse struct {
	Provider string `json:"provider"`
	Asset interface{} `json:"asset"`
	Timestamp string `json:"timestamp"`
	Quotes []map[string]interface{} `json:"quotes"`
}

// CreatePayoutActionRequest represents the request body for the createPayoutAction operation.
type CreatePayoutActionRequest = any

// Create Payout Action
type CreatePayoutActionResponse struct {
}
