version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/dfns/dfns-sdk-go
            - github.com/google/uuid
            - github.com/aws/aws-sdk-go-v2/service/kms
            - github.com/aws/aws-sdk-go-v2/config
            - github.com/aws/aws-sdk-go-v2/aws
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    gocritic:
      disabled-checks:
        - whyNoLint
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    prealloc:
      simple: false
      range-loops: true
      for-loops: true
    revive:
      confidence: 0
    tagalign:
      align: false
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2 
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - contextcheck
          - cyclop
          - dupl
          - err113
          - errcheck
          - errorlint
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gocritic
          - interfacer
          - lll
          - nlreturn
          - varnamelen
          - wrapcheck
        path: (.+)_test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - cmd
      - pkg/mod
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/dfns/dfns-sdk-go)
    gofumpt:
      module-path: github.com/dfns/dfns-sdk-go
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - cmd
      - pkg/mod
      - third_party$
      - builtin$
      - examples$
