linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/dfns/dfns-sdk-go)
  gofumpt:
    extra-rules: true
    module-path: github.com/dfns/dfns-sdk-go
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    confidence: 0
  prealloc:
    simple: false
    range-loops: true
    for-loops: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult
  errorlint:
    errorf: true
  nolintlint:
    require-explanation: true
    require-specific: true
  tagalign:
    align: false
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/dfns/dfns-sdk-go
          - github.com/google/uuid
          - github.com/aws/aws-sdk-go-v2/service/kms
          - github.com/aws/aws-sdk-go-v2/config
          - github.com/aws/aws-sdk-go-v2/aws
run:
  timeout: 15m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - funlen
        - bodyclose
        - goconst
        - interfacer
        - dupl
        - lll
        - goerr113
        - varnamelen
        - errcheck
        - gocritic
        - cyclop
        - wrapcheck
        - gocognit
        - contextcheck
        - nlreturn
        - gochecknoglobals
        - errorlint
    - linters:
        - lll
      source: "^//go:generate "
  exclude-dirs:
    - cmd
    - pkg/mod
