// Code generated by go-sdk-generator. DO NOT EDIT.

package dfns

import (
	"github.com/dfns/dfns-sdk-go/internal/client"
	"github.com/dfns/dfns-sdk-go/auth"
	"github.com/dfns/dfns-sdk-go/exchanges"
	"github.com/dfns/dfns-sdk-go/feesponsors"
	"github.com/dfns/dfns-sdk-go/keys"
	"github.com/dfns/dfns-sdk-go/networks"
	"github.com/dfns/dfns-sdk-go/permissions"
	"github.com/dfns/dfns-sdk-go/policies"
	"github.com/dfns/dfns-sdk-go/signers"
	"github.com/dfns/dfns-sdk-go/staking"
	"github.com/dfns/dfns-sdk-go/wallets"
	"github.com/dfns/dfns-sdk-go/webhooks"
	"github.com/dfns/dfns-sdk-go/swaps"
	"github.com/dfns/dfns-sdk-go/agreements"
	"github.com/dfns/dfns-sdk-go/allocations"
)

// Options contains configuration for the Dfns client.
// Re-exported from internal package for public access.
type Options = client.Options

// APIError represents an error response from the Dfns API.
// Re-exported from internal package for public access.
type APIError = client.APIError

// Client is the main Dfns API client.
type Client struct {
	baseClient *client.Client
	Auth *auth.AuthClient
	Exchanges *exchanges.ExchangesClient
	FeeSponsors *feesponsors.FeeSponsorsClient
	Keys *keys.KeysClient
	Networks *networks.NetworksClient
	Permissions *permissions.PermissionsClient
	Policies *policies.PoliciesClient
	Signers *signers.SignersClient
	Staking *staking.StakingClient
	Wallets *wallets.WalletsClient
	Webhooks *webhooks.WebhooksClient
	Swaps *swaps.SwapsClient
	Agreements *agreements.AgreementsClient
	Allocations *allocations.AllocationsClient
}

// NewClient creates a new Dfns API client.
func NewClient(opts Options) (*Client, error) {
	c, err := client.New(opts)
	if err != nil {
		return nil, err
	}

	return &Client{
		baseClient: c,
		Auth: auth.NewAuthClient(c),
		Exchanges: exchanges.NewExchangesClient(c),
		FeeSponsors: feesponsors.NewFeeSponsorsClient(c),
		Keys: keys.NewKeysClient(c),
		Networks: networks.NewNetworksClient(c),
		Permissions: permissions.NewPermissionsClient(c),
		Policies: policies.NewPoliciesClient(c),
		Signers: signers.NewSignersClient(c),
		Staking: staking.NewStakingClient(c),
		Wallets: wallets.NewWalletsClient(c),
		Webhooks: webhooks.NewWebhooksClient(c),
		Swaps: swaps.NewSwapsClient(c),
		Agreements: agreements.NewAgreementsClient(c),
		Allocations: allocations.NewAllocationsClient(c),
	}, nil
}