coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

ignore:
  - "agreements/**"
  - "allocations/**"
  - "auth/**"
  - "exchanges/**"
  - "feesponsors/**"
  - "keys/**"
  - "networks/**"
  - "payins/**"
  - "payouts/**"
  - "permissions/**"
  - "policies/**"
  - "signers/**"
  - "staking/**"
  - "swaps/**"
  - "vaults/**"
  - "wallets/**"
  - "webhooks/**"
  - "types/**"
  - "client.go"
  - "delegated_client.go"
  - "cmd/**"
