// Code generated by go-sdk-generator. DO NOT EDIT.

package dfns

import (
	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/agreements"
	"github.com/dfns/dfns-sdk-go/v2/allocations"
	"github.com/dfns/dfns-sdk-go/v2/auth"
	"github.com/dfns/dfns-sdk-go/v2/exchanges"
	"github.com/dfns/dfns-sdk-go/v2/feesponsors"
	"github.com/dfns/dfns-sdk-go/v2/keys"
	"github.com/dfns/dfns-sdk-go/v2/networks"
	"github.com/dfns/dfns-sdk-go/v2/payins"
	"github.com/dfns/dfns-sdk-go/v2/payouts"
	"github.com/dfns/dfns-sdk-go/v2/permissions"
	"github.com/dfns/dfns-sdk-go/v2/policies"
	"github.com/dfns/dfns-sdk-go/v2/signers"
	"github.com/dfns/dfns-sdk-go/v2/staking"
	"github.com/dfns/dfns-sdk-go/v2/swaps"
	"github.com/dfns/dfns-sdk-go/v2/vaults"
	"github.com/dfns/dfns-sdk-go/v2/wallets"
	"github.com/dfns/dfns-sdk-go/v2/webhooks"
)

// DelegatedClient is the Dfns API client for delegated user action signing. Its domain
// clients split signed operations into Init/Complete calls, so challenges can be signed
// out-of-band (e.g. by an end user) rather than by a Signer held in this process.
type DelegatedClient struct {
	baseClient *client.Client
	Agreements *agreements.DelegatedAgreementsClient
	Allocations *allocations.DelegatedAllocationsClient
	Auth *auth.DelegatedAuthClient
	Exchanges *exchanges.DelegatedExchangesClient
	FeeSponsors *feesponsors.DelegatedFeeSponsorsClient
	Keys *keys.DelegatedKeysClient
	Networks *networks.DelegatedNetworksClient
	Payins *payins.DelegatedPayinsClient
	Payouts *payouts.DelegatedPayoutsClient
	Permissions *permissions.DelegatedPermissionsClient
	Policies *policies.DelegatedPoliciesClient
	Signers *signers.DelegatedSignersClient
	Staking *staking.DelegatedStakingClient
	Swaps *swaps.DelegatedSwapsClient
	Vaults *vaults.DelegatedVaultsClient
	Wallets *wallets.DelegatedWalletsClient
	Webhooks *webhooks.DelegatedWebhooksClient
}

// NewDelegatedClient creates a new Dfns delegated API client. A Signer is not required
// on Options for delegated signing, since challenges are signed out-of-band.
func NewDelegatedClient(opts Options) (*DelegatedClient, error) {
	c, err := client.New(opts)
	if err != nil {
		return nil, err
	}

	return &DelegatedClient{
		baseClient: c,
		Agreements: agreements.NewDelegatedAgreementsClient(c),
		Allocations: allocations.NewDelegatedAllocationsClient(c),
		Auth: auth.NewDelegatedAuthClient(c),
		Exchanges: exchanges.NewDelegatedExchangesClient(c),
		FeeSponsors: feesponsors.NewDelegatedFeeSponsorsClient(c),
		Keys: keys.NewDelegatedKeysClient(c),
		Networks: networks.NewDelegatedNetworksClient(c),
		Payins: payins.NewDelegatedPayinsClient(c),
		Payouts: payouts.NewDelegatedPayoutsClient(c),
		Permissions: permissions.NewDelegatedPermissionsClient(c),
		Policies: policies.NewDelegatedPoliciesClient(c),
		Signers: signers.NewDelegatedSignersClient(c),
		Staking: staking.NewDelegatedStakingClient(c),
		Swaps: swaps.NewDelegatedSwapsClient(c),
		Vaults: vaults.NewDelegatedVaultsClient(c),
		Wallets: wallets.NewDelegatedWalletsClient(c),
		Webhooks: webhooks.NewDelegatedWebhooksClient(c),
	}, nil
}