// Code generated by go-sdk-generator. DO NOT EDIT.

package addresswatches

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// AddressWatchesClient provides methods for address_watches operations.
type AddressWatchesClient struct {
	client *client.Client
}

// NewAddressWatchesClient creates a new AddressWatchesClient.
func NewAddressWatchesClient(c *client.Client) *AddressWatchesClient {
	return &AddressWatchesClient{client: c}
}

// Retrieves the list of address watches in your organization. Pagination is supported via limit and paginationToken parameters.
func (c *AddressWatchesClient) ListAddressWatches(ctx context.Context, query *ListAddressWatchesQuery) (*ListAddressWatchesResponse, error) {
	path := "/address-watches"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAddressWatchesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Registers an on chain address to watch. An address watch is not controlled by Dfns: it holds no key, it cannot sign or move funds. The indexer matches on chain activity touching the address and sends the corresponding webhooks.
// 
// The address must already exist on chain and is normalized to the form the indexer matches on (lowercase for EVM networks). Only networks that support address watches are accepted. A given address can only be watched once per network within an organization while the watch is Active.
func (c *AddressWatchesClient) CreateAddressWatch(ctx context.Context, body CreateAddressWatchRequest) (*CreateAddressWatchResponse, error) {
	path := "/address-watches"
	var result CreateAddressWatchResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves an address watch by its ID.
func (c *AddressWatchesClient) GetAddressWatch(ctx context.Context, addressWatchID string) (*GetAddressWatchResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID)
	var result GetAddressWatchResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the list of assets held by the address watch, as tracked by the indexer. Balances are tracked from the moment the watch is created.
func (c *AddressWatchesClient) GetAddressWatchAssets(ctx context.Context, addressWatchID string, query *GetAddressWatchAssetsQuery) (*GetAddressWatchAssetsResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.NetWorth != nil {
			q.Set("netWorth", fmt.Sprintf("%v", *query.NetWorth))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of decoded blockchain events indexed for the specified address watch.
// 
// Blockchain events are not value transfers: asset and token transfers are listed by
func (c *AddressWatchesClient) GetAddressWatchBlockchainEvents(ctx context.Context, addressWatchID string, query *GetAddressWatchBlockchainEventsQuery) (*GetAddressWatchBlockchainEventsResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/blockchain-events"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Name != nil {
			q.Set("name", fmt.Sprintf("%v", *query.Name))
		}
		if query.Contract != nil {
			q.Set("contract", fmt.Sprintf("%v", *query.Contract))
		}
		if query.TxHash != nil {
			q.Set("txHash", fmt.Sprintf("%v", *query.TxHash))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchBlockchainEventsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the list of indexed on chain activities for the specified address watch.
// 
// The list reflects the indexed on chain activity from the moment the watch was created. Events from before the watch are not backfilled.
func (c *AddressWatchesClient) GetAddressWatchHistory(ctx context.Context, addressWatchID string, query *GetAddressWatchHistoryQuery) (*GetAddressWatchHistoryResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/history"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Direction != nil {
			q.Set("direction", fmt.Sprintf("%v", *query.Direction))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.Contract != nil {
			q.Set("contract", fmt.Sprintf("%v", *query.Contract))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchHistoryResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
