// Code generated by go-sdk-generator. DO NOT EDIT.

package addresswatches

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedAddressWatchesClient provides delegated user action signing for address_watches operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedAddressWatchesClient struct {
	client *client.Client
}

// NewDelegatedAddressWatchesClient creates a new DelegatedAddressWatchesClient.
func NewDelegatedAddressWatchesClient(c *client.Client) *DelegatedAddressWatchesClient {
	return &DelegatedAddressWatchesClient{client: c}
}

// Retrieves the list of address watches in your organization. Pagination is supported via limit and paginationToken parameters.
func (c *DelegatedAddressWatchesClient) ListAddressWatches(ctx context.Context, query *ListAddressWatchesQuery) (*ListAddressWatchesResponse, error) {
	path := "/address-watches"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAddressWatchesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateAddressWatchInit starts delegated user action signing for the createAddressWatch operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateAddressWatchComplete
// along with the same arguments given here.
func (c *DelegatedAddressWatchesClient) CreateAddressWatchInit(ctx context.Context, body CreateAddressWatchRequest) (*signer.UserActionChallenge, error) {
	path := "/address-watches"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateAddressWatchComplete finishes delegated signing for the createAddressWatch operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateAddressWatchInit challenge.
func (c *DelegatedAddressWatchesClient) CreateAddressWatchComplete(ctx context.Context, body CreateAddressWatchRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateAddressWatchResponse, error) {
	path := "/address-watches"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateAddressWatchResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves an address watch by its ID.
func (c *DelegatedAddressWatchesClient) GetAddressWatch(ctx context.Context, addressWatchID string) (*GetAddressWatchResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID)
	var result GetAddressWatchResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the list of assets held by the address watch, as tracked by the indexer. Balances are tracked from the moment the watch is created.
func (c *DelegatedAddressWatchesClient) GetAddressWatchAssets(ctx context.Context, addressWatchID string, query *GetAddressWatchAssetsQuery) (*GetAddressWatchAssetsResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.NetWorth != nil {
			q.Set("netWorth", fmt.Sprintf("%v", *query.NetWorth))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of decoded blockchain events indexed for the specified address watch.
// 
// Blockchain events are not value transfers: asset and token transfers are listed by
func (c *DelegatedAddressWatchesClient) GetAddressWatchBlockchainEvents(ctx context.Context, addressWatchID string, query *GetAddressWatchBlockchainEventsQuery) (*GetAddressWatchBlockchainEventsResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/blockchain-events"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Name != nil {
			q.Set("name", fmt.Sprintf("%v", *query.Name))
		}
		if query.Contract != nil {
			q.Set("contract", fmt.Sprintf("%v", *query.Contract))
		}
		if query.TxHash != nil {
			q.Set("txHash", fmt.Sprintf("%v", *query.TxHash))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchBlockchainEventsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the list of indexed on chain activities for the specified address watch.
// 
// The list reflects the indexed on chain activity from the moment the watch was created. Events from before the watch are not backfilled.
func (c *DelegatedAddressWatchesClient) GetAddressWatchHistory(ctx context.Context, addressWatchID string, query *GetAddressWatchHistoryQuery) (*GetAddressWatchHistoryResponse, error) {
	path := "/address-watches/" + url.PathEscape(addressWatchID) + "/history"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Direction != nil {
			q.Set("direction", fmt.Sprintf("%v", *query.Direction))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.Contract != nil {
			q.Set("contract", fmt.Sprintf("%v", *query.Contract))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetAddressWatchHistoryResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
