// Code generated by go-sdk-generator. DO NOT EDIT.

package networks

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/internal/client"
)

// NetworksClient provides methods for networks operations.
type NetworksClient struct {
	client *client.Client
}

// NewNetworksClient creates a new NetworksClient.
func NewNetworksClient(c *client.Client) *NetworksClient {
	return &NetworksClient{client: c}
}

// Gets real-time fee details for a given network, allowing users to make decisions based on their preferences for transaction speed/priority. Three levels of priority will be displayed: `slow`, `standard`, `fast`.
func (c *NetworksClient) EstimateFees(ctx context.Context, query *EstimateFeesQuery) (interface{}, error) {
	path := "/networks/fees"
	if query != nil {
		q := url.Values{}
		q.Set("network", fmt.Sprintf("%v", query.Network))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Call a read-only function on a smart contract. In Solidity, this use the `view` keyword.
// 
//   <Note>
func (c *NetworksClient) ReadContract(ctx context.Context, body ReadContractRequest) (*ReadContractResponse, error) {
	path := "/networks/read-contract"
	var result ReadContractResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Return a configured Canton Validator in your organization.
func (c *NetworksClient) GetCantonValidator(ctx context.Context, network string, validatorID string) (*GetCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	var result GetCantonValidatorResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update an existing Canton Validator configuration.
//   
//   Read details about the process [here](https://docs.dfns.co/networks/canton-validators).
func (c *NetworksClient) UpdateCantonValidator(ctx context.Context, network string, validatorID string, body UpdateCantonValidatorRequest) (*UpdateCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	var result UpdateCantonValidatorResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete a specific Canton Validator configuration.
func (c *NetworksClient) DeleteCantonValidator(ctx context.Context, network string, validatorID string) (*DeleteCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	var result DeleteCantonValidatorResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of configured Canton Validators in your organization.
func (c *NetworksClient) ListCantonValidators(ctx context.Context, network string, query *ListCantonValidatorsQuery) (*ListCantonValidatorsResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListCantonValidatorsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Link a Canton Validator to your organization. This is required in order to create wallets or interact with the Canton network.
// 
//   The `Shared` option allows you to use a shared validator hosted by DFNS and get started in seconds, while the `Custom` option allows you to connect your own validator and ledger nodes using OAuth2 authentication.
func (c *NetworksClient) CreateCantonValidator(ctx context.Context, network string, body CreateCantonValidatorRequest) (*CreateCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators"
	var result CreateCantonValidatorResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
