// Code generated by go-sdk-generator. DO NOT EDIT.

package networks

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedNetworksClient provides delegated user action signing for networks operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedNetworksClient struct {
	client *client.Client
}

// NewDelegatedNetworksClient creates a new DelegatedNetworksClient.
func NewDelegatedNetworksClient(c *client.Client) *DelegatedNetworksClient {
	return &DelegatedNetworksClient{client: c}
}

// Gets real-time fee details for a given network, allowing users to make decisions based on their preferences for transaction speed/priority. Three levels of priority will be displayed: `slow`, `standard`, `fast`.
func (c *DelegatedNetworksClient) EstimateFees(ctx context.Context, query *EstimateFeesQuery) (interface{}, error) {
	path := "/networks/fees"
	if query != nil {
		q := url.Values{}
		q.Set("network", fmt.Sprintf("%v", query.Network))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Call a read-only function on a smart contract. In Solidity, these are functions with the state mutability set to `view`.
// 
//   <Note>
func (c *DelegatedNetworksClient) CallFunction(ctx context.Context, network string, body CallFunctionRequest) (interface{}, error) {
	path := "/networks/" + url.PathEscape(network) + "/call-function"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Return a configured Canton Validator in your organization.
func (c *DelegatedNetworksClient) GetCantonValidator(ctx context.Context, network string, validatorID string) (*GetCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	var result GetCantonValidatorResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateCantonValidatorInit starts delegated user action signing for the updateCantonValidator operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateCantonValidatorComplete
// along with the same arguments given here.
func (c *DelegatedNetworksClient) UpdateCantonValidatorInit(ctx context.Context, network string, validatorID string, body UpdateCantonValidatorRequest) (*signer.UserActionChallenge, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateCantonValidatorComplete finishes delegated signing for the updateCantonValidator operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateCantonValidatorInit challenge.
func (c *DelegatedNetworksClient) UpdateCantonValidatorComplete(ctx context.Context, network string, validatorID string, body UpdateCantonValidatorRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateCantonValidatorResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteCantonValidatorInit starts delegated user action signing for the deleteCantonValidator operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteCantonValidatorComplete
// along with the same arguments given here.
func (c *DelegatedNetworksClient) DeleteCantonValidatorInit(ctx context.Context, network string, validatorID string) (*signer.UserActionChallenge, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteCantonValidatorComplete finishes delegated signing for the deleteCantonValidator operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteCantonValidatorInit challenge.
func (c *DelegatedNetworksClient) DeleteCantonValidatorComplete(ctx context.Context, network string, validatorID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators/" + url.PathEscape(validatorID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteCantonValidatorResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of configured Canton Validators in your organization.
func (c *DelegatedNetworksClient) ListCantonValidators(ctx context.Context, network string, query *ListCantonValidatorsQuery) (*ListCantonValidatorsResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListCantonValidatorsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateCantonValidatorInit starts delegated user action signing for the createCantonValidator operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateCantonValidatorComplete
// along with the same arguments given here.
func (c *DelegatedNetworksClient) CreateCantonValidatorInit(ctx context.Context, network string, body CreateCantonValidatorRequest) (*signer.UserActionChallenge, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateCantonValidatorComplete finishes delegated signing for the createCantonValidator operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateCantonValidatorInit challenge.
func (c *DelegatedNetworksClient) CreateCantonValidatorComplete(ctx context.Context, network string, body CreateCantonValidatorRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateCantonValidatorResponse, error) {
	path := "/networks/" + url.PathEscape(network) + "/validators"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateCantonValidatorResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
