// Code generated by go-sdk-generator. DO NOT EDIT.

package networks

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// EstimateFeesQuery represents query parameters.
type EstimateFeesQuery struct {
	Network string `json:"network"`
}

// ReadContractRequest represents the request body for the readContract operation.
type ReadContractRequest = any

// Read Contract
type ReadContractResponse struct {
	Kind string `json:"kind"`
	Data string `json:"data"`
}

// Get Canton Validator
type GetCantonValidatorResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Network string `json:"network"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
	PartyHint string `json:"partyHint"`
}

// Update Canton Validator
type UpdateCantonValidatorRequest struct {
	Name *string `json:"name,omitempty"`
	Validator *map[string]interface{} `json:"validator,omitempty"`
	Ledger *map[string]interface{} `json:"ledger,omitempty"`
}

// Update Canton Validator
type UpdateCantonValidatorResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Network string `json:"network"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
	PartyHint string `json:"partyHint"`
}

// Delete Canton Validator
type DeleteCantonValidatorResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Network string `json:"network"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
	PartyHint string `json:"partyHint"`
}

// List Canton Validators
type ListCantonValidatorsResponse struct {
	Items []types.CantonValidator `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListCantonValidatorsQuery represents query parameters.
type ListCantonValidatorsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateCantonValidatorRequest represents the request body for the createCantonValidator operation.
type CreateCantonValidatorRequest = any

// Create Canton Validator
type CreateCantonValidatorResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Network string `json:"network"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
	PartyHint string `json:"partyHint"`
}
