// Code generated by go-sdk-generator. DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/internal/client"
)

// AuthClient provides methods for auth operations.
type AuthClient struct {
	client *client.Client
}

// NewAuthClient creates a new AuthClient.
func NewAuthClient(c *client.Client) *AuthClient {
	return &AuthClient{client: c}
}

// Completes the user action signing process and provides a signing token that can be used to verify the user intended to perform the action.
// 
// This is the first step of the [User Action Signing flow](http://docs.dfns.co/api-reference/auth/signing-flows).
func (c *AuthClient) CreateUserActionSignature(ctx context.Context, body CreateUserActionSignatureRequest) (*CreateUserActionSignatureResponse, error) {
	path := "/auth/action"
	var result CreateUserActionSignatureResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user action signing session, returning a challenge that will be used to verify the user's intent to perform an action.
//   
//   This is the first step of the [User Action Signing flow](http://docs.dfns.co/api-reference/auth/signing-flows).
func (c *AuthClient) CreateUserActionChallenge(ctx context.Context, body CreateUserActionChallengeRequest) (*CreateUserActionChallengeResponse, error) {
	path := "/auth/action/init"
	var result CreateUserActionChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Gets all signature events which have occurred in the over the timeframe.  The max range the API supports is 7 days.
// 
// StartTime and EndTime are URL-encoded UTC ISO timestamps:    
func (c *AuthClient) ListAuditLogs(ctx context.Context, query *ListAuditLogsQuery) error {
	path := "/auth/action/logs"
	if query != nil {
		q := url.Values{}
		q.Set("startTime", fmt.Sprintf("%v", query.StartTime))
		q.Set("endTime", fmt.Sprintf("%v", query.EndTime))
		if query.UserID != nil {
			q.Set("userId", fmt.Sprintf("%v", *query.UserID))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	return c.client.Do(ctx, "GET", path, nil, nil, false)
}

// Gets detailed information for a particular audit log. Specifically, the API returns the action performed, as well as the `firstFactorCredential` in which you will find the signature information required to validate it. 
// 
// Dfns maintains a script which can be used for audit log signature validation: [WebAuthn Signature Verifier](https://github.com/dfns/example-scripts/tree/m/python/utils)
func (c *AuthClient) GetAuditLog(ctx context.Context, id string) (*GetAuditLogResponse, error) {
	path := "/auth/action/logs/" + url.PathEscape(id)
	var result GetAuditLogResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
//   Applications are deprecated and will be removed in a future release. See details [here](https://docs.dfns.co/developers/guides/applications-deprecation).
//   </Warning>
// Deprecated: This endpoint is deprecated.
func (c *AuthClient) ListApplications(ctx context.Context) (*ListApplicationsResponse, error) {
	path := "/auth/apps"
	var result ListApplicationsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
//   Applications are deprecated and will be removed in a future release. See details [here](https://docs.dfns.co/developers/guides/applications-deprecation).
//   </Warning>
// Deprecated: This endpoint is deprecated.
func (c *AuthClient) GetApplication(ctx context.Context, appID string) (*GetApplicationResponse, error) {
	path := "/auth/apps/" + url.PathEscape(appID)
	var result GetApplicationResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all credentials for a user.
func (c *AuthClient) ListCredentials(ctx context.Context) (*ListCredentialsResponse, error) {
	path := "/auth/credentials"
	var result ListCredentialsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the flow [Create Credential Regular flow](https://docs.dfns.co/api-reference/auth/credentials#regular-flow).
// 
// Adds a new credential to a user's account. See [Credential Kinds](https://docs.dfns.co/api-reference/auth/credentials#credential-kinds) for all supported credential types.
func (c *AuthClient) CreateCredential(ctx context.Context, body CreateCredentialRequest) (*CreateCredentialResponse, error) {
	path := "/auth/credentials"
	var result CreateCredentialResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the flow [Create Credential Regular flow](https://docs.dfns.co/api-reference/auth/credentials#regular-flow).
//   
//   Starts a create user credential session, returning a challenge that will be used to verify the user's identity.
func (c *AuthClient) CreateCredentialChallenge(ctx context.Context, body CreateCredentialChallengeRequest) (interface{}, error) {
	path := "/auth/credentials/init"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Activates a credential that was previously deactivated. If the credential is already activated no action is taken.
func (c *AuthClient) ActivateCredential(ctx context.Context, body ActivateCredentialRequest) (*ActivateCredentialResponse, error) {
	path := "/auth/credentials/activate"
	var result ActivateCredentialResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deactivates a credential that was previously active. If the credential is already deactivated no action is taken.
func (c *AuthClient) DeactivateCredential(ctx context.Context, body DeactivateCredentialRequest) (*DeactivateCredentialResponse, error) {
	path := "/auth/credentials/deactivate"
	var result DeactivateCredentialResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the [Create Credential With Code flow](https://docs.dfns.co/api-reference/auth/credentials#create-credential-with-code-flow).
// 
// Creates a one-time-code that can then be used to create a new credential from a place you don't have access to one of your existing credential.
func (c *AuthClient) CreateCredentialCode(ctx context.Context, body CreateCredentialCodeRequest) (*CreateCredentialCodeResponse, error) {
	path := "/auth/credentials/code"
	var result CreateCredentialCodeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the flow [Create Credential With Code](https://docs.dfns.co/api-reference/auth/credentials#create-credential-with-code-flow).
// 
// Creates a credential challenge using a one time code-time-code. This challenge must then be signed by the new credential, before finalizing the flow.
func (c *AuthClient) CreateCredentialChallengeWithCode(ctx context.Context, body CreateCredentialChallengeWithCodeRequest) (interface{}, error) {
	path := "/auth/credentials/code/init"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Finalizes the flow [Create Credential With Code](https://docs.dfns.co/api-reference/auth/credentials#create-credential-with-code-flow).
//   
// Adds a new credential to a user's account. This endpoint is similar to the [Create Credential](https://docs.dfns.co/api-reference/auth/create-credential) endpoint, except:
func (c *AuthClient) CreateCredentialWithCode(ctx context.Context, body CreateCredentialWithCodeRequest) (*CreateCredentialWithCodeResponse, error) {
	path := "/auth/credentials/code/verify"
	var result CreateCredentialWithCodeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Start a user login session, returning a challenge that will be used to verify the user's identity.
// 
// If the user has a credential of kind `PasswordProtectedKey` a temporary one time code needs to be passed in the `loginCode` field.
func (c *AuthClient) CreateLoginChallenge(ctx context.Context, body CreateLoginChallengeRequest) (*CreateLoginChallengeResponse, error) {
	path := "/auth/login/init"
	var result CreateLoginChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
// Only a [Service Account](https://docs.dfns.co/api-reference/auth/service-accounts) can use this endpoint.
// </Warning>
func (c *AuthClient) DelegatedLogin(ctx context.Context, body DelegatedLoginRequest) (*DelegatedLoginResponse, error) {
	path := "/auth/login/delegated"
	var result DelegatedLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the login process and provides the authenticated user with their authentication token.
// 
// The type of credentials used to login is determined by the `kind` field in the nested objects (`firstFactor` and `secondFactor`). Supported credential kinds are:
func (c *AuthClient) CompleteUserLogin(ctx context.Context, body CompleteUserLoginRequest) (interface{}, error) {
	path := "/auth/login"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Completes the user logout process.
func (c *AuthClient) Logout(ctx context.Context, body LogoutRequest) (*LogoutResponse, error) {
	path := "/auth/logout"
	var result LogoutResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Sends a temporary one time code to the user that can be used during login flow.
// 
// If the user has a credential of kind `PasswordProtectedKey` a temporary one time code needs to be passed in the `loginCode` field. That's because the [Create Login Challenge](https://docs.dfns.co/api-reference/auth/create-login-challenge) is unauthenticated and returns the encrypted private key of the user. So we need a first step to verify the identity of the user to prevent anybody from fetching the encrypted private key and trying to brute force it offline.
func (c *AuthClient) SendLoginCode(ctx context.Context, body SendLoginCodeRequest) (*SendLoginCodeResponse, error) {
	path := "/auth/login/code"
	var result SendLoginCodeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the login process and provides the authenticated user with their authentication token.
func (c *AuthClient) SocialLogin(ctx context.Context, body SocialLoginRequest) (*SocialLoginResponse, error) {
	path := "/auth/login/social"
	var result SocialLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the login process and provides the authenticated user with their authentication token.
func (c *AuthClient) CompleteSsoLogin(ctx context.Context, body CompleteSsoLoginRequest) (*CompleteSsoLoginResponse, error) {
	path := "/auth/login/sso"
	var result CompleteSsoLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Initialize the login process with SSO by returning the IdP Url to call.
func (c *AuthClient) InitiateSsoLogin(ctx context.Context, body InitiateSsoLoginRequest) (*InitiateSsoLoginResponse, error) {
	path := "/auth/login/sso/init"
	var result InitiateSsoLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of your Personal Access Tokens.
func (c *AuthClient) ListPersonalAccessTokens(ctx context.Context) (*ListPersonalAccessTokensResponse, error) {
	path := "/auth/pats"
	var result ListPersonalAccessTokensResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new Personal Access Token for the caller.
func (c *AuthClient) CreatePersonalAccessToken(ctx context.Context, body CreatePersonalAccessTokenRequest) (*CreatePersonalAccessTokenResponse, error) {
	path := "/auth/pats"
	var result CreatePersonalAccessTokenResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a specific Personal Access Token.
func (c *AuthClient) GetPersonalAccessToken(ctx context.Context, tokenID string) (*GetPersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	var result GetPersonalAccessTokenResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update a specific Personal Access Token.
func (c *AuthClient) UpdatePersonalAccessToken(ctx context.Context, tokenID string, body UpdatePersonalAccessTokenRequest) (*UpdatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	var result UpdatePersonalAccessTokenResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete a specific Personal Access Token.
func (c *AuthClient) DeletePersonalAccessToken(ctx context.Context, tokenID string) (*DeletePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	var result DeletePersonalAccessTokenResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Activate a specific Personal Access Token.
func (c *AuthClient) ActivatePersonalAccessToken(ctx context.Context, tokenID string) (*ActivatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/activate"
	var result ActivatePersonalAccessTokenResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deactivates a credential that was previously active. If the credential is already deactivated no action is taken.
func (c *AuthClient) DeactivatePersonalAccessToken(ctx context.Context, tokenID string) (*DeactivatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/deactivate"
	var result DeactivatePersonalAccessTokenResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
// Only a [Service Account](https://docs.dfns.co/api-reference/auth/service-accounts) can use this endpoint.
// </Warning>
func (c *AuthClient) CreateDelegatedRecoveryChallenge(ctx context.Context, body CreateDelegatedRecoveryChallengeRequest) (*CreateDelegatedRecoveryChallengeResponse, error) {
	path := "/auth/recover/user/delegated"
	var result CreateDelegatedRecoveryChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Recovers a user, using a recovery credential. After successfully recovering the user, all of the user's previous credentials and personal access tokens will be invalidated.
// 
// This flow requires cryptographic validation of newly created credential(s) using a recovery credential. The `recovery.credentialAssertion.clientData` field's challenge must be the _base64url-encoded_ representation of the `newCredential` object.
func (c *AuthClient) RecoverUser(ctx context.Context, body RecoverUserRequest) (*RecoverUserResponse, error) {
	path := "/auth/recover/user"
	var result RecoverUserResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user recovery session, returning a challenge that will be used to verify the user's identity.
func (c *AuthClient) CreateRecoveryChallenge(ctx context.Context, body CreateRecoveryChallengeRequest) (*CreateRecoveryChallengeResponse, error) {
	path := "/auth/recover/user/init"
	var result CreateRecoveryChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Send the user a recovery verification code. This code is used as a second factor to verify the user initiated the recovery request.
func (c *AuthClient) SendRecoveryCodeEmail(ctx context.Context, body SendRecoveryCodeEmailRequest) (*SendRecoveryCodeEmailResponse, error) {
	path := "/auth/recover/user/code"
	var result SendRecoveryCodeEmailResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
// Only a [Service Account](https://docs.dfns.co/api-reference/auth/service-accounts) can use this endpoint.
// </Warning>
func (c *AuthClient) CreateDelegatedRegistrationChallenge(ctx context.Context, body CreateDelegatedRegistrationChallengeRequest) (*CreateDelegatedRegistrationChallengeResponse, error) {
	path := "/auth/registration/delegated"
	var result CreateDelegatedRegistrationChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user registration session. It returns a challenge that will need to be signed by a passkey and used to perform the step [Complete User Registration](/api-reference/auth/register)
func (c *AuthClient) CreateRegistrationChallenge(ctx context.Context, body CreateRegistrationChallengeRequest) (*CreateRegistrationChallengeResponse, error) {
	path := "/auth/registration/init"
	var result CreateRegistrationChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts an end-user registration session by passing a JWT obtained by an IdP. It returns a challenge that will need to be signed by a passkey and used to perform [Complete End User Registration with Wallets](/api-reference/auth/register-end-user).
func (c *AuthClient) CreateSocialRegistrationChallenge(ctx context.Context, body CreateSocialRegistrationChallengeRequest) (*CreateSocialRegistrationChallengeResponse, error) {
	path := "/auth/registration/social"
	var result CreateSocialRegistrationChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the user registration process and creates the user's initial credentials.
// 
// The type of credentials being registered is determined by the `credentialKind` field in the nested objects (`firstFactorCredential` , `secondFactorCredential` and `RecoveryCredential`). Supported credential kinds are:
func (c *AuthClient) CompleteUserRegistration(ctx context.Context, body CompleteUserRegistrationRequest) (*CompleteUserRegistrationResponse, error) {
	path := "/auth/registration"
	var result CompleteUserRegistrationResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the end user registration process and creates the user's initial credentials along with delegated wallets for the new end user.
// 
// The type of credentials being registered is determined by the `credentialKind` field in the nested objects (`firstFactorCredential` , `secondFactorCredential` and `RecoveryCredential`). Supported credential kinds are:
func (c *AuthClient) CompleteEndUserRegistrationWithWallets(ctx context.Context, body CompleteEndUserRegistrationWithWalletsRequest) (*CompleteEndUserRegistrationWithWalletsResponse, error) {
	path := "/auth/registration/enduser"
	var result CompleteEndUserRegistrationWithWalletsResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Sends the user a new registration code. The previous registration code will be marked invalid. If the user has already completed their registration no action will be taken.
func (c *AuthClient) ResendRegistrationCode(ctx context.Context, body ResendRegistrationCodeRequest) (*ResendRegistrationCodeResponse, error) {
	path := "/auth/registration/code"
	var result ResendRegistrationCodeResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all Service Accounts in your organization.
func (c *AuthClient) ListServiceAccounts(ctx context.Context) (*ListServiceAccountsResponse, error) {
	path := "/auth/service-accounts"
	var result ListServiceAccountsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new Service Account for your organization.
func (c *AuthClient) CreateServiceAccount(ctx context.Context, body CreateServiceAccountRequest) (*CreateServiceAccountResponse, error) {
	path := "/auth/service-accounts"
	var result CreateServiceAccountResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get information about a specific Service Account.
func (c *AuthClient) GetServiceAccount(ctx context.Context, serviceAccountID string) (*GetServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	var result GetServiceAccountResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update a specific Service Account.
func (c *AuthClient) UpdateServiceAccount(ctx context.Context, serviceAccountID string, body UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	var result UpdateServiceAccountResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete a specific Service Account.
func (c *AuthClient) DeleteServiceAccount(ctx context.Context, serviceAccountID string) (*DeleteServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	var result DeleteServiceAccountResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Activate a specific Service Account.
func (c *AuthClient) ActivateServiceAccount(ctx context.Context, serviceAccountID string) (*ActivateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/activate"
	var result ActivateServiceAccountResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deactivate a specific Service Account.
func (c *AuthClient) DeactivateServiceAccount(ctx context.Context, serviceAccountID string) (*DeactivateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/deactivate"
	var result DeactivateServiceAccountResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Activate a specific User.
func (c *AuthClient) ActivateUser(ctx context.Context, userID string) (*ActivateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/activate"
	var result ActivateUserResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deactivate a specific User.
func (c *AuthClient) DeactivateUser(ctx context.Context, userID string) (*DeactivateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/deactivate"
	var result DeactivateUserResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific User.
func (c *AuthClient) GetUser(ctx context.Context, userID string) (*GetUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	var result GetUserResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update a specific User.
func (c *AuthClient) UpdateUser(ctx context.Context, userID string, body UpdateUserRequest) (*UpdateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	var result UpdateUserResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete a specific User.
func (c *AuthClient) DeleteUser(ctx context.Context, userID string) (*DeleteUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	var result DeleteUserResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all Users in your organization.
func (c *AuthClient) ListUsers(ctx context.Context, query *ListUsersQuery) (*ListUsersResponse, error) {
	path := "/auth/users"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListUsersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Invite a new user in the caller's org. This will create the user and send a registration email to the created User's email, with a registration code, and pointing him to complete his registration on Dfns Dashboard. The user is created without any permissions.
//   
//   <Note>If you want the created User to not know about about Dfns, and don't want him to 
func (c *AuthClient) CreateUser(ctx context.Context, body CreateUserRequest) (*CreateUserResponse, error) {
	path := "/auth/users"
	var result CreateUserResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
