// Code generated by go-sdk-generator. DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedAuthClient provides delegated user action signing for auth operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedAuthClient struct {
	client *client.Client
}

// NewDelegatedAuthClient creates a new DelegatedAuthClient.
func NewDelegatedAuthClient(c *client.Client) *DelegatedAuthClient {
	return &DelegatedAuthClient{client: c}
}

// Completes the user action signing process and provides a signing token that can be used to verify the user intended to perform the action.
// 
// This is the first step of the [User Action Signing flow](https://docs.dfns.co/api-reference/auth/signing-flows).
func (c *DelegatedAuthClient) CreateUserActionSignature(ctx context.Context, body CreateUserActionSignatureRequest) (*CreateUserActionSignatureResponse, error) {
	path := "/auth/action"
	var result CreateUserActionSignatureResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user action signing session, returning a challenge that will be used to verify the user's intent to perform an action.
//   
//   This is the first step of the [User Action Signing flow](https://docs.dfns.co/api-reference/auth/signing-flows).
func (c *DelegatedAuthClient) CreateUserActionChallenge(ctx context.Context, body CreateUserActionChallengeRequest) (*CreateUserActionChallengeResponse, error) {
	path := "/auth/action/init"
	var result CreateUserActionChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Gets all signature events which have occurred in the over the timeframe. The time range is unbounded, but the export is capped at 100,000 rows. When the result is truncated, the `X-Dfns-Result-Truncated: true` response header is set and a trailing `# TRUNCATED ...` line is appended to the CSV; narrow the time range to retrieve all data.
// 
// StartTime and EndTime are URL-encoded UTC ISO timestamps:
func (c *DelegatedAuthClient) ListAuditLogs(ctx context.Context, query *ListAuditLogsQuery) error {
	path := "/auth/action/logs"
	if query != nil {
		q := url.Values{}
		q.Set("startTime", fmt.Sprintf("%v", query.StartTime))
		q.Set("endTime", fmt.Sprintf("%v", query.EndTime))
		if query.UserID != nil {
			q.Set("userId", fmt.Sprintf("%v", *query.UserID))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	return c.client.Do(ctx, "GET", path, nil, nil, false)
}

// Gets detailed information for a particular audit log. Specifically, the API returns the action performed, as well as the `firstFactorCredential` in which you will find the signature information required to validate it. 
// 
// Dfns maintains a script which can be used for audit log signature validation: [WebAuthn Signature Verifier](https://github.com/dfns/example-scripts/tree/m/python/utils)
func (c *DelegatedAuthClient) GetAuditLog(ctx context.Context, id string) (*GetAuditLogResponse, error) {
	path := "/auth/action/logs/" + url.PathEscape(id)
	var result GetAuditLogResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
//   Applications are deprecated and will be removed in a future release. See details [here](https://docs.dfns.co/deprecation/applications-deprecation).
//   </Warning>
// Deprecated: This endpoint is deprecated.
func (c *DelegatedAuthClient) ListApplications(ctx context.Context) (*ListApplicationsResponse, error) {
	path := "/auth/apps"
	var result ListApplicationsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// <Warning>
//   Applications are deprecated and will be removed in a future release. See details [here](https://docs.dfns.co/deprecation/applications-deprecation).
//   </Warning>
// Deprecated: This endpoint is deprecated.
func (c *DelegatedAuthClient) GetApplication(ctx context.Context, appID string) (*GetApplicationResponse, error) {
	path := "/auth/apps/" + url.PathEscape(appID)
	var result GetApplicationResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all credentials for a user.
func (c *DelegatedAuthClient) ListCredentials(ctx context.Context) (*ListCredentialsResponse, error) {
	path := "/auth/credentials"
	var result ListCredentialsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateCredentialInit starts delegated user action signing for the createCredential operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateCredentialComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateCredentialInit(ctx context.Context, body CreateCredentialRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/credentials"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateCredentialComplete finishes delegated signing for the createCredential operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateCredentialInit challenge.
func (c *DelegatedAuthClient) CreateCredentialComplete(ctx context.Context, body CreateCredentialRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateCredentialResponse, error) {
	path := "/auth/credentials"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateCredentialResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the flow [Create Credential Regular flow](https://docs.dfns.co/api-reference/auth/credentials#regular-flow).
//   
//   Starts a create user credential session, returning a challenge that will be used to verify the user's identity.
func (c *DelegatedAuthClient) CreateCredentialChallenge(ctx context.Context, body CreateCredentialChallengeRequest) (interface{}, error) {
	path := "/auth/credentials/init"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ActivateCredentialInit starts delegated user action signing for the activateCredential operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivateCredentialComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) ActivateCredentialInit(ctx context.Context, body ActivateCredentialRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/credentials/activate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// ActivateCredentialComplete finishes delegated signing for the activateCredential operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivateCredentialInit challenge.
func (c *DelegatedAuthClient) ActivateCredentialComplete(ctx context.Context, body ActivateCredentialRequest, challengeID string, assertion *signer.CredentialAssertion) (*ActivateCredentialResponse, error) {
	path := "/auth/credentials/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivateCredentialResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteCredentialInit starts delegated user action signing for the deleteCredential operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteCredentialComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeleteCredentialInit(ctx context.Context, credentialUUID string) (*signer.UserActionChallenge, error) {
	path := "/auth/credentials/" + url.PathEscape(credentialUUID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteCredentialComplete finishes delegated signing for the deleteCredential operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteCredentialInit challenge.
func (c *DelegatedAuthClient) DeleteCredentialComplete(ctx context.Context, credentialUUID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteCredentialResponse, error) {
	path := "/auth/credentials/" + url.PathEscape(credentialUUID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteCredentialResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivateCredentialInit starts delegated user action signing for the deactivateCredential operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeactivateCredentialComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeactivateCredentialInit(ctx context.Context, body DeactivateCredentialRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/credentials/deactivate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// DeactivateCredentialComplete finishes delegated signing for the deactivateCredential operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeactivateCredentialInit challenge.
func (c *DelegatedAuthClient) DeactivateCredentialComplete(ctx context.Context, body DeactivateCredentialRequest, challengeID string, assertion *signer.CredentialAssertion) (*DeactivateCredentialResponse, error) {
	path := "/auth/credentials/deactivate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeactivateCredentialResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateCredentialCodeInit starts delegated user action signing for the createCredentialCode operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateCredentialCodeComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateCredentialCodeInit(ctx context.Context, body CreateCredentialCodeRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/credentials/code"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateCredentialCodeComplete finishes delegated signing for the createCredentialCode operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateCredentialCodeInit challenge.
func (c *DelegatedAuthClient) CreateCredentialCodeComplete(ctx context.Context, body CreateCredentialCodeRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateCredentialCodeResponse, error) {
	path := "/auth/credentials/code"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateCredentialCodeResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Part of the flow [Create Credential With Code](https://docs.dfns.co/api-reference/auth/credentials#create-credential-with-code-flow).
// 
// Creates a credential challenge using a one time code-time-code. This challenge must then be signed by the new credential, before finalizing the flow.
func (c *DelegatedAuthClient) CreateCredentialChallengeWithCode(ctx context.Context, body CreateCredentialChallengeWithCodeRequest) (interface{}, error) {
	path := "/auth/credentials/code/init"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Finalizes the flow [Create Credential With Code](https://docs.dfns.co/api-reference/auth/credentials#create-credential-with-code-flow).
//   
// Adds a new credential to a user's account. This endpoint is similar to the [Create Credential](https://docs.dfns.co/api-reference/auth/create-credential) endpoint, except:
func (c *DelegatedAuthClient) CreateCredentialWithCode(ctx context.Context, body CreateCredentialWithCodeRequest) (*CreateCredentialWithCodeResponse, error) {
	path := "/auth/credentials/code/verify"
	var result CreateCredentialWithCodeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Start a user login session, returning a challenge that will be used to verify the user's identity.
// 
// If the user has a credential of kind `PasswordProtectedKey` a temporary one time code needs to be passed in the `loginCode` field.
func (c *DelegatedAuthClient) CreateLoginChallenge(ctx context.Context, body CreateLoginChallengeRequest) (*CreateLoginChallengeResponse, error) {
	path := "/auth/login/init"
	var result CreateLoginChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DelegatedLoginInit starts delegated user action signing for the delegatedLogin operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DelegatedLoginComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DelegatedLoginInit(ctx context.Context, body DelegatedLoginRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/login/delegated"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// DelegatedLoginComplete finishes delegated signing for the delegatedLogin operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DelegatedLoginInit challenge.
func (c *DelegatedAuthClient) DelegatedLoginComplete(ctx context.Context, body DelegatedLoginRequest, challengeID string, assertion *signer.CredentialAssertion) (*DelegatedLoginResponse, error) {
	path := "/auth/login/delegated"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DelegatedLoginResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the login process and provides the authenticated user with their authentication token.
// 
// The type of credentials used to login is determined by the `kind` field in the nested objects (`firstFactor` and `secondFactor`). Supported credential kinds are:
func (c *DelegatedAuthClient) CompleteUserLogin(ctx context.Context, body CompleteUserLoginRequest) (interface{}, error) {
	path := "/auth/login"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Completes the user logout process.
func (c *DelegatedAuthClient) Logout(ctx context.Context, body LogoutRequest) (*LogoutResponse, error) {
	path := "/auth/logout"
	var result LogoutResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Sends a temporary one time code to the user that can be used during login flow.
// 
// If the user has a credential of kind `PasswordProtectedKey` a temporary one time code needs to be passed in the `loginCode` field. That's because the [Create Login Challenge](https://docs.dfns.co/api-reference/auth/create-login-challenge) is unauthenticated and returns the encrypted private key of the user. So we need a first step to verify the identity of the user to prevent anybody from fetching the encrypted private key and trying to brute force it offline.
func (c *DelegatedAuthClient) SendLoginCode(ctx context.Context, body SendLoginCodeRequest) (*SendLoginCodeResponse, error) {
	path := "/auth/login/code"
	var result SendLoginCodeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Logs a user in with a JWT id token issued by a social login provider and provides the authenticated user with their authentication token.
func (c *DelegatedAuthClient) SocialLogin(ctx context.Context, body SocialLoginRequest) (*SocialLoginResponse, error) {
	path := "/auth/login/social"
	var result SocialLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the SSO login process by exchanging the authorization code obtained from the identity provider for the user's authentication token.
func (c *DelegatedAuthClient) CompleteSsoLogin(ctx context.Context, body CompleteSsoLoginRequest) (*CompleteSsoLoginResponse, error) {
	path := "/auth/login/sso"
	var result CompleteSsoLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Initialize the login process with SSO by returning the IdP URL to call.
func (c *DelegatedAuthClient) InitiateSsoLogin(ctx context.Context, body InitiateSsoLoginRequest) (*InitiateSsoLoginResponse, error) {
	path := "/auth/login/sso/init"
	var result InitiateSsoLoginResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Only for TenantUsers - Exchanges the current user access token, for an org-bound or tenant-bound token. The user must have access to the target org / tenant. The new access token expiration won't exceed the current token's one.
func (c *DelegatedAuthClient) ExchangeAccessToken(ctx context.Context, body ExchangeAccessTokenRequest) (*ExchangeAccessTokenResponse, error) {
	path := "/auth/tokens"
	var result ExchangeAccessTokenResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of your Personal Access Tokens.
func (c *DelegatedAuthClient) ListPersonalAccessTokens(ctx context.Context) (*ListPersonalAccessTokensResponse, error) {
	path := "/auth/pats"
	var result ListPersonalAccessTokensResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePersonalAccessTokenInit starts delegated user action signing for the createPersonalAccessToken operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePersonalAccessTokenComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreatePersonalAccessTokenInit(ctx context.Context, body CreatePersonalAccessTokenRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/pats"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePersonalAccessTokenComplete finishes delegated signing for the createPersonalAccessToken operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePersonalAccessTokenInit challenge.
func (c *DelegatedAuthClient) CreatePersonalAccessTokenComplete(ctx context.Context, body CreatePersonalAccessTokenRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreatePersonalAccessTokenResponse, error) {
	path := "/auth/pats"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreatePersonalAccessTokenResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a specific Personal Access Token.
func (c *DelegatedAuthClient) GetPersonalAccessToken(ctx context.Context, tokenID string) (*GetPersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	var result GetPersonalAccessTokenResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdatePersonalAccessTokenInit starts delegated user action signing for the updatePersonalAccessToken operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdatePersonalAccessTokenComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) UpdatePersonalAccessTokenInit(ctx context.Context, tokenID string, body UpdatePersonalAccessTokenRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdatePersonalAccessTokenComplete finishes delegated signing for the updatePersonalAccessToken operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdatePersonalAccessTokenInit challenge.
func (c *DelegatedAuthClient) UpdatePersonalAccessTokenComplete(ctx context.Context, tokenID string, body UpdatePersonalAccessTokenRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdatePersonalAccessTokenResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeletePersonalAccessTokenInit starts delegated user action signing for the deletePersonalAccessToken operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeletePersonalAccessTokenComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeletePersonalAccessTokenInit(ctx context.Context, tokenID string) (*signer.UserActionChallenge, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeletePersonalAccessTokenComplete finishes delegated signing for the deletePersonalAccessToken operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeletePersonalAccessTokenInit challenge.
func (c *DelegatedAuthClient) DeletePersonalAccessTokenComplete(ctx context.Context, tokenID string, challengeID string, assertion *signer.CredentialAssertion) (*DeletePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeletePersonalAccessTokenResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ActivatePersonalAccessTokenInit starts delegated user action signing for the activatePersonalAccessToken operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivatePersonalAccessTokenComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) ActivatePersonalAccessTokenInit(ctx context.Context, tokenID string) (*signer.UserActionChallenge, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/activate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// ActivatePersonalAccessTokenComplete finishes delegated signing for the activatePersonalAccessToken operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivatePersonalAccessTokenInit challenge.
func (c *DelegatedAuthClient) ActivatePersonalAccessTokenComplete(ctx context.Context, tokenID string, challengeID string, assertion *signer.CredentialAssertion) (*ActivatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivatePersonalAccessTokenResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivatePersonalAccessTokenInit starts delegated user action signing for the deactivatePersonalAccessToken operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeactivatePersonalAccessTokenComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeactivatePersonalAccessTokenInit(ctx context.Context, tokenID string) (*signer.UserActionChallenge, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/deactivate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// DeactivatePersonalAccessTokenComplete finishes delegated signing for the deactivatePersonalAccessToken operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeactivatePersonalAccessTokenInit challenge.
func (c *DelegatedAuthClient) DeactivatePersonalAccessTokenComplete(ctx context.Context, tokenID string, challengeID string, assertion *signer.CredentialAssertion) (*DeactivatePersonalAccessTokenResponse, error) {
	path := "/auth/pats/" + url.PathEscape(tokenID) + "/deactivate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeactivatePersonalAccessTokenResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateDelegatedRecoveryChallengeInit starts delegated user action signing for the createDelegatedRecoveryChallenge operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateDelegatedRecoveryChallengeComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateDelegatedRecoveryChallengeInit(ctx context.Context, body CreateDelegatedRecoveryChallengeRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/recover/user/delegated"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateDelegatedRecoveryChallengeComplete finishes delegated signing for the createDelegatedRecoveryChallenge operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateDelegatedRecoveryChallengeInit challenge.
func (c *DelegatedAuthClient) CreateDelegatedRecoveryChallengeComplete(ctx context.Context, body CreateDelegatedRecoveryChallengeRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateDelegatedRecoveryChallengeResponse, error) {
	path := "/auth/recover/user/delegated"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateDelegatedRecoveryChallengeResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Recovers a user, using a recovery credential. After successfully recovering the user, all of the user's previous credentials and personal access tokens will be invalidated.
// 
// This flow requires cryptographic validation of newly created credential(s) using a recovery credential. The `recovery.credentialAssertion.clientData` field's challenge must be the _base64url-encoded_ representation of the `newCredential` object.
func (c *DelegatedAuthClient) RecoverUser(ctx context.Context, body RecoverUserRequest) (*RecoverUserResponse, error) {
	path := "/auth/recover/user"
	var result RecoverUserResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user recovery session, returning a challenge that will be used to verify the user's identity.
func (c *DelegatedAuthClient) CreateRecoveryChallenge(ctx context.Context, body CreateRecoveryChallengeRequest) (*CreateRecoveryChallengeResponse, error) {
	path := "/auth/recover/user/init"
	var result CreateRecoveryChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Send the user a recovery verification code. This code is used as a second factor to verify the user initiated the recovery request.
func (c *DelegatedAuthClient) SendRecoveryCodeEmail(ctx context.Context, body SendRecoveryCodeEmailRequest) (*SendRecoveryCodeEmailResponse, error) {
	path := "/auth/recover/user/code"
	var result SendRecoveryCodeEmailResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateDelegatedRegistrationChallengeInit starts delegated user action signing for the createDelegatedRegistrationChallenge operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateDelegatedRegistrationChallengeComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateDelegatedRegistrationChallengeInit(ctx context.Context, body CreateDelegatedRegistrationChallengeRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/registration/delegated"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateDelegatedRegistrationChallengeComplete finishes delegated signing for the createDelegatedRegistrationChallenge operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateDelegatedRegistrationChallengeInit challenge.
func (c *DelegatedAuthClient) CreateDelegatedRegistrationChallengeComplete(ctx context.Context, body CreateDelegatedRegistrationChallengeRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateDelegatedRegistrationChallengeResponse, error) {
	path := "/auth/registration/delegated"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateDelegatedRegistrationChallengeResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts a user registration session. It returns a challenge that will need to be signed by a passkey and used to perform the step [Complete User Registration](/api-reference/auth/complete-user-registration)
func (c *DelegatedAuthClient) CreateRegistrationChallenge(ctx context.Context, body CreateRegistrationChallengeRequest) (*CreateRegistrationChallengeResponse, error) {
	path := "/auth/registration/init"
	var result CreateRegistrationChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Starts an end-user registration session by passing a JWT obtained by an IdP. It returns a challenge that will need to be signed by a passkey and used to perform [Complete End User Registration with Wallets](/api-reference/auth/complete-end-user-registration-with-wallets).
func (c *DelegatedAuthClient) CreateSocialRegistrationChallenge(ctx context.Context, body CreateSocialRegistrationChallengeRequest) (*CreateSocialRegistrationChallengeResponse, error) {
	path := "/auth/registration/social"
	var result CreateSocialRegistrationChallengeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the user registration process and creates the user's initial credentials.
// 
// All credentials submitted in this call (`firstFactorCredential`, `secondFactorCredential`, `recoveryCredential`) sign the same challenge returned by the registration init endpoint ([Create Registration Challenge](https://docs.dfns.co/api-reference/auth/create-registration-challenge), [Create Delegated Registration Challenge](https://docs.dfns.co/api-reference/auth/create-delegated-registration-challenge), or [Create Social Registration Challenge](https://docs.dfns.co/api-reference/auth/create-social-registration-challenge)).
func (c *DelegatedAuthClient) CompleteUserRegistration(ctx context.Context, body CompleteUserRegistrationRequest) (*CompleteUserRegistrationResponse, error) {
	path := "/auth/registration"
	var result CompleteUserRegistrationResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Completes the end user registration process and creates the user's initial credentials along with delegated wallets for the new end user.
// 
// All credentials submitted in this call (`firstFactorCredential`, `secondFactorCredential`, `recoveryCredential`) sign the same challenge returned by the registration init endpoint ([Create Delegated Registration Challenge](https://docs.dfns.co/api-reference/auth/create-delegated-registration-challenge) or [Create Social Registration Challenge](https://docs.dfns.co/api-reference/auth/create-social-registration-challenge)).
func (c *DelegatedAuthClient) CompleteEndUserRegistrationWithWallets(ctx context.Context, body CompleteEndUserRegistrationWithWalletsRequest) (*CompleteEndUserRegistrationWithWalletsResponse, error) {
	path := "/auth/registration/enduser"
	var result CompleteEndUserRegistrationWithWalletsResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Sends the user a new registration code. The previous registration code will be marked invalid. If the user has already completed their registration no action will be taken.
func (c *DelegatedAuthClient) ResendRegistrationCode(ctx context.Context, body ResendRegistrationCodeRequest) (*ResendRegistrationCodeResponse, error) {
	path := "/auth/registration/code"
	var result ResendRegistrationCodeResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all Service Accounts in your organization.
func (c *DelegatedAuthClient) ListServiceAccounts(ctx context.Context) (*ListServiceAccountsResponse, error) {
	path := "/auth/service-accounts"
	var result ListServiceAccountsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateServiceAccountInit starts delegated user action signing for the createServiceAccount operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateServiceAccountComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateServiceAccountInit(ctx context.Context, body CreateServiceAccountRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/service-accounts"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateServiceAccountComplete finishes delegated signing for the createServiceAccount operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateServiceAccountInit challenge.
func (c *DelegatedAuthClient) CreateServiceAccountComplete(ctx context.Context, body CreateServiceAccountRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateServiceAccountResponse, error) {
	path := "/auth/service-accounts"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateServiceAccountResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get information about a specific Service Account.
func (c *DelegatedAuthClient) GetServiceAccount(ctx context.Context, serviceAccountID string) (*GetServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	var result GetServiceAccountResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateServiceAccountInit starts delegated user action signing for the updateServiceAccount operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateServiceAccountComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) UpdateServiceAccountInit(ctx context.Context, serviceAccountID string, body UpdateServiceAccountRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateServiceAccountComplete finishes delegated signing for the updateServiceAccount operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateServiceAccountInit challenge.
func (c *DelegatedAuthClient) UpdateServiceAccountComplete(ctx context.Context, serviceAccountID string, body UpdateServiceAccountRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateServiceAccountResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteServiceAccountInit starts delegated user action signing for the deleteServiceAccount operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteServiceAccountComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeleteServiceAccountInit(ctx context.Context, serviceAccountID string, query *DeleteServiceAccountQuery) (*signer.UserActionChallenge, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	if query != nil {
		q := url.Values{}
		if query.Force != nil {
			q.Set("force", fmt.Sprintf("%v", *query.Force))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteServiceAccountComplete finishes delegated signing for the deleteServiceAccount operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteServiceAccountInit challenge.
func (c *DelegatedAuthClient) DeleteServiceAccountComplete(ctx context.Context, serviceAccountID string, query *DeleteServiceAccountQuery, challengeID string, assertion *signer.CredentialAssertion) (*DeleteServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID)
	if query != nil {
		q := url.Values{}
		if query.Force != nil {
			q.Set("force", fmt.Sprintf("%v", *query.Force))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteServiceAccountResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ActivateServiceAccountInit starts delegated user action signing for the activateServiceAccount operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivateServiceAccountComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) ActivateServiceAccountInit(ctx context.Context, serviceAccountID string) (*signer.UserActionChallenge, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/activate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// ActivateServiceAccountComplete finishes delegated signing for the activateServiceAccount operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivateServiceAccountInit challenge.
func (c *DelegatedAuthClient) ActivateServiceAccountComplete(ctx context.Context, serviceAccountID string, challengeID string, assertion *signer.CredentialAssertion) (*ActivateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivateServiceAccountResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivateServiceAccountInit starts delegated user action signing for the deactivateServiceAccount operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeactivateServiceAccountComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeactivateServiceAccountInit(ctx context.Context, serviceAccountID string, body DeactivateServiceAccountRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/deactivate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// DeactivateServiceAccountComplete finishes delegated signing for the deactivateServiceAccount operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeactivateServiceAccountInit challenge.
func (c *DelegatedAuthClient) DeactivateServiceAccountComplete(ctx context.Context, serviceAccountID string, body DeactivateServiceAccountRequest, challengeID string, assertion *signer.CredentialAssertion) (*DeactivateServiceAccountResponse, error) {
	path := "/auth/service-accounts/" + url.PathEscape(serviceAccountID) + "/deactivate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeactivateServiceAccountResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ActivateUserInit starts delegated user action signing for the activateUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivateUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) ActivateUserInit(ctx context.Context, userID string) (*signer.UserActionChallenge, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/activate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// ActivateUserComplete finishes delegated signing for the activateUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivateUserInit challenge.
func (c *DelegatedAuthClient) ActivateUserComplete(ctx context.Context, userID string, challengeID string, assertion *signer.CredentialAssertion) (*ActivateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivateUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivateUserInit starts delegated user action signing for the deactivateUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeactivateUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeactivateUserInit(ctx context.Context, userID string) (*signer.UserActionChallenge, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/deactivate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// DeactivateUserComplete finishes delegated signing for the deactivateUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeactivateUserInit challenge.
func (c *DelegatedAuthClient) DeactivateUserComplete(ctx context.Context, userID string, challengeID string, assertion *signer.CredentialAssertion) (*DeactivateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID) + "/deactivate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeactivateUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific User.
func (c *DelegatedAuthClient) GetUser(ctx context.Context, userID string) (*GetUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	var result GetUserResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUserInit starts delegated user action signing for the updateUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) UpdateUserInit(ctx context.Context, userID string, body UpdateUserRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateUserComplete finishes delegated signing for the updateUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateUserInit challenge.
func (c *DelegatedAuthClient) UpdateUserComplete(ctx context.Context, userID string, body UpdateUserRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteUserInit starts delegated user action signing for the deleteUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) DeleteUserInit(ctx context.Context, userID string) (*signer.UserActionChallenge, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteUserComplete finishes delegated signing for the deleteUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteUserInit challenge.
func (c *DelegatedAuthClient) DeleteUserComplete(ctx context.Context, userID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteUserResponse, error) {
	path := "/auth/users/" + url.PathEscape(userID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// List all Users in your organization.
func (c *DelegatedAuthClient) ListUsers(ctx context.Context, query *ListUsersQuery) (*ListUsersResponse, error) {
	path := "/auth/users"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListUsersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateUserInit starts delegated user action signing for the createUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) CreateUserInit(ctx context.Context, body CreateUserRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/users"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateUserComplete finishes delegated signing for the createUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateUserInit challenge.
func (c *DelegatedAuthClient) CreateUserComplete(ctx context.Context, body CreateUserRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateUserResponse, error) {
	path := "/auth/users"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// InviteTenantUserInit starts delegated user action signing for the inviteTenantUser operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to InviteTenantUserComplete
// along with the same arguments given here.
func (c *DelegatedAuthClient) InviteTenantUserInit(ctx context.Context, body InviteTenantUserRequest) (*signer.UserActionChallenge, error) {
	path := "/auth/users/invite"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// InviteTenantUserComplete finishes delegated signing for the inviteTenantUser operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the InviteTenantUserInit challenge.
func (c *DelegatedAuthClient) InviteTenantUserComplete(ctx context.Context, body InviteTenantUserRequest, challengeID string, assertion *signer.CredentialAssertion) (*InviteTenantUserResponse, error) {
	path := "/auth/users/invite"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result InviteTenantUserResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
