// Code generated by go-sdk-generator. DO NOT EDIT.

package auth

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// Create User Action Signature
type CreateUserActionSignatureRequest struct {
	ChallengeIdentifier string `json:"challengeIdentifier"`
	FirstFactor interface{} `json:"firstFactor"`
	SecondFactor interface{} `json:"secondFactor,omitempty"`
}

// Create User Action Signature
type CreateUserActionSignatureResponse struct {
	UserAction string `json:"userAction"`
}

// Create User Action Challenge
type CreateUserActionChallengeRequest struct {
	UserActionServerKind *string `json:"userActionServerKind,omitempty"`
	UserActionHTTPMethod string `json:"userActionHttpMethod"`
	UserActionHTTPPath string `json:"userActionHttpPath"`
	UserActionPayload string `json:"userActionPayload"`
}

// Create User Action Challenge
type CreateUserActionChallengeResponse struct {
	Challenge string `json:"challenge"`
	ChallengeIdentifier string `json:"challengeIdentifier"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds []map[string]interface{} `json:"supportedCredentialKinds"`
	UserVerification string `json:"userVerification"`
	Attestation string `json:"attestation"`
	AllowCredentials map[string]interface{} `json:"allowCredentials"`
	ExternalAuthenticationURL string `json:"externalAuthenticationUrl"`
}

// ListAuditLogsQuery represents query parameters.
type ListAuditLogsQuery struct {
	StartTime string `json:"startTime"`
	EndTime string `json:"endTime"`
	UserID *string `json:"userId,omitempty"`
}

// Get Audit Log
type GetAuditLogResponse struct {
	ID interface{} `json:"id"`
	Action string `json:"action"`
	ActionToken string `json:"actionToken"`
	UserID interface{} `json:"userId"`
	Username interface{} `json:"username"`
	DatePerformed string `json:"datePerformed"`
	FirstFactorCredential map[string]interface{} `json:"firstFactorCredential"`
}

// List Applications
type ListApplicationsResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// Get Application
type GetApplicationResponse struct {
	AppID string `json:"appId"`
	Kind string `json:"kind"`
	OrgID string `json:"orgId"`
	ExpectedRpID *string `json:"expectedRpId,omitempty"`
	Name string `json:"name"`
	IsActive bool `json:"isActive"`
	ExpectedOrigin *string `json:"expectedOrigin,omitempty"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// List Credentials
type ListCredentialsResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// CreateCredentialRequest represents the request body for the createCredential operation.
type CreateCredentialRequest = any

// Create Credential
type CreateCredentialResponse struct {
	Kind string `json:"kind"`
	CredentialID string `json:"credentialId"`
	CredentialUUID string `json:"credentialUuid"`
	DateCreated string `json:"dateCreated"`
	IsActive bool `json:"isActive"`
	Name string `json:"name"`
	PublicKey string `json:"publicKey"`
	RelyingPartyID string `json:"relyingPartyId"`
	Origin string `json:"origin"`
}

// Create Credential Challenge
type CreateCredentialChallengeRequest struct {
	Kind map[string]interface{} `json:"kind"`
}

// Activate Credential
type ActivateCredentialRequest struct {
	CredentialUUID string `json:"credentialUuid"`
}

// Activate Credential
type ActivateCredentialResponse struct {
	Message string `json:"message"`
}

// Deactivate Credential
type DeactivateCredentialRequest struct {
	CredentialUUID string `json:"credentialUuid"`
}

// Deactivate Credential
type DeactivateCredentialResponse struct {
	Message string `json:"message"`
}

// Create Credential Code
type CreateCredentialCodeRequest struct {
	Expiration interface{} `json:"expiration"`
}

// Create Credential Code
type CreateCredentialCodeResponse struct {
	Code string `json:"code"`
	Expiration string `json:"expiration"`
}

// Create Credential Challenge With Code
type CreateCredentialChallengeWithCodeRequest struct {
	CredentialKind string `json:"credentialKind"`
	Code string `json:"code"`
}

// CreateCredentialWithCodeRequest represents the request body for the createCredentialWithCode operation.
type CreateCredentialWithCodeRequest = any

// Create Credential With Code
type CreateCredentialWithCodeResponse struct {
	Kind string `json:"kind"`
	CredentialID string `json:"credentialId"`
	CredentialUUID string `json:"credentialUuid"`
	DateCreated string `json:"dateCreated"`
	IsActive bool `json:"isActive"`
	Name string `json:"name"`
	PublicKey string `json:"publicKey"`
	RelyingPartyID string `json:"relyingPartyId"`
	Origin string `json:"origin"`
}

// Create Login Challenge
type CreateLoginChallengeRequest struct {
	Username *string `json:"username,omitempty"`
	OrgID string `json:"orgId"`
	LoginCode *string `json:"loginCode,omitempty"`
}

// Create Login Challenge
type CreateLoginChallengeResponse struct {
	Challenge string `json:"challenge"`
	ChallengeIdentifier string `json:"challengeIdentifier"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds []map[string]interface{} `json:"supportedCredentialKinds"`
	UserVerification string `json:"userVerification"`
	Attestation string `json:"attestation"`
	AllowCredentials map[string]interface{} `json:"allowCredentials"`
	ExternalAuthenticationURL string `json:"externalAuthenticationUrl"`
}

// Delegated Login
type DelegatedLoginRequest struct {
	Username string `json:"username"`
}

// Delegated Login
type DelegatedLoginResponse struct {
	Token string `json:"token"`
}

// Complete User Login
type CompleteUserLoginRequest struct {
	ChallengeIdentifier string `json:"challengeIdentifier"`
	FirstFactor interface{} `json:"firstFactor"`
	SecondFactor interface{} `json:"secondFactor,omitempty"`
}

// Logout
type LogoutRequest struct {
	AllSessions *bool `json:"allSessions,omitempty"`
}

// Logout
type LogoutResponse struct {
	Message string `json:"message"`
}

// Send Login Code
type SendLoginCodeRequest struct {
	Username string `json:"username"`
	OrgID string `json:"orgId"`
}

// Send Login Code
type SendLoginCodeResponse struct {
	Message string `json:"message"`
}

// Social Login
type SocialLoginRequest struct {
	OrgID *string `json:"orgId,omitempty"`
	SocialLoginProviderKind string `json:"socialLoginProviderKind"`
	IDToken string `json:"idToken"`
}

// Social Login
type SocialLoginResponse struct {
	Token string `json:"token"`
}

// Complete SSO Login
type CompleteSsoLoginRequest struct {
	Code string `json:"code"`
	State string `json:"state"`
}

// Complete SSO Login
type CompleteSsoLoginResponse struct {
	Token string `json:"token"`
}

// Initiate SSO Login
type InitiateSsoLoginRequest struct {
	OrgID string `json:"orgId"`
	ClientID string `json:"clientId"`
	RedirectURI string `json:"redirectUri"`
}

// Initiate SSO Login
type InitiateSsoLoginResponse struct {
	SsoRedirectURL string `json:"ssoRedirectUrl"`
}

// List Personal Access Tokens
type ListPersonalAccessTokensResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// Create Personal Access Token
type CreatePersonalAccessTokenRequest struct {
	Name string `json:"name"`
	PublicKey string `json:"publicKey"`
	PermissionID *string `json:"permissionId,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	DaysValid *int64 `json:"daysValid,omitempty"`
	SecondsValid *int64 `json:"secondsValid,omitempty"`
}

// Create Personal Access Token
type CreatePersonalAccessTokenResponse struct {
	AccessToken string `json:"accessToken"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// Get Personal Access Token
type GetPersonalAccessTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
}

// Update Personal Access Token
type UpdatePersonalAccessTokenRequest struct {
	Name *string `json:"name,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Update Personal Access Token
type UpdatePersonalAccessTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
}

// Delete Personal Access Token
type DeletePersonalAccessTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
}

// Activate Personal Access Token
type ActivatePersonalAccessTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
}

// Deactivate Personal Access Token
type DeactivatePersonalAccessTokenResponse struct {
	AccessToken *string `json:"accessToken,omitempty"`
	DateCreated string `json:"dateCreated"`
	CredID string `json:"credId"`
	IsActive bool `json:"isActive"`
	Kind string `json:"kind"`
	LinkedUserID string `json:"linkedUserId"`
	LinkedAppID string `json:"linkedAppId"`
	Name string `json:"name"`
	OrgID string `json:"orgId"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
	PublicKey string `json:"publicKey"`
	TokenID string `json:"tokenId"`
}

// Create Delegated Recovery Challenge
type CreateDelegatedRecoveryChallengeRequest struct {
	Username string `json:"username"`
	CredentialID string `json:"credentialId"`
}

// Create Delegated Recovery Challenge
type CreateDelegatedRecoveryChallengeResponse struct {
	User map[string]interface{} `json:"user"`
	TemporaryAuthenticationToken string `json:"temporaryAuthenticationToken"`
	Challenge string `json:"challenge"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds map[string]interface{} `json:"supportedCredentialKinds"`
	AuthenticatorSelection map[string]interface{} `json:"authenticatorSelection"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []map[string]interface{} `json:"pubKeyCredParams"`
	ExcludeCredentials []map[string]interface{} `json:"excludeCredentials"`
	OtpURL string `json:"otpUrl"`
	AllowedRecoveryCredentials []map[string]interface{} `json:"allowedRecoveryCredentials"`
}

// Recover User
type RecoverUserRequest struct {
	Recovery map[string]interface{} `json:"recovery"`
	NewCredentials map[string]interface{} `json:"newCredentials"`
}

// Recover User
type RecoverUserResponse struct {
	Credential map[string]interface{} `json:"credential"`
	User map[string]interface{} `json:"user"`
}

// Create Recovery Challenge
type CreateRecoveryChallengeRequest struct {
	Username string `json:"username"`
	VerificationCode string `json:"verificationCode"`
	OrgID string `json:"orgId"`
	CredentialID string `json:"credentialId"`
}

// Create Recovery Challenge
type CreateRecoveryChallengeResponse struct {
	User map[string]interface{} `json:"user"`
	TemporaryAuthenticationToken string `json:"temporaryAuthenticationToken"`
	Challenge string `json:"challenge"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds map[string]interface{} `json:"supportedCredentialKinds"`
	AuthenticatorSelection map[string]interface{} `json:"authenticatorSelection"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []map[string]interface{} `json:"pubKeyCredParams"`
	ExcludeCredentials []map[string]interface{} `json:"excludeCredentials"`
	OtpURL string `json:"otpUrl"`
	AllowedRecoveryCredentials []map[string]interface{} `json:"allowedRecoveryCredentials"`
}

// Send Recovery Code Email
type SendRecoveryCodeEmailRequest struct {
	Username string `json:"username"`
	OrgID string `json:"orgId"`
}

// Send Recovery Code Email
type SendRecoveryCodeEmailResponse struct {
	Message string `json:"message"`
}

// Create Delegated Registration Challenge
type CreateDelegatedRegistrationChallengeRequest struct {
	Email string `json:"email"`
	Kind string `json:"kind"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Create Delegated Registration Challenge
type CreateDelegatedRegistrationChallengeResponse struct {
	User map[string]interface{} `json:"user"`
	TemporaryAuthenticationToken string `json:"temporaryAuthenticationToken"`
	Challenge string `json:"challenge"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds map[string]interface{} `json:"supportedCredentialKinds"`
	AuthenticatorSelection map[string]interface{} `json:"authenticatorSelection"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []map[string]interface{} `json:"pubKeyCredParams"`
	ExcludeCredentials []map[string]interface{} `json:"excludeCredentials"`
	OtpURL string `json:"otpUrl"`
}

// Create Registration Challenge
type CreateRegistrationChallengeRequest struct {
	OrgID string `json:"orgId"`
	Username string `json:"username"`
	RegistrationCode string `json:"registrationCode"`
}

// Create Registration Challenge
type CreateRegistrationChallengeResponse struct {
	User map[string]interface{} `json:"user"`
	TemporaryAuthenticationToken string `json:"temporaryAuthenticationToken"`
	Challenge string `json:"challenge"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds map[string]interface{} `json:"supportedCredentialKinds"`
	AuthenticatorSelection map[string]interface{} `json:"authenticatorSelection"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []map[string]interface{} `json:"pubKeyCredParams"`
	ExcludeCredentials []map[string]interface{} `json:"excludeCredentials"`
	OtpURL string `json:"otpUrl"`
}

// Create Social Registration Challenge
type CreateSocialRegistrationChallengeRequest struct {
	OrgID *string `json:"orgId,omitempty"`
	SocialLoginProviderKind string `json:"socialLoginProviderKind"`
	IDToken string `json:"idToken"`
}

// Create Social Registration Challenge
type CreateSocialRegistrationChallengeResponse struct {
	User map[string]interface{} `json:"user"`
	TemporaryAuthenticationToken string `json:"temporaryAuthenticationToken"`
	Challenge string `json:"challenge"`
	Rp *map[string]interface{} `json:"rp,omitempty"`
	SupportedCredentialKinds map[string]interface{} `json:"supportedCredentialKinds"`
	AuthenticatorSelection map[string]interface{} `json:"authenticatorSelection"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []map[string]interface{} `json:"pubKeyCredParams"`
	ExcludeCredentials []map[string]interface{} `json:"excludeCredentials"`
	OtpURL string `json:"otpUrl"`
}

// Complete User Registration
type CompleteUserRegistrationRequest struct {
	FirstFactorCredential interface{} `json:"firstFactorCredential"`
	SecondFactorCredential interface{} `json:"secondFactorCredential,omitempty"`
	RecoveryCredential *map[string]interface{} `json:"recoveryCredential,omitempty"`
}

// Complete User Registration
type CompleteUserRegistrationResponse struct {
	Credential map[string]interface{} `json:"credential"`
	User map[string]interface{} `json:"user"`
}

// Complete End User Registration with Wallets
type CompleteEndUserRegistrationWithWalletsRequest struct {
	FirstFactorCredential interface{} `json:"firstFactorCredential"`
	SecondFactorCredential interface{} `json:"secondFactorCredential,omitempty"`
	RecoveryCredential *map[string]interface{} `json:"recoveryCredential,omitempty"`
	Wallets []map[string]interface{} `json:"wallets"`
}

// Complete End User Registration with Wallets
type CompleteEndUserRegistrationWithWalletsResponse struct {
	Credential map[string]interface{} `json:"credential"`
	User map[string]interface{} `json:"user"`
	Authentication map[string]interface{} `json:"authentication"`
	Wallets []types.Wallet `json:"wallets"`
}

// Resend Registration Code
type ResendRegistrationCodeRequest struct {
	Username string `json:"username"`
	OrgID string `json:"orgId"`
}

// Resend Registration Code
type ResendRegistrationCodeResponse struct {
	Message string `json:"message"`
}

// List Service Accounts
type ListServiceAccountsResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// Create Service Account
type CreateServiceAccountRequest struct {
	Name string `json:"name"`
	PublicKey string `json:"publicKey"`
	PermissionID *string `json:"permissionId,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	DaysValid *int64 `json:"daysValid,omitempty"`
}

// Create Service Account
type CreateServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Get Service Account
type GetServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Update Service Account
type UpdateServiceAccountRequest struct {
	Name *string `json:"name,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Update Service Account
type UpdateServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Delete Service Account
type DeleteServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Activate Service Account
type ActivateServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Deactivate Service Account
type DeactivateServiceAccountResponse struct {
	UserInfo map[string]interface{} `json:"userInfo"`
	AccessTokens []map[string]interface{} `json:"accessTokens"`
}

// Activate User
type ActivateUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// Deactivate User
type DeactivateUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// Get User
type GetUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// Update User
type UpdateUserRequest struct {
	IsSSORequired bool `json:"isSSORequired"`
}

// Update User
type UpdateUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// Delete User
type DeleteUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}

// List Users
type ListUsersResponse struct {
	Items []types.User `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListUsersQuery represents query parameters.
type ListUsersQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	Kind *string `json:"kind,omitempty"`
}

// Create User
type CreateUserRequest struct {
	Email string `json:"email"`
	Kind string `json:"kind"`
	PublicKey *string `json:"publicKey,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	IsSSORequired *bool `json:"isSSORequired,omitempty"`
}

// Create User
type CreateUserResponse struct {
	Username string `json:"username"`
	Name string `json:"name"`
	UserID string `json:"userId"`
	Kind string `json:"kind"`
	CredentialUUID string `json:"credentialUuid"`
	OrgID string `json:"orgId"`
	Permissions []string `json:"permissions,omitempty"`
	IsActive bool `json:"isActive"`
	IsServiceAccount bool `json:"isServiceAccount"`
	IsRegistered bool `json:"isRegistered"`
	IsSSORequired bool `json:"isSSORequired"`
	PermissionAssignments []map[string]interface{} `json:"permissionAssignments"`
}
