// Code generated by go-sdk-generator. DO NOT EDIT.

package swaps

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/internal/client"
)

// SwapsClient provides methods for swaps operations.
type SwapsClient struct {
	client *client.Client
}

// NewSwapsClient creates a new SwapsClient.
func NewSwapsClient(c *client.Client) *SwapsClient {
	return &SwapsClient{client: c}
}

// List all swaps with pagination
func (c *SwapsClient) ListSwaps(ctx context.Context, query *ListSwapsQuery) (*ListSwapsResponse, error) {
	path := "/swaps"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListSwapsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new swap based on an existing quote. This is the second step of the [Swap flow](https://docs.dfns.co/api-reference/swaps#flow-overview).
func (c *SwapsClient) CreateSwap(ctx context.Context, body CreateSwapRequest) (*CreateSwapResponse, error) {
	path := "/swaps"
	var result CreateSwapResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Request a quote from a given provider for swapping assets. This is the first step of the [Swap flow](https://docs.dfns.co/api-reference/swaps#flow-overview).
func (c *SwapsClient) RequestSwapQuote(ctx context.Context, body RequestSwapQuoteRequest) (*RequestSwapQuoteResponse, error) {
	path := "/swaps/quotes"
	var result RequestSwapQuoteResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get details of a specific swap by its ID
func (c *SwapsClient) GetSwap(ctx context.Context, swapID string) (*GetSwapResponse, error) {
	path := "/swaps/" + url.PathEscape(swapID)
	var result GetSwapResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get details of a specific swap quote by its ID
func (c *SwapsClient) GetSwapQuote(ctx context.Context, quoteID string) (*GetSwapQuoteResponse, error) {
	path := "/swaps/quotes/" + url.PathEscape(quoteID)
	var result GetSwapQuoteResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
