// Code generated by go-sdk-generator. DO NOT EDIT.

package swaps

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedSwapsClient provides delegated user action signing for swaps operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedSwapsClient struct {
	client *client.Client
}

// NewDelegatedSwapsClient creates a new DelegatedSwapsClient.
func NewDelegatedSwapsClient(c *client.Client) *DelegatedSwapsClient {
	return &DelegatedSwapsClient{client: c}
}

// List all swaps with pagination
func (c *DelegatedSwapsClient) ListSwaps(ctx context.Context, query *ListSwapsQuery) (*ListSwapsResponse, error) {
	path := "/swaps"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListSwapsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateSwapInit starts delegated user action signing for the createSwap operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateSwapComplete
// along with the same arguments given here.
func (c *DelegatedSwapsClient) CreateSwapInit(ctx context.Context, body CreateSwapRequest) (*signer.UserActionChallenge, error) {
	path := "/swaps"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateSwapComplete finishes delegated signing for the createSwap operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateSwapInit challenge.
func (c *DelegatedSwapsClient) CreateSwapComplete(ctx context.Context, body CreateSwapRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateSwapResponse, error) {
	path := "/swaps"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateSwapResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Request a quote from a given provider for swapping assets. This is the first step of the [Swap flow](https://docs.dfns.co/api-reference/swaps#flow-overview).
func (c *DelegatedSwapsClient) RequestSwapQuote(ctx context.Context, body RequestSwapQuoteRequest) (*RequestSwapQuoteResponse, error) {
	path := "/swaps/quotes"
	var result RequestSwapQuoteResponse
	err := c.client.Do(ctx, "POST", path, body, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get details of a specific swap by its ID
func (c *DelegatedSwapsClient) GetSwap(ctx context.Context, swapID string) (*GetSwapResponse, error) {
	path := "/swaps/" + url.PathEscape(swapID)
	var result GetSwapResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get details of a specific swap quote by its ID
func (c *DelegatedSwapsClient) GetSwapQuote(ctx context.Context, quoteID string) (*GetSwapQuoteResponse, error) {
	path := "/swaps/quotes/" + url.PathEscape(quoteID)
	var result GetSwapQuoteResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
