// Code generated by go-sdk-generator. DO NOT EDIT.

package swaps

import (
	"github.com/dfns/dfns-sdk-go/types"
)

// List Swaps
type ListSwapsResponse struct {
	Items []types.Swap `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListSwapsQuery represents query parameters.
type ListSwapsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Swap
type CreateSwapRequest struct {
	QuoteID string `json:"quoteId"`
	Reference *string `json:"reference,omitempty"`
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	SlippageBps float64 `json:"slippageBps"`
	SourceAsset interface{} `json:"sourceAsset"`
	TargetAsset interface{} `json:"targetAsset"`
}

// Create Swap
type CreateSwapResponse struct {
	ID string `json:"id"`
	QuoteID string `json:"quoteId"`
	Reference interface{} `json:"reference"`
	WalletID string `json:"walletId"`
	TargetWalletID string `json:"targetWalletId"`
	Status string `json:"status"`
	Provider string `json:"provider"`
	QuotedSourceAsset map[string]interface{} `json:"quotedSourceAsset"`
	QuotedTargetAsset map[string]interface{} `json:"quotedTargetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester map[string]interface{} `json:"requester"`
}

// Request Swap Quote
type RequestSwapQuoteRequest struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	SourceAsset interface{} `json:"sourceAsset"`
	TargetAsset interface{} `json:"targetAsset"`
	SlippageBps float64 `json:"slippageBps"`
}

// Request Swap Quote
type RequestSwapQuoteResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	Provider string `json:"provider"`
	SourceAsset map[string]interface{} `json:"sourceAsset"`
	TargetAsset map[string]interface{} `json:"targetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester map[string]interface{} `json:"requester"`
}

// Get Swap
type GetSwapResponse struct {
	ID string `json:"id"`
	QuoteID string `json:"quoteId"`
	Reference interface{} `json:"reference"`
	WalletID string `json:"walletId"`
	TargetWalletID string `json:"targetWalletId"`
	Status string `json:"status"`
	Provider string `json:"provider"`
	QuotedSourceAsset map[string]interface{} `json:"quotedSourceAsset"`
	QuotedTargetAsset map[string]interface{} `json:"quotedTargetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester map[string]interface{} `json:"requester"`
}

// Get Swap Quote
type GetSwapQuoteResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	Provider string `json:"provider"`
	SourceAsset map[string]interface{} `json:"sourceAsset"`
	TargetAsset map[string]interface{} `json:"targetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester map[string]interface{} `json:"requester"`
}
