// Code generated by go-sdk-generator. DO NOT EDIT.

package swaps

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// List Swaps
type ListSwapsResponse struct {
	Items []types.Swap `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListSwapsQuery represents query parameters.
type ListSwapsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateSwapRequest represents the request body for the createSwap operation.
type CreateSwapRequest = any

// Create Swap
type CreateSwapResponse struct {
	ID string `json:"id"`
	QuoteID string `json:"quoteId"`
	Reference interface{} `json:"reference"`
	WalletID string `json:"walletId"`
	TargetWalletID string `json:"targetWalletId"`
	Status string `json:"status"`
	Provider string `json:"provider"`
	QuotedSourceAsset map[string]interface{} `json:"quotedSourceAsset"`
	QuotedTargetAsset map[string]interface{} `json:"quotedTargetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester types.Requester `json:"requester"`
	FailureReason *string `json:"failureReason,omitempty"`
	ProtocolStatus *string `json:"protocolStatus,omitempty"`
}

// RequestSwapQuoteRequest represents the request body for the requestSwapQuote operation.
type RequestSwapQuoteRequest = any

// Request Swap Quote
type RequestSwapQuoteResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	Provider string `json:"provider"`
	SourceAsset map[string]interface{} `json:"sourceAsset"`
	TargetAsset map[string]interface{} `json:"targetAsset"`
	SlippageBps int64 `json:"slippageBps"`
	Fee *string `json:"fee,omitempty"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester types.Requester `json:"requester"`
}

// Get Swap
type GetSwapResponse struct {
	ID string `json:"id"`
	QuoteID string `json:"quoteId"`
	Reference interface{} `json:"reference"`
	WalletID string `json:"walletId"`
	TargetWalletID string `json:"targetWalletId"`
	Status string `json:"status"`
	Provider string `json:"provider"`
	QuotedSourceAsset map[string]interface{} `json:"quotedSourceAsset"`
	QuotedTargetAsset map[string]interface{} `json:"quotedTargetAsset"`
	SlippageBps float64 `json:"slippageBps"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester types.Requester `json:"requester"`
	FailureReason *string `json:"failureReason,omitempty"`
	ProtocolStatus *string `json:"protocolStatus,omitempty"`
}

// Get Swap Quote
type GetSwapQuoteResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	TargetWalletID *string `json:"targetWalletId,omitempty"`
	Provider string `json:"provider"`
	SourceAsset map[string]interface{} `json:"sourceAsset"`
	TargetAsset map[string]interface{} `json:"targetAsset"`
	SlippageBps int64 `json:"slippageBps"`
	Fee *string `json:"fee,omitempty"`
	DateCreated string `json:"dateCreated"`
	RequestBody interface{} `json:"requestBody"`
	Requester types.Requester `json:"requester"`
}
