// Code generated by go-sdk-generator. DO NOT EDIT.

package agreements

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// AgreementsClient provides methods for agreements operations.
type AgreementsClient struct {
	client *client.Client
}

// NewAgreementsClient creates a new AgreementsClient.
func NewAgreementsClient(c *client.Client) *AgreementsClient {
	return &AgreementsClient{client: c}
}

// Get the latest unaccepted agreement for a specific agreement type
func (c *AgreementsClient) GetLatestUnacceptedAgreement(ctx context.Context, query *GetLatestUnacceptedAgreementQuery) (*GetLatestUnacceptedAgreementResponse, error) {
	path := "/agreements/latest-unaccepted"
	if query != nil {
		q := url.Values{}
		q.Set("agreementType", fmt.Sprintf("%v", query.AgreementType))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetLatestUnacceptedAgreementResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Record the acceptance of a specific agreement by its ID
func (c *AgreementsClient) RecordAgreementAcceptance(ctx context.Context, agreementID string) (*RecordAgreementAcceptanceResponse, error) {
	path := "/agreements/" + url.PathEscape(agreementID) + "/accept"
	var result RecordAgreementAcceptanceResponse
	err := c.client.Do(ctx, "POST", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
