// Code generated by go-sdk-generator. DO NOT EDIT.

package agreements

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedAgreementsClient provides delegated user action signing for agreements operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedAgreementsClient struct {
	client *client.Client
}

// NewDelegatedAgreementsClient creates a new DelegatedAgreementsClient.
func NewDelegatedAgreementsClient(c *client.Client) *DelegatedAgreementsClient {
	return &DelegatedAgreementsClient{client: c}
}

// Get the latest unaccepted agreement for a specific agreement type
func (c *DelegatedAgreementsClient) GetLatestUnacceptedAgreement(ctx context.Context, query *GetLatestUnacceptedAgreementQuery) (*GetLatestUnacceptedAgreementResponse, error) {
	path := "/agreements/latest-unaccepted"
	if query != nil {
		q := url.Values{}
		q.Set("agreementType", fmt.Sprintf("%v", query.AgreementType))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetLatestUnacceptedAgreementResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RecordAgreementAcceptanceInit starts delegated user action signing for the recordAgreementAcceptance operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to RecordAgreementAcceptanceComplete
// along with the same arguments given here.
func (c *DelegatedAgreementsClient) RecordAgreementAcceptanceInit(ctx context.Context, agreementID string) (*signer.UserActionChallenge, error) {
	path := "/agreements/" + url.PathEscape(agreementID) + "/accept"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// RecordAgreementAcceptanceComplete finishes delegated signing for the recordAgreementAcceptance operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the RecordAgreementAcceptanceInit challenge.
func (c *DelegatedAgreementsClient) RecordAgreementAcceptanceComplete(ctx context.Context, agreementID string, challengeID string, assertion *signer.CredentialAssertion) (*RecordAgreementAcceptanceResponse, error) {
	path := "/agreements/" + url.PathEscape(agreementID) + "/accept"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result RecordAgreementAcceptanceResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
