// Code generated by go-sdk-generator. DO NOT EDIT.

package agreements

// Get Latest Unaccepted Agreement
type GetLatestUnacceptedAgreementResponse struct {
	LatestAgreement interface{} `json:"latestAgreement"`
}

// GetLatestUnacceptedAgreementQuery represents query parameters.
type GetLatestUnacceptedAgreementQuery struct {
	AgreementType string `json:"agreementType"`
}

// Record Agreement Acceptance
type RecordAgreementAcceptanceResponse struct {
	AgreementID string `json:"agreementId"`
	UserID string `json:"userId"`
	DateAccepted string `json:"dateAccepted"`
}
