// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// PayinsClient provides methods for payins operations.
type PayinsClient struct {
	client *client.Client
}

// NewPayinsClient creates a new PayinsClient.
func NewPayinsClient(c *client.Client) *PayinsClient {
	return &PayinsClient{client: c}
}

// Check whether a wallet's address is registered (and approved) as an payin recipient with the provider.
func (c *PayinsClient) GetPayinRecipient(ctx context.Context, query *GetPayinRecipientQuery) (*GetPayinRecipientResponse, error) {
	path := "/payins/recipients"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		q.Set("walletId", fmt.Sprintf("%v", query.WalletID))
		q.Set("currency", fmt.Sprintf("%v", query.Currency))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetPayinRecipientResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Register a wallet's address as an payin recipient with the provider. The registration then needs
//     to be approved on the provider's side (for Circle Mint: by an administrator in the Mint Console)
//     before payins to that wallet can be created.
func (c *PayinsClient) RegisterPayinRecipient(ctx context.Context, body RegisterPayinRecipientRequest) (*RegisterPayinRecipientResponse, error) {
	path := "/payins/recipients"
	var result RegisterPayinRecipientResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
