// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// PayinsClient provides methods for payins operations.
type PayinsClient struct {
	client *client.Client
}

// NewPayinsClient creates a new PayinsClient.
func NewPayinsClient(c *client.Client) *PayinsClient {
	return &PayinsClient{client: c}
}

// List payins with optional filtering and pagination.
func (c *PayinsClient) ListPayins(ctx context.Context, query *ListPayinsQuery) (*ListPayinsResponse, error) {
	path := "/payins"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.WalletID != nil {
			q.Set("walletId", fmt.Sprintf("%v", *query.WalletID))
		}
		if len(query.Status) > 0 {
			q.Set("status", fmt.Sprintf("%v", query.Status))
		}
		if len(query.Provider) > 0 {
			q.Set("provider", fmt.Sprintf("%v", query.Provider))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayinsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deliver stablecoin from the organisation's provider balance to a wallet on-chain.
func (c *PayinsClient) CreatePayin(ctx context.Context, body CreatePayinRequest) (interface{}, error) {
	path := "/payins"
	var result interface{}
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Check whether a wallet's address is registered (and approved) as an payin recipient with the provider.
func (c *PayinsClient) GetPayinRecipient(ctx context.Context, query *GetPayinRecipientQuery) (*GetPayinRecipientResponse, error) {
	path := "/payins/recipients"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		q.Set("walletId", fmt.Sprintf("%v", query.WalletID))
		q.Set("currency", fmt.Sprintf("%v", query.Currency))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetPayinRecipientResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Register a wallet's address as an payin recipient with the provider. The registration then needs
//     to be approved on the provider's side (for Circle Mint: by an administrator in the Mint Console)
//     before payins to that wallet can be created.
func (c *PayinsClient) RegisterPayinRecipient(ctx context.Context, body RegisterPayinRecipientRequest) (*RegisterPayinRecipientResponse, error) {
	path := "/payins/recipients"
	var result RegisterPayinRecipientResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the current status of an payin by its ID.
func (c *PayinsClient) GetPayinStatus(ctx context.Context, payinID string) (interface{}, error) {
	path := "/payins/" + url.PathEscape(payinID)
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// The organisation's available balance at the payin provider, one entry per currency —
//     the funds payins can deliver on-chain.
func (c *PayinsClient) ListPayinBalances(ctx context.Context, query *ListPayinBalancesQuery) (*ListPayinBalancesResponse, error) {
	path := "/payins/balances"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayinBalancesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
