// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedPayinsClient provides delegated user action signing for payins operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedPayinsClient struct {
	client *client.Client
}

// NewDelegatedPayinsClient creates a new DelegatedPayinsClient.
func NewDelegatedPayinsClient(c *client.Client) *DelegatedPayinsClient {
	return &DelegatedPayinsClient{client: c}
}

// List payins with optional filtering and pagination.
func (c *DelegatedPayinsClient) ListPayins(ctx context.Context, query *ListPayinsQuery) (*ListPayinsResponse, error) {
	path := "/payins"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.WalletID != nil {
			q.Set("walletId", fmt.Sprintf("%v", *query.WalletID))
		}
		if len(query.Status) > 0 {
			q.Set("status", fmt.Sprintf("%v", query.Status))
		}
		if len(query.Provider) > 0 {
			q.Set("provider", fmt.Sprintf("%v", query.Provider))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayinsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePayinInit starts delegated user action signing for the createPayin operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePayinComplete
// along with the same arguments given here.
func (c *DelegatedPayinsClient) CreatePayinInit(ctx context.Context, body CreatePayinRequest) (*signer.UserActionChallenge, error) {
	path := "/payins"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePayinComplete finishes delegated signing for the createPayin operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePayinInit challenge.
func (c *DelegatedPayinsClient) CreatePayinComplete(ctx context.Context, body CreatePayinRequest, challengeID string, assertion *signer.CredentialAssertion) (interface{}, error) {
	path := "/payins"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return result, nil
}

// Check whether a wallet's address is registered (and approved) as an payin recipient with the provider.
func (c *DelegatedPayinsClient) GetPayinRecipient(ctx context.Context, query *GetPayinRecipientQuery) (*GetPayinRecipientResponse, error) {
	path := "/payins/recipients"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		q.Set("walletId", fmt.Sprintf("%v", query.WalletID))
		q.Set("currency", fmt.Sprintf("%v", query.Currency))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetPayinRecipientResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RegisterPayinRecipientInit starts delegated user action signing for the registerPayinRecipient operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to RegisterPayinRecipientComplete
// along with the same arguments given here.
func (c *DelegatedPayinsClient) RegisterPayinRecipientInit(ctx context.Context, body RegisterPayinRecipientRequest) (*signer.UserActionChallenge, error) {
	path := "/payins/recipients"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// RegisterPayinRecipientComplete finishes delegated signing for the registerPayinRecipient operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the RegisterPayinRecipientInit challenge.
func (c *DelegatedPayinsClient) RegisterPayinRecipientComplete(ctx context.Context, body RegisterPayinRecipientRequest, challengeID string, assertion *signer.CredentialAssertion) (*RegisterPayinRecipientResponse, error) {
	path := "/payins/recipients"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result RegisterPayinRecipientResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the current status of an payin by its ID.
func (c *DelegatedPayinsClient) GetPayinStatus(ctx context.Context, payinID string) (interface{}, error) {
	path := "/payins/" + url.PathEscape(payinID)
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// The organisation's available balance at the payin provider, one entry per currency —
//     the funds payins can deliver on-chain.
func (c *DelegatedPayinsClient) ListPayinBalances(ctx context.Context, query *ListPayinBalancesQuery) (*ListPayinBalancesResponse, error) {
	path := "/payins/balances"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPayinBalancesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
