// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedPayinsClient provides delegated user action signing for payins operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedPayinsClient struct {
	client *client.Client
}

// NewDelegatedPayinsClient creates a new DelegatedPayinsClient.
func NewDelegatedPayinsClient(c *client.Client) *DelegatedPayinsClient {
	return &DelegatedPayinsClient{client: c}
}

// Check whether a wallet's address is registered (and approved) as an payin recipient with the provider.
func (c *DelegatedPayinsClient) GetPayinRecipient(ctx context.Context, query *GetPayinRecipientQuery) (*GetPayinRecipientResponse, error) {
	path := "/payins/recipients"
	if query != nil {
		q := url.Values{}
		q.Set("provider", fmt.Sprintf("%v", query.Provider))
		q.Set("walletId", fmt.Sprintf("%v", query.WalletID))
		q.Set("currency", fmt.Sprintf("%v", query.Currency))
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetPayinRecipientResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RegisterPayinRecipientInit starts delegated user action signing for the registerPayinRecipient operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to RegisterPayinRecipientComplete
// along with the same arguments given here.
func (c *DelegatedPayinsClient) RegisterPayinRecipientInit(ctx context.Context, body RegisterPayinRecipientRequest) (*signer.UserActionChallenge, error) {
	path := "/payins/recipients"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// RegisterPayinRecipientComplete finishes delegated signing for the registerPayinRecipient operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the RegisterPayinRecipientInit challenge.
func (c *DelegatedPayinsClient) RegisterPayinRecipientComplete(ctx context.Context, body RegisterPayinRecipientRequest, challengeID string, assertion *signer.CredentialAssertion) (*RegisterPayinRecipientResponse, error) {
	path := "/payins/recipients"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result RegisterPayinRecipientResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
