// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

// Get Payin Recipient
type GetPayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}

// GetPayinRecipientQuery represents query parameters.
type GetPayinRecipientQuery struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
}

// RegisterPayinRecipientRequest represents the request body for the registerPayinRecipient operation.
type RegisterPayinRecipientRequest = any

// Register Payin Recipient
type RegisterPayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}
