// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// List Payins
type ListPayinsResponse struct {
	Items []interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListPayinsQuery represents query parameters.
type ListPayinsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	WalletID *string `json:"walletId,omitempty"`
	Status []string `json:"status,omitempty"`
	Provider []string `json:"provider,omitempty"`
}

// CreatePayinRequest represents the request body for the createPayin operation.
type CreatePayinRequest = any

// CreatePayinQuoteRequest represents the request body for the createPayinQuote operation.
type CreatePayinQuoteRequest = any

// Request Payin Quote
type CreatePayinQuoteResponse struct {
	Provider string `json:"provider"`
	Currency string `json:"currency"`
	Network types.Network `json:"network"`
	Tid string `json:"tid"`
	Timestamp string `json:"timestamp"`
	Quotes []map[string]interface{} `json:"quotes"`
}

// Deprecated: use CreatePayinQuoteRequest instead.
type RequestPayinQuoteRequest = CreatePayinQuoteRequest

// Deprecated: use CreatePayinQuoteResponse instead.
type RequestPayinQuoteResponse = CreatePayinQuoteResponse

// Get Payin Recipient
type GetPayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}

// GetPayinRecipientQuery represents query parameters.
type GetPayinRecipientQuery struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
}

// CreatePayinRecipientRequest represents the request body for the createPayinRecipient operation.
type CreatePayinRecipientRequest = any

// Register Payin Recipient
type CreatePayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}

// Deprecated: use CreatePayinRecipientRequest instead.
type RegisterPayinRecipientRequest = CreatePayinRecipientRequest

// Deprecated: use CreatePayinRecipientResponse instead.
type RegisterPayinRecipientResponse = CreatePayinRecipientResponse

// List Payin Accounts
type ListPayinAccountsResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// ListPayinAccountsQuery represents query parameters.
type ListPayinAccountsQuery struct {
	Provider string `json:"provider"`
}

// List Payin Balances
type ListPayinBalancesResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// ListPayinBalancesQuery represents query parameters.
type ListPayinBalancesQuery struct {
	Provider string `json:"provider"`
}

// List Payin Options
type ListPayinOptionsResponse struct {
	Assets []string `json:"assets"`
	Currencies []map[string]interface{} `json:"currencies"`
}

// ListPayinOptionsQuery represents query parameters.
type ListPayinOptionsQuery struct {
	Provider string `json:"provider"`
}

// RegisterPayinAccountAssetRequest represents the request body for the registerPayinAccountAsset operation.
type RegisterPayinAccountAssetRequest = any

// Register Payin Account Asset
type RegisterPayinAccountAssetResponse struct {
	AccountID string `json:"accountId"`
	Name *string `json:"name,omitempty"`
	Assets []map[string]interface{} `json:"assets"`
}
