// Code generated by go-sdk-generator. DO NOT EDIT.

package payins

// List Payins
type ListPayinsResponse struct {
	Items []interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListPayinsQuery represents query parameters.
type ListPayinsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	WalletID *string `json:"walletId,omitempty"`
	Status []string `json:"status,omitempty"`
	Provider []string `json:"provider,omitempty"`
}

// CreatePayinRequest represents the request body for the createPayin operation.
type CreatePayinRequest = any

// Get Payin Recipient
type GetPayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}

// GetPayinRecipientQuery represents query parameters.
type GetPayinRecipientQuery struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
}

// RegisterPayinRecipientRequest represents the request body for the registerPayinRecipient operation.
type RegisterPayinRecipientRequest = any

// Register Payin Recipient
type RegisterPayinRecipientResponse struct {
	Provider string `json:"provider"`
	WalletID string `json:"walletId"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	RecipientAddressID *string `json:"recipientAddressId,omitempty"`
}

// List Payin Balances
type ListPayinBalancesResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// ListPayinBalancesQuery represents query parameters.
type ListPayinBalancesQuery struct {
	Provider string `json:"provider"`
}
