// Code generated by go-sdk-generator. DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// Options contains configuration for the Dfns client.
type Options struct {
	// BaseURL is the Dfns API base URL (default: https://api.dfns.io)
	BaseURL string

	// AuthToken is the bearer token for authentication
	AuthToken string

	// Signer is used for signing user actions (required for write operations)
	Signer signer.Signer

	// HTTPClient is an optional custom HTTP client
	HTTPClient *http.Client
}

// Client is the base HTTP client for Dfns API.
type Client struct {
	opts       Options
	httpClient *http.Client
}

// New creates a new base client.
func New(opts Options) (*Client, error) {
	if opts.BaseURL == "" {
		opts.BaseURL = "https://api.dfns.io"
	}

	// Validate BaseURL scheme to prevent SSRF
	parsedURL, err := url.Parse(opts.BaseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid BaseURL: %w", err)
	}
	if parsedURL.Scheme != "https" {
		return nil, errors.New("BaseURL must use https scheme")
	}

	if opts.AuthToken == "" {
		return nil, errors.New("AuthToken is required")
	}

	httpClient := opts.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{
			Timeout: 30 * time.Second,
		}
	}

	return &Client{
		opts:       opts,
		httpClient: httpClient,
	}, nil
}

// Do performs an HTTP request to the Dfns API.
func (c *Client) Do(ctx context.Context, method, path string, body interface{}, result interface{}, requiresSignature bool) error {
	url := c.opts.BaseURL + path

	var bodyReader io.Reader
	var bodyBytes []byte
	if body != nil {
		var err error
		bodyBytes, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = bytes.NewReader(bodyBytes)
	}

	req, err := http.NewRequestWithContext(ctx, method, url, bodyReader)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.opts.AuthToken)

	// Handle user action signing if required
	if requiresSignature {
		if c.opts.Signer == nil {
			return errors.New("signer is required for this operation but not configured")
		}
		userActionToken, err := c.getUserActionToken(ctx, method, path, bodyBytes)
		if err != nil {
			return fmt.Errorf("failed to get user action token: %w", err)
		}
		req.Header.Set("X-DFNS-USERACTION", userActionToken)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 10<<20))
	if err != nil {
		return fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return &APIError{
			StatusCode: resp.StatusCode,
			Body:       string(respBody),
		}
	}

	if result != nil && len(respBody) > 0 {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// MultipartFile is a binary file uploaded as the "file" part of a multipart/form-data request.
type MultipartFile struct {
	// Bytes is the raw file content.
	Bytes []byte

	// Name is the file name sent in the multipart part (defaults to "upload.bin").
	Name string
}

// DoMultipart performs a multipart/form-data upload. The JSON body is sent as the
// "data" part (with the file's "fileChecksum" injected, matching the API contract),
// and the bytes are sent as the "file" part. When a signature is required, the "data"
// payload is what gets signed.
func (c *Client) DoMultipart(ctx context.Context, method, path string, body interface{}, file MultipartFile, result interface{}, requiresSignature bool) error {
	url := c.opts.BaseURL + path

	// Build the "data" object: the JSON body plus the file checksum the API expects.
	data := map[string]interface{}{}
	if body != nil {
		bodyBytes, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		if err := json.Unmarshal(bodyBytes, &data); err != nil {
			return fmt.Errorf("failed to build multipart data: %w", err)
		}
	}
	checksum := sha256.Sum256(file.Bytes)
	data["fileChecksum"] = hex.EncodeToString(checksum[:])

	dataBytes, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("failed to marshal multipart data: %w", err)
	}

	// Strip CR/LF from the caller-supplied name to prevent multipart header injection.
	fileName := strings.ReplaceAll(strings.ReplaceAll(file.Name, "\r", ""), "\n", "")
	if fileName == "" {
		fileName = "upload.bin"
	}

	// Stream the multipart body through an io.Pipe instead of buffering the whole
	// payload (data + file) in a bytes.Buffer. The file content is already in memory
	// because we must hash it for the signed "fileChecksum" above, so this avoids a
	// second full-size copy and keeps peak memory flat for large uploads.
	pr, pw := io.Pipe()
	writer := multipart.NewWriter(pw)
	// Always close the read end when we return. A compliant http.Transport already
	// closes the request body, but a custom Options.HTTPClient that errors without
	// reading/closing it would otherwise strand the writer goroutine on a pipe write.
	// Closing pr makes any pending write return ErrClosedPipe so the goroutine exits.
	defer pr.Close()

	req, err := http.NewRequestWithContext(ctx, method, url, pr)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("Authorization", "Bearer "+c.opts.AuthToken)

	// User action signing covers the "data" payload (matching the JSON body path).
	if requiresSignature {
		if c.opts.Signer == nil {
			return errors.New("signer is required for this operation but not configured")
		}
		userActionToken, err := c.getUserActionToken(ctx, method, path, dataBytes)
		if err != nil {
			return fmt.Errorf("failed to get user action token: %w", err)
		}
		req.Header.Set("X-DFNS-USERACTION", userActionToken)
	}

	// Write the multipart body in the background; httpClient.Do reads it from the pipe.
	// Launched only here, after the early returns above, so a bail-out can't leak a
	// goroutine blocked on the unbuffered pipe. The deferred pr.Close() above guarantees
	// this goroutine is unblocked when DoMultipart returns, even if a custom transport
	// neither drains nor closes the request body.
	go func() {
		// Surface any encoding error to the HTTP client via the pipe reader.
		// CloseWithError(nil) behaves like Close(), so the success path needs no branch.
		pw.CloseWithError(writeMultipartBody(writer, dataBytes, fileName, file.Bytes))
	}()

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 10<<20))
	if err != nil {
		return fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return &APIError{
			StatusCode: resp.StatusCode,
			Body:       string(respBody),
		}
	}

	if result != nil && len(respBody) > 0 {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// writeMultipartBody writes the "data" and "file" parts to w and finalizes it.
// It is split out of DoMultipart so each error path can be unit-tested with a
// failing io.Writer, instead of racing the io.Pipe in the streaming goroutine.
func writeMultipartBody(w *multipart.Writer, dataBytes []byte, fileName string, fileBytes []byte) error {
	if err := w.WriteField("data", string(dataBytes)); err != nil {
		return fmt.Errorf("failed to write data part: %w", err)
	}
	part, err := w.CreateFormFile("file", fileName)
	if err != nil {
		return fmt.Errorf("failed to create file part: %w", err)
	}
	if _, err := part.Write(fileBytes); err != nil {
		return fmt.Errorf("failed to write file part: %w", err)
	}
	if err := w.Close(); err != nil {
		return fmt.Errorf("failed to finalize multipart body: %w", err)
	}
	return nil
}

// getUserActionToken obtains a user action token by signing a challenge.
func (c *Client) getUserActionToken(ctx context.Context, method, path string, body []byte) (string, error) {
	// Step 1: Create challenge
	challenge, err := c.createUserActionChallenge(ctx, method, path, body)
	if err != nil {
		return "", fmt.Errorf("failed to create challenge: %w", err)
	}

	// Step 2: Sign challenge using the configured signer
	assertion, err := c.opts.Signer.Sign(challenge)
	if err != nil {
		return "", fmt.Errorf("failed to sign challenge: %w", err)
	}

	// Step 3: Complete signing to get user action token
	return c.completeUserActionSigning(ctx, challenge.ChallengeIdentifier, assertion)
}

func (c *Client) createUserActionChallenge(ctx context.Context, method, path string, body []byte) (*signer.UserActionChallenge, error) {
	reqBody := map[string]string{
		"userActionPayload":    string(body),
		"userActionHttpMethod": method,
		"userActionHttpPath":   path,
		"userActionServerKind": "Api",
	}

	var resp signer.UserActionChallenge
	err := c.Do(ctx, "POST", "/auth/action/init", reqBody, &resp, false)
	if err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *Client) completeUserActionSigning(ctx context.Context, challengeID string, assertion *signer.CredentialAssertion) (string, error) {
	reqBody := map[string]interface{}{
		"challengeIdentifier": challengeID,
		"firstFactor":         assertion,
	}

	var resp struct {
		UserAction string `json:"userAction"`
	}
	err := c.Do(ctx, "POST", "/auth/action", reqBody, &resp, false)
	if err != nil {
		return "", err
	}

	return resp.UserAction, nil
}

// APIError represents an error response from the Dfns API.
type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("API error (status %d): %s", e.StatusCode, e.Body)
}
