// Code generated by go-sdk-generator. DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/dfns/dfns-sdk-go/signer"
)

// Options contains configuration for the Dfns client.
type Options struct {
	// BaseURL is the Dfns API base URL (default: https://api.dfns.io)
	BaseURL string

	// AuthToken is the bearer token for authentication
	AuthToken string

	// Signer is used for signing user actions (required for write operations)
	Signer signer.Signer

	// HTTPClient is an optional custom HTTP client
	HTTPClient *http.Client
}

// Client is the base HTTP client for Dfns API.
type Client struct {
	opts       Options
	httpClient *http.Client
}

// New creates a new base client.
func New(opts Options) (*Client, error) {
	if opts.BaseURL == "" {
		opts.BaseURL = "https://api.dfns.io"
	}

	// Validate BaseURL scheme to prevent SSRF
	parsedURL, err := url.Parse(opts.BaseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid BaseURL: %w", err)
	}
	if parsedURL.Scheme != "https" {
		return nil, errors.New("BaseURL must use https scheme")
	}

	if opts.AuthToken == "" {
		return nil, errors.New("AuthToken is required")
	}

	httpClient := opts.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{
			Timeout: 30 * time.Second,
		}
	}

	return &Client{
		opts:       opts,
		httpClient: httpClient,
	}, nil
}

// Do performs an HTTP request to the Dfns API.
func (c *Client) Do(ctx context.Context, method, path string, body interface{}, result interface{}, requiresSignature bool) error {
	url := c.opts.BaseURL + path

	var bodyReader io.Reader
	var bodyBytes []byte
	if body != nil {
		var err error
		bodyBytes, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = bytes.NewReader(bodyBytes)
	}

	req, err := http.NewRequestWithContext(ctx, method, url, bodyReader)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.opts.AuthToken)

	// Handle user action signing if required
	if requiresSignature {
		if c.opts.Signer == nil {
			return errors.New("signer is required for this operation but not configured")
		}
		userActionToken, err := c.getUserActionToken(ctx, method, path, bodyBytes)
		if err != nil {
			return fmt.Errorf("failed to get user action token: %w", err)
		}
		req.Header.Set("X-DFNS-USERACTION", userActionToken)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 10<<20))
	if err != nil {
		return fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return &APIError{
			StatusCode: resp.StatusCode,
			Body:       string(respBody),
		}
	}

	if result != nil && len(respBody) > 0 {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// getUserActionToken obtains a user action token by signing a challenge.
func (c *Client) getUserActionToken(ctx context.Context, method, path string, body []byte) (string, error) {
	// Step 1: Create challenge
	challenge, err := c.createUserActionChallenge(ctx, method, path, body)
	if err != nil {
		return "", fmt.Errorf("failed to create challenge: %w", err)
	}

	// Step 2: Sign challenge using the configured signer
	assertion, err := c.opts.Signer.Sign(challenge)
	if err != nil {
		return "", fmt.Errorf("failed to sign challenge: %w", err)
	}

	// Step 3: Complete signing to get user action token
	return c.completeUserActionSigning(ctx, challenge.ChallengeIdentifier, assertion)
}

func (c *Client) createUserActionChallenge(ctx context.Context, method, path string, body []byte) (*signer.UserActionChallenge, error) {
	reqBody := map[string]string{
		"userActionPayload":    string(body),
		"userActionHttpMethod": method,
		"userActionHttpPath":   path,
		"userActionServerKind": "Api",
	}

	var resp signer.UserActionChallenge
	err := c.Do(ctx, "POST", "/auth/action/init", reqBody, &resp, false)
	if err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *Client) completeUserActionSigning(ctx context.Context, challengeID string, assertion *signer.CredentialAssertion) (string, error) {
	reqBody := map[string]interface{}{
		"challengeIdentifier": challengeID,
		"firstFactor":         assertion,
	}

	var resp struct {
		UserAction string `json:"userAction"`
	}
	err := c.Do(ctx, "POST", "/auth/action", reqBody, &resp, false)
	if err != nil {
		return "", err
	}

	return resp.UserAction, nil
}

// APIError represents an error response from the Dfns API.
type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("API error (status %d): %s", e.StatusCode, e.Body)
}
