// Code generated by go-sdk-generator. DO NOT EDIT.

package exchanges

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// ExchangesClient provides methods for exchanges operations.
type ExchangesClient struct {
	client *client.Client
}

// NewExchangesClient creates a new ExchangesClient.
func NewExchangesClient(c *client.Client) *ExchangesClient {
	return &ExchangesClient{client: c}
}

// Retrieve the details of a specific exchange integration configuration.
func (c *ExchangesClient) GetExchange(ctx context.Context, exchangeID string) (*GetExchangeResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID)
	var result GetExchangeResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete the exchange configuration from your organization.
func (c *ExchangesClient) DeleteExchange(ctx context.Context, exchangeID string) (*DeleteExchangeResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID)
	var result DeleteExchangeResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// List all configured exchange integrations.
func (c *ExchangesClient) ListExchanges(ctx context.Context, query *ListExchangesQuery) (*ListExchangesResponse, error) {
	path := "/exchanges"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListExchangesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Link your organization with a cryptocurrency exchange.
func (c *ExchangesClient) CreateExchange(ctx context.Context, body CreateExchangeRequest) (*CreateExchangeResponse, error) {
	path := "/exchanges"
	var result CreateExchangeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get a list of accounts for a specific exchange.
func (c *ExchangesClient) ListAccounts(ctx context.Context, exchangeID string, query *ListAccountsQuery) (*ListAccountsResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAccountsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of assets for a specific account on a specific exchange.
func (c *ExchangesClient) ListAccountAssets(ctx context.Context, exchangeID string, accountID string, query *ListAccountAssetsQuery) (*ListAccountAssetsResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAccountAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListAssetWithdrawalNetworks list asset withdrawal networks.
func (c *ExchangesClient) ListAssetWithdrawalNetworks(ctx context.Context, exchangeID string, accountID string, asset string) (interface{}, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/assets/" + url.PathEscape(asset) + "/withdrawal-networks"
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// Creates a new exchange deposit transaction.
func (c *ExchangesClient) CreateExchangeDeposit(ctx context.Context, exchangeID string, accountID string, body CreateExchangeDepositRequest) (*CreateExchangeDepositResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/deposits"
	var result CreateExchangeDepositResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Creates a new exchange withdrawal transaction.
func (c *ExchangesClient) CreateExchangeWithdrawal(ctx context.Context, exchangeID string, accountID string, body CreateExchangeWithdrawalRequest) (*CreateExchangeWithdrawalResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/withdrawals"
	var result CreateExchangeWithdrawalResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
