// Code generated by go-sdk-generator. DO NOT EDIT.

package exchanges

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedExchangesClient provides delegated user action signing for exchanges operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedExchangesClient struct {
	client *client.Client
}

// NewDelegatedExchangesClient creates a new DelegatedExchangesClient.
func NewDelegatedExchangesClient(c *client.Client) *DelegatedExchangesClient {
	return &DelegatedExchangesClient{client: c}
}

// Retrieve the details of a specific exchange integration configuration.
func (c *DelegatedExchangesClient) GetExchange(ctx context.Context, exchangeID string) (*GetExchangeResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID)
	var result GetExchangeResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteExchangeInit starts delegated user action signing for the deleteExchange operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteExchangeComplete
// along with the same arguments given here.
func (c *DelegatedExchangesClient) DeleteExchangeInit(ctx context.Context, exchangeID string) (*signer.UserActionChallenge, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteExchangeComplete finishes delegated signing for the deleteExchange operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteExchangeInit challenge.
func (c *DelegatedExchangesClient) DeleteExchangeComplete(ctx context.Context, exchangeID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteExchangeResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteExchangeResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// List all configured exchange integrations.
func (c *DelegatedExchangesClient) ListExchanges(ctx context.Context, query *ListExchangesQuery) (*ListExchangesResponse, error) {
	path := "/exchanges"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListExchangesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateExchangeInit starts delegated user action signing for the createExchange operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateExchangeComplete
// along with the same arguments given here.
func (c *DelegatedExchangesClient) CreateExchangeInit(ctx context.Context, body CreateExchangeRequest) (*signer.UserActionChallenge, error) {
	path := "/exchanges"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateExchangeComplete finishes delegated signing for the createExchange operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateExchangeInit challenge.
func (c *DelegatedExchangesClient) CreateExchangeComplete(ctx context.Context, body CreateExchangeRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateExchangeResponse, error) {
	path := "/exchanges"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateExchangeResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get a list of accounts for a specific exchange.
func (c *DelegatedExchangesClient) ListAccounts(ctx context.Context, exchangeID string, query *ListAccountsQuery) (*ListAccountsResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAccountsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of assets for a specific account on a specific exchange.
func (c *DelegatedExchangesClient) ListAccountAssets(ctx context.Context, exchangeID string, accountID string, query *ListAccountAssetsQuery) (*ListAccountAssetsResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAccountAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists the networks to which the given asset can be withdrawn from an exchange account.
func (c *DelegatedExchangesClient) ListAssetWithdrawalNetworks(ctx context.Context, exchangeID string, accountID string, asset string) (interface{}, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/assets/" + url.PathEscape(asset) + "/withdrawal-networks"
	var result interface{}
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// CreateExchangeDepositInit starts delegated user action signing for the createExchangeDeposit operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateExchangeDepositComplete
// along with the same arguments given here.
func (c *DelegatedExchangesClient) CreateExchangeDepositInit(ctx context.Context, exchangeID string, accountID string, body CreateExchangeDepositRequest) (*signer.UserActionChallenge, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/deposits"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateExchangeDepositComplete finishes delegated signing for the createExchangeDeposit operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateExchangeDepositInit challenge.
func (c *DelegatedExchangesClient) CreateExchangeDepositComplete(ctx context.Context, exchangeID string, accountID string, body CreateExchangeDepositRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateExchangeDepositResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/deposits"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateExchangeDepositResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateExchangeWithdrawalInit starts delegated user action signing for the createExchangeWithdrawal operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateExchangeWithdrawalComplete
// along with the same arguments given here.
func (c *DelegatedExchangesClient) CreateExchangeWithdrawalInit(ctx context.Context, exchangeID string, accountID string, body CreateExchangeWithdrawalRequest) (*signer.UserActionChallenge, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/withdrawals"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateExchangeWithdrawalComplete finishes delegated signing for the createExchangeWithdrawal operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateExchangeWithdrawalInit challenge.
func (c *DelegatedExchangesClient) CreateExchangeWithdrawalComplete(ctx context.Context, exchangeID string, accountID string, body CreateExchangeWithdrawalRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateExchangeWithdrawalResponse, error) {
	path := "/exchanges/" + url.PathEscape(exchangeID) + "/accounts/" + url.PathEscape(accountID) + "/withdrawals"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateExchangeWithdrawalResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
