// Code generated by go-sdk-generator. DO NOT EDIT.

package exchanges

// Get Exchange
type GetExchangeResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
}

// Delete Exchange
type DeleteExchangeResponse struct {
	Deleted string `json:"deleted"`
}

// List Exchanges
type ListExchangesResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListExchangesQuery represents query parameters.
type ListExchangesQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Exchange
type CreateExchangeRequest struct {
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	ReadConfiguration map[string]interface{} `json:"readConfiguration"`
	WriteConfiguration map[string]interface{} `json:"writeConfiguration"`
}

// Create Exchange
type CreateExchangeResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	Kind string `json:"kind"`
	DateCreated string `json:"dateCreated"`
}

// List Accounts
type ListAccountsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAccountsQuery represents query parameters.
type ListAccountsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// List Account Assets
type ListAccountAssetsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAccountAssetsQuery represents query parameters.
type ListAccountAssetsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateExchangeDepositRequest represents the request body for the createExchangeDeposit operation.
type CreateExchangeDepositRequest = any

// Create Exchange Deposit
type CreateExchangeDepositResponse struct {
	ID string `json:"id"`
	ExchangeID string `json:"exchangeId"`
	AccountID string `json:"accountId"`
	TransferID *string `json:"transferId,omitempty"`
	ExchangeReference *string `json:"exchangeReference,omitempty"`
	Kind string `json:"kind"`
	WalletID string `json:"walletId"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	DateCreated string `json:"dateCreated"`
}

// CreateExchangeWithdrawalRequest represents the request body for the createExchangeWithdrawal operation.
type CreateExchangeWithdrawalRequest = any

// Create Exchange Withdrawal
type CreateExchangeWithdrawalResponse struct {
	ID string `json:"id"`
	ExchangeID string `json:"exchangeId"`
	AccountID string `json:"accountId"`
	TransferID *string `json:"transferId,omitempty"`
	ExchangeReference *string `json:"exchangeReference,omitempty"`
	Kind string `json:"kind"`
	WalletID string `json:"walletId"`
	Requester map[string]interface{} `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	DateCreated string `json:"dateCreated"`
}
