// Code generated by go-sdk-generator. DO NOT EDIT.

package feesponsors

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// FeeSponsorsClient provides methods for fee_sponsors operations.
type FeeSponsorsClient struct {
	client *client.Client
}

// NewFeeSponsorsClient creates a new FeeSponsorsClient.
func NewFeeSponsorsClient(c *client.Client) *FeeSponsorsClient {
	return &FeeSponsorsClient{client: c}
}

// Retrieves all Fee Sponsors configured in your organization.
func (c *FeeSponsorsClient) ListFeeSponsors(ctx context.Context, query *ListFeeSponsorsQuery) (*ListFeeSponsorsResponse, error) {
	path := "/fee-sponsors"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListFeeSponsorsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Creates a new `FeeSponsor` associated with a sponsor wallet. Returns a new fee sponsor entity with the `id` to be used when making a transfer.
func (c *FeeSponsorsClient) CreateFeeSponsor(ctx context.Context, body CreateFeeSponsorRequest) (*CreateFeeSponsorResponse, error) {
	path := "/fee-sponsors"
	var result CreateFeeSponsorResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a Fee Sponsor information by ID.
func (c *FeeSponsorsClient) GetFeeSponsor(ctx context.Context, feeSponsorID string) (*GetFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID)
	var result GetFeeSponsorResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete a Fee Sponsor. This action is irreversible. The fee sponsor won't be able to be used anymore when making a transfer.
func (c *FeeSponsorsClient) DeleteFeeSponsor(ctx context.Context, feeSponsorID string) (*DeleteFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID)
	var result DeleteFeeSponsorResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deactivate a Fee Sponsor: The fee sponsor won't be able to be used anymore when making a transfer.
func (c *FeeSponsorsClient) DeactivateFeeSponsor(ctx context.Context, feeSponsorID string) (*DeactivateFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/deactivate"
	var result DeactivateFeeSponsorResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Activate a Fee Sponsor: The fee sponsor can be used when making a transfer.
func (c *FeeSponsorsClient) ActivateFeeSponsor(ctx context.Context, feeSponsorID string) (*ActivateFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/activate"
	var result ActivateFeeSponsorResponse
	err := c.client.Do(ctx, "PUT", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves all fees paid by the specific Fee Sponsor.
func (c *FeeSponsorsClient) ListSponsoredFees(ctx context.Context, feeSponsorID string, query *ListSponsoredFeesQuery) (*ListSponsoredFeesResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/fees"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListSponsoredFeesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
