// Code generated by go-sdk-generator. DO NOT EDIT.

package feesponsors

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedFeeSponsorsClient provides delegated user action signing for fee_sponsors operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedFeeSponsorsClient struct {
	client *client.Client
}

// NewDelegatedFeeSponsorsClient creates a new DelegatedFeeSponsorsClient.
func NewDelegatedFeeSponsorsClient(c *client.Client) *DelegatedFeeSponsorsClient {
	return &DelegatedFeeSponsorsClient{client: c}
}

// Retrieves all Fee Sponsors configured in your organization.
func (c *DelegatedFeeSponsorsClient) ListFeeSponsors(ctx context.Context, query *ListFeeSponsorsQuery) (*ListFeeSponsorsResponse, error) {
	path := "/fee-sponsors"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListFeeSponsorsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateFeeSponsorInit starts delegated user action signing for the createFeeSponsor operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateFeeSponsorComplete
// along with the same arguments given here.
func (c *DelegatedFeeSponsorsClient) CreateFeeSponsorInit(ctx context.Context, body CreateFeeSponsorRequest) (*signer.UserActionChallenge, error) {
	path := "/fee-sponsors"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateFeeSponsorComplete finishes delegated signing for the createFeeSponsor operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateFeeSponsorInit challenge.
func (c *DelegatedFeeSponsorsClient) CreateFeeSponsorComplete(ctx context.Context, body CreateFeeSponsorRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateFeeSponsorResponse, error) {
	path := "/fee-sponsors"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateFeeSponsorResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a Fee Sponsor information by ID.
func (c *DelegatedFeeSponsorsClient) GetFeeSponsor(ctx context.Context, feeSponsorID string) (*GetFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID)
	var result GetFeeSponsorResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteFeeSponsorInit starts delegated user action signing for the deleteFeeSponsor operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteFeeSponsorComplete
// along with the same arguments given here.
func (c *DelegatedFeeSponsorsClient) DeleteFeeSponsorInit(ctx context.Context, feeSponsorID string) (*signer.UserActionChallenge, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteFeeSponsorComplete finishes delegated signing for the deleteFeeSponsor operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteFeeSponsorInit challenge.
func (c *DelegatedFeeSponsorsClient) DeleteFeeSponsorComplete(ctx context.Context, feeSponsorID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteFeeSponsorResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeactivateFeeSponsorInit starts delegated user action signing for the deactivateFeeSponsor operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeactivateFeeSponsorComplete
// along with the same arguments given here.
func (c *DelegatedFeeSponsorsClient) DeactivateFeeSponsorInit(ctx context.Context, feeSponsorID string) (*signer.UserActionChallenge, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/deactivate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// DeactivateFeeSponsorComplete finishes delegated signing for the deactivateFeeSponsor operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeactivateFeeSponsorInit challenge.
func (c *DelegatedFeeSponsorsClient) DeactivateFeeSponsorComplete(ctx context.Context, feeSponsorID string, challengeID string, assertion *signer.CredentialAssertion) (*DeactivateFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/deactivate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeactivateFeeSponsorResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ActivateFeeSponsorInit starts delegated user action signing for the activateFeeSponsor operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ActivateFeeSponsorComplete
// along with the same arguments given here.
func (c *DelegatedFeeSponsorsClient) ActivateFeeSponsorInit(ctx context.Context, feeSponsorID string) (*signer.UserActionChallenge, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/activate"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, nil)
}

// ActivateFeeSponsorComplete finishes delegated signing for the activateFeeSponsor operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ActivateFeeSponsorInit challenge.
func (c *DelegatedFeeSponsorsClient) ActivateFeeSponsorComplete(ctx context.Context, feeSponsorID string, challengeID string, assertion *signer.CredentialAssertion) (*ActivateFeeSponsorResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/activate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ActivateFeeSponsorResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves all fees paid by the specific Fee Sponsor.
func (c *DelegatedFeeSponsorsClient) ListSponsoredFees(ctx context.Context, feeSponsorID string, query *ListSponsoredFeesQuery) (*ListSponsoredFeesResponse, error) {
	path := "/fee-sponsors/" + url.PathEscape(feeSponsorID) + "/fees"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListSponsoredFeesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
