// Code generated by go-sdk-generator. DO NOT EDIT.

package feesponsors

// List Fee Sponsors
type ListFeeSponsorsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListFeeSponsorsQuery represents query parameters.
type ListFeeSponsorsQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Fee Sponsor
type CreateFeeSponsorRequest struct {
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// Create Fee Sponsor
type CreateFeeSponsorResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	Network map[string]interface{} `json:"network"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// Get Fee Sponsor
type GetFeeSponsorResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	Network map[string]interface{} `json:"network"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// Delete Fee Sponsor
type DeleteFeeSponsorResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	Network map[string]interface{} `json:"network"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// Deactivate Fee Sponsor
type DeactivateFeeSponsorResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	Network map[string]interface{} `json:"network"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// Activate Fee Sponsor
type ActivateFeeSponsorResponse struct {
	ID string `json:"id"`
	Name *string `json:"name,omitempty"`
	WalletID string `json:"walletId"`
	Network map[string]interface{} `json:"network"`
	Status string `json:"status"`
	DateCreated string `json:"dateCreated"`
	AllowEndUser *bool `json:"allowEndUser,omitempty"`
}

// List Sponsored Fees
type ListSponsoredFeesResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListSponsoredFeesQuery represents query parameters.
type ListSponsoredFeesQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}
