// Code generated by go-sdk-generator. DO NOT EDIT.

package signer

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
)

// KeySigner implements the Signer interface using a private key.
// It supports Ed25519, ECDSA (P-256, secp256k1), and RSA keys.
type KeySigner struct {
	// CredentialID is the ID of the credential registered with Dfns.
	CredentialID string

	// privateKey is the parsed private key.
	privateKey crypto.PrivateKey
}

// NewKeySigner creates a new KeySigner from a PEM-encoded private key.
// Supported key types: Ed25519, ECDSA (P-256, secp256k1), RSA.
func NewKeySigner(credentialID string, privateKeyPEM string) (*KeySigner, error) {
	if credentialID == "" {
		return nil, errors.New("credentialID is required")
	}

	if privateKeyPEM == "" {
		return nil, errors.New("privateKeyPEM is required")
	}

	privateKey, err := parsePrivateKey(privateKeyPEM)
	if err != nil {
		return nil, fmt.Errorf("failed to parse private key: %w", err)
	}

	return &KeySigner{
		CredentialID: credentialID,
		privateKey:   privateKey,
	}, nil
}

// Sign implements the Signer interface.
func (s *KeySigner) Sign(challenge *UserActionChallenge) (*CredentialAssertion, error) {
	if challenge == nil {
		return nil, errors.New("challenge is required")
	}

	// Create client data JSON (matches WebAuthn-style format)
	clientData := map[string]interface{}{
		"type":        "key.get",
		"challenge":   challenge.Challenge,
		"crossOrigin": false,
	}

	clientDataJSON, err := json.Marshal(clientData)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal client data: %w", err)
	}

	// Sign the client data
	signature, err := s.signBytes(clientDataJSON)
	if err != nil {
		return nil, fmt.Errorf("failed to sign: %w", err)
	}

	return &CredentialAssertion{
		Kind: "Key",
		CredentialAssertion: CredentialAssertionData{
			CredID:     s.CredentialID,
			ClientData: base64.RawURLEncoding.EncodeToString(clientDataJSON),
			Signature:  base64.RawURLEncoding.EncodeToString(signature),
		},
	}, nil
}

// signBytes signs data using the appropriate algorithm for the key type.
func (s *KeySigner) signBytes(data []byte) ([]byte, error) {
	switch key := s.privateKey.(type) {
	case ed25519.PrivateKey:
		// Ed25519 signs the raw data
		return ed25519.Sign(key, data), nil

	case *ecdsa.PrivateKey:
		// ECDSA signs a SHA-256 hash of the data
		hash := sha256.Sum256(data)
		return ecdsa.SignASN1(rand.Reader, key, hash[:])

	case *rsa.PrivateKey:
		// RSA-PKCS1v15 signs a SHA-256 hash of the data
		hash := sha256.Sum256(data)
		return rsa.SignPKCS1v15(rand.Reader, key, crypto.SHA256, hash[:])

	default:
		return nil, fmt.Errorf("unsupported key type: %T", s.privateKey)
	}
}

// parsePrivateKey parses a PEM-encoded private key.
func parsePrivateKey(pemData string) (crypto.PrivateKey, error) {
	block, _ := pem.Decode([]byte(pemData))
	if block == nil {
		return nil, errors.New("failed to decode PEM block")
	}

	// Try PKCS8 format first (works for Ed25519, ECDSA, RSA)
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err == nil {
		return key, nil
	}

	// Try EC private key format
	ecKey, err := x509.ParseECPrivateKey(block.Bytes)
	if err == nil {
		return ecKey, nil
	}

	// Try PKCS1 RSA format
	rsaKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err == nil {
		return rsaKey, nil
	}

	return nil, errors.New("unable to parse private key: unsupported format")
}
