// Code generated by go-sdk-generator. DO NOT EDIT.

package signer

// Signer is the interface for signing user action challenges.
// Implementations handle the cryptographic signing of challenges
// to prove user authorization for sensitive operations.
type Signer interface {
	// Sign takes a user action challenge and returns a signed credential assertion.
	// The assertion proves the user authorized the action.
	Sign(challenge *UserActionChallenge) (*CredentialAssertion, error)
}
