// Code generated by go-sdk-generator. DO NOT EDIT.

package signer

// UserActionChallenge represents the challenge returned by the auth/action/init endpoint.
type UserActionChallenge struct {
	// ChallengeIdentifier is a JWT that identifies this challenge session.
	ChallengeIdentifier string `json:"challengeIdentifier"`

	// Challenge is the base64url-encoded challenge string to sign.
	Challenge string `json:"challenge"`

	// AllowCredentials lists the credentials that can be used to sign.
	AllowCredentials AllowCredentials `json:"allowCredentials"`

	// SupportedCredentialKinds lists what credential types are supported.
	SupportedCredentialKinds []SupportedCredentialKind `json:"supportedCredentialKinds,omitempty"`

	// UserVerification indicates the user verification requirement.
	UserVerification string `json:"userVerification,omitempty"`
}

// AllowCredentials contains the credentials grouped by kind that can be used for signing.
type AllowCredentials struct {
	// Key lists key credentials that can be used to sign.
	Key []PublicKeyCredentialDescriptor `json:"key"`

	// WebAuthn lists WebAuthn credentials that can be used to sign.
	WebAuthn []PublicKeyCredentialDescriptor `json:"webauthn"`

	// PasswordProtectedKey lists password-protected key credentials that can be used to sign.
	PasswordProtectedKey []PasswordProtectedKeyDescriptor `json:"passwordProtectedKey,omitempty"`
}

// PublicKeyCredentialDescriptor identifies a credential for signing.
type PublicKeyCredentialDescriptor struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// PasswordProtectedKeyDescriptor identifies a password-protected key credential.
type PasswordProtectedKeyDescriptor struct {
	ID                  string `json:"id"`
	Type                string `json:"type"`
	EncryptedPrivateKey string `json:"encryptedPrivateKey"`
}

// SupportedCredentialKind describes a supported credential type.
type SupportedCredentialKind struct {
	Kind                 string `json:"kind"`
	Factor               string `json:"factor"`
	RequiresSecondFactor bool   `json:"requiresSecondFactor"`
}

// CredentialAssertion is the signed assertion to submit for user action verification.
type CredentialAssertion struct {
	// Kind is the credential type (e.g., "Key", "Fido2").
	Kind string `json:"kind"`

	// CredentialAssertion contains the signed data.
	CredentialAssertion CredentialAssertionData `json:"credentialAssertion"`
}

// CredentialAssertionData contains the actual signature data.
type CredentialAssertionData struct {
	// CredID is the credential identifier.
	CredID string `json:"credId"`

	// ClientData is the base64url-encoded client data JSON that was signed.
	ClientData string `json:"clientData"`

	// Signature is the base64url-encoded signature.
	Signature string `json:"signature"`
}
