// Code generated by go-sdk-generator. DO NOT EDIT.

package signers

import (
	"context"
	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// SignersClient provides methods for signers operations.
type SignersClient struct {
	client *client.Client
}

// NewSignersClient creates a new SignersClient.
func NewSignersClient(c *client.Client) *SignersClient {
	return &SignersClient{client: c}
}

// ListKeyStores list key stores.
func (c *SignersClient) ListKeyStores(ctx context.Context) (*ListKeyStoresResponse, error) {
	path := "/key-stores"
	var result ListKeyStoresResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListSigners list signers.
func (c *SignersClient) ListSigners(ctx context.Context) (*ListSignersResponse, error) {
	path := "/signers"
	var result ListSignersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
