// Code generated by go-sdk-generator. DO NOT EDIT.

package signers

import (
	"context"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedSignersClient provides delegated user action signing for signers operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedSignersClient struct {
	client *client.Client
}

// NewDelegatedSignersClient creates a new DelegatedSignersClient.
func NewDelegatedSignersClient(c *client.Client) *DelegatedSignersClient {
	return &DelegatedSignersClient{client: c}
}

// CreateAddMacUserInputInit starts delegated user action signing for the createAddMacUserInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateAddMacUserInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateAddMacUserInputInit(ctx context.Context, storeID string, body CreateAddMacUserInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/add-mac-user/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateAddMacUserInputComplete finishes delegated signing for the createAddMacUserInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateAddMacUserInputInit challenge.
func (c *DelegatedSignersClient) CreateAddMacUserInputComplete(ctx context.Context, storeID string, body CreateAddMacUserInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/add-mac-user/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// CreateCloneInputInit starts delegated user action signing for the createCloneInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateCloneInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateCloneInputInit(ctx context.Context, storeID string, body CreateCloneInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/clone/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateCloneInputComplete finishes delegated signing for the createCloneInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateCloneInputInit challenge.
func (c *DelegatedSignersClient) CreateCloneInputComplete(ctx context.Context, storeID string, body CreateCloneInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/clone/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// CreateGenesisInputInit starts delegated user action signing for the createGenesisInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateGenesisInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateGenesisInputInit(ctx context.Context, storeID string, body CreateGenesisInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/genesis/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateGenesisInputComplete finishes delegated signing for the createGenesisInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateGenesisInputInit challenge.
func (c *DelegatedSignersClient) CreateGenesisInputComplete(ctx context.Context, storeID string, body CreateGenesisInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/genesis/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// CreateKeyHarvestInputInit starts delegated user action signing for the createKeyHarvestInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateKeyHarvestInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateKeyHarvestInputInit(ctx context.Context, storeID string, body CreateKeyHarvestInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/key-harvest/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateKeyHarvestInputComplete finishes delegated signing for the createKeyHarvestInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateKeyHarvestInputInit challenge.
func (c *DelegatedSignersClient) CreateKeyHarvestInputComplete(ctx context.Context, storeID string, body CreateKeyHarvestInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/key-harvest/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// CreateOnchainSignInputInit starts delegated user action signing for the createOnchainSignInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateOnchainSignInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateOnchainSignInputInit(ctx context.Context, storeID string, body CreateOnchainSignInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/onchain-sign/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateOnchainSignInputComplete finishes delegated signing for the createOnchainSignInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateOnchainSignInputInit challenge.
func (c *DelegatedSignersClient) CreateOnchainSignInputComplete(ctx context.Context, storeID string, body CreateOnchainSignInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/onchain-sign/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// CreateProofOfControlInputInit starts delegated user action signing for the createProofOfControlInput operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateProofOfControlInputComplete
// along with the same arguments given here.
func (c *DelegatedSignersClient) CreateProofOfControlInputInit(ctx context.Context, storeID string, body CreateProofOfControlInputRequest) (*signer.UserActionChallenge, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/proof-of-control/input"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateProofOfControlInputComplete finishes delegated signing for the createProofOfControlInput operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateProofOfControlInputInit challenge.
func (c *DelegatedSignersClient) CreateProofOfControlInputComplete(ctx context.Context, storeID string, body CreateProofOfControlInputRequest, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/key-stores/" + url.PathEscape(storeID) + "/proof-of-control/input"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "POST", path, body, nil, userAction)
}

// Lists the key stores of your organization.
func (c *DelegatedSignersClient) ListKeyStores(ctx context.Context) (*ListKeyStoresResponse, error) {
	path := "/key-stores"
	var result ListKeyStoresResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists the signer clusters of your key store, including each signer's ID and encryption public key.
func (c *DelegatedSignersClient) ListSigners(ctx context.Context) (*ListSignersResponse, error) {
	path := "/signers"
	var result ListSignersResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Submits the output archive produced by the offline signer fleet for an add-mac-user operation.
func (c *DelegatedSignersClient) SubmitAddMacUserOutput(ctx context.Context, storeID string, body SubmitAddMacUserOutputRequest, file client.MultipartFile) (*SubmitAddMacUserOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/add-mac-user/output"
	var result SubmitAddMacUserOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Submits the output archive produced by the offline signer fleet for a clone operation.
func (c *DelegatedSignersClient) SubmitCloneOutput(ctx context.Context, storeID string, body SubmitCloneOutputRequest, file client.MultipartFile) (*SubmitCloneOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/clone/output"
	var result SubmitCloneOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Submits the output archive produced by the offline signer fleet for a genesis operation.
func (c *DelegatedSignersClient) SubmitGenesisOutput(ctx context.Context, storeID string, body SubmitGenesisOutputRequest, file client.MultipartFile) (*SubmitGenesisOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/genesis/output"
	var result SubmitGenesisOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SubmitKeyHarvestOutput submit key harvest output.
func (c *DelegatedSignersClient) SubmitKeyHarvestOutput(ctx context.Context, storeID string, body SubmitKeyHarvestOutputRequest, file client.MultipartFile) (*SubmitKeyHarvestOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/key-harvest/output"
	var result SubmitKeyHarvestOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Submits the output archive produced by the offline signer fleet for an onchain-sign operation.
func (c *DelegatedSignersClient) SubmitOnchainSignOutput(ctx context.Context, storeID string, body SubmitOnchainSignOutputRequest, file client.MultipartFile) (*SubmitOnchainSignOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/onchain-sign/output"
	var result SubmitOnchainSignOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Submits the output archive produced by the offline signer fleet for a proof-of-control operation.
func (c *DelegatedSignersClient) SubmitProofOfControlOutput(ctx context.Context, storeID string, body SubmitProofOfControlOutputRequest, file client.MultipartFile) (*SubmitProofOfControlOutputResponse, error) {
	path := "/key-stores/" + url.PathEscape(storeID) + "/proof-of-control/output"
	var result SubmitProofOfControlOutputResponse
	err := c.client.DoMultipart(ctx, "POST", path, body, file, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
