// Code generated by go-sdk-generator. DO NOT EDIT.

package signers

// List Key Stores
type ListKeyStoresResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// List Signers
type ListSignersResponse struct {
	Clusters []map[string]interface{} `json:"clusters"`
}
