// Code generated by go-sdk-generator. DO NOT EDIT.

package signers

// Create Add Mac User Input
type CreateAddMacUserInputRequest struct {
	Kind string `json:"kind"`
	MacTargetSerial string `json:"macTargetSerial"`
	HsmTargetSerial string `json:"hsmTargetSerial"`
}

// Create Clone Input
type CreateCloneInputRequest struct {
	Kind string `json:"kind"`
	HsmSourceSerial string `json:"hsmSourceSerial"`
	HsmTargetSerial string `json:"hsmTargetSerial"`
	MacTargetSerial *string `json:"macTargetSerial,omitempty"`
}

// Create Genesis Input
type CreateGenesisInputRequest struct {
	Kind string `json:"kind"`
	NumProvisioners int64 `json:"numProvisioners"`
	NumSecp256k1 int64 `json:"numSecp256k1"`
	NumEd25519 int64 `json:"numEd25519"`
	HsmGenesisSerial string `json:"hsmGenesisSerial"`
	MacGenesisSerial *string `json:"macGenesisSerial,omitempty"`
	HsmGenesisFirmwareVersion *string `json:"hsmGenesisFirmwareVersion,omitempty"`
	DebugOptions map[string]map[string]interface{} `json:"debugOptions,omitempty"`
}

// Create Key Harvest Input
type CreateKeyHarvestInputRequest struct {
	Kind string `json:"kind"`
	HsmTargetSerial string `json:"hsmTargetSerial"`
	MacTargetSerial string `json:"macTargetSerial"`
	MacTargetUsername string `json:"macTargetUsername"`
	NumSecp256k1 *int64 `json:"numSecp256k1,omitempty"`
	NumEd25519 *int64 `json:"numEd25519,omitempty"`
}

// Create Onchain Sign Input
type CreateOnchainSignInputRequest struct {
}

// Create Proof Of Control Input
type CreateProofOfControlInputRequest struct {
	WalletIDs []string `json:"walletIds"`
}

// List Key Stores
type ListKeyStoresResponse struct {
	Items []map[string]interface{} `json:"items"`
}

// List Signers
type ListSignersResponse struct {
	Clusters []map[string]interface{} `json:"clusters"`
}

// Submit Add Mac User Output
type SubmitAddMacUserOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Add Mac User Output
type SubmitAddMacUserOutputResponse struct {
	Message string `json:"message"`
}

// Submit Clone Output
type SubmitCloneOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Clone Output
type SubmitCloneOutputResponse struct {
	Message string `json:"message"`
}

// Submit Genesis Output
type SubmitGenesisOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Genesis Output
type SubmitGenesisOutputResponse struct {
	Message string `json:"message"`
}

// Submit Key Harvest Output
type SubmitKeyHarvestOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Key Harvest Output
type SubmitKeyHarvestOutputResponse struct {
	Message string `json:"message"`
}

// Submit Onchain Sign Output
type SubmitOnchainSignOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Onchain Sign Output
type SubmitOnchainSignOutputResponse struct {
	Status string `json:"status"`
}

// Submit Proof Of Control Output
type SubmitProofOfControlOutputRequest struct {
	FileChecksum string `json:"fileChecksum"`
	OutputJSON map[string]interface{} `json:"outputJson"`
}

// Submit Proof Of Control Output
type SubmitProofOfControlOutputResponse struct {
	Status string `json:"status"`
}
