// Code generated by go-sdk-generator. DO NOT EDIT.

package allocations

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/internal/client"
)

// AllocationsClient provides methods for allocations operations.
type AllocationsClient struct {
	client *client.Client
}

// NewAllocationsClient creates a new AllocationsClient.
func NewAllocationsClient(c *client.Client) *AllocationsClient {
	return &AllocationsClient{client: c}
}

// ListAllocations list allocations.
func (c *AllocationsClient) ListAllocations(ctx context.Context, query *ListAllocationsQuery) (*ListAllocationsResponse, error) {
	path := "/allocations"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAllocationsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new allocation.
func (c *AllocationsClient) CreateAllocation(ctx context.Context, body CreateAllocationRequest) (*CreateAllocationResponse, error) {
	path := "/allocations"
	var result CreateAllocationResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of actions for a specific allocation.
func (c *AllocationsClient) ListAllocationActions(ctx context.Context, allocationID string, query *ListAllocationActionsQuery) (*ListAllocationActionsResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID) + "/actions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAllocationActionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new action for an existing allocation.
func (c *AllocationsClient) CreateAllocationAction(ctx context.Context, allocationID string, body CreateAllocationActionRequest) (*CreateAllocationActionResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID) + "/actions"
	var result CreateAllocationActionResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the details of a specific allocation.
func (c *AllocationsClient) GetAllocation(ctx context.Context, allocationID string) (*GetAllocationResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID)
	var result GetAllocationResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
