// Code generated by go-sdk-generator. DO NOT EDIT.

package allocations

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedAllocationsClient provides delegated user action signing for allocations operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedAllocationsClient struct {
	client *client.Client
}

// NewDelegatedAllocationsClient creates a new DelegatedAllocationsClient.
func NewDelegatedAllocationsClient(c *client.Client) *DelegatedAllocationsClient {
	return &DelegatedAllocationsClient{client: c}
}

// Lists the allocations of your organization.
func (c *DelegatedAllocationsClient) ListAllocations(ctx context.Context, query *ListAllocationsQuery) (*ListAllocationsResponse, error) {
	path := "/allocations"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAllocationsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateAllocationInit starts delegated user action signing for the createAllocation operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateAllocationComplete
// along with the same arguments given here.
func (c *DelegatedAllocationsClient) CreateAllocationInit(ctx context.Context, body CreateAllocationRequest) (*signer.UserActionChallenge, error) {
	path := "/allocations"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateAllocationComplete finishes delegated signing for the createAllocation operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateAllocationInit challenge.
func (c *DelegatedAllocationsClient) CreateAllocationComplete(ctx context.Context, body CreateAllocationRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateAllocationResponse, error) {
	path := "/allocations"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateAllocationResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of actions for a specific allocation.
func (c *DelegatedAllocationsClient) ListAllocationActions(ctx context.Context, allocationID string, query *ListAllocationActionsQuery) (*ListAllocationActionsResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID) + "/actions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListAllocationActionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateAllocationActionInit starts delegated user action signing for the createAllocationAction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateAllocationActionComplete
// along with the same arguments given here.
func (c *DelegatedAllocationsClient) CreateAllocationActionInit(ctx context.Context, allocationID string, body CreateAllocationActionRequest) (*signer.UserActionChallenge, error) {
	path := "/allocations/" + url.PathEscape(allocationID) + "/actions"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateAllocationActionComplete finishes delegated signing for the createAllocationAction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateAllocationActionInit challenge.
func (c *DelegatedAllocationsClient) CreateAllocationActionComplete(ctx context.Context, allocationID string, body CreateAllocationActionRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateAllocationActionResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID) + "/actions"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateAllocationActionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the details of a specific allocation.
func (c *DelegatedAllocationsClient) GetAllocation(ctx context.Context, allocationID string) (*GetAllocationResponse, error) {
	path := "/allocations/" + url.PathEscape(allocationID)
	var result GetAllocationResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
