// Code generated by go-sdk-generator. DO NOT EDIT.

package allocations

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// List Allocations
type ListAllocationsResponse struct {
	Items []types.Allocation `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAllocationsQuery represents query parameters.
type ListAllocationsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateAllocationRequest represents the request body for the createAllocation operation.
type CreateAllocationRequest = any

// Create Allocation
type CreateAllocationResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Provider *string `json:"provider,omitempty"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}

// List Allocation Actions
type ListAllocationActionsResponse struct {
	Items []types.AllocationAction `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAllocationActionsQuery represents query parameters.
type ListAllocationActionsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateAllocationActionRequest represents the request body for the createAllocationAction operation.
type CreateAllocationActionRequest = any

// Create Allocation Action
type CreateAllocationActionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Provider *string `json:"provider,omitempty"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}

// Get Allocation
type GetAllocationResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Provider *string `json:"provider,omitempty"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}

// Get Allocations Info
type GetAllocationsInfoResponse struct {
	Ofns *map[string]interface{} `json:"0fns,omitempty"`
	SkySusds *map[string]interface{} `json:"SkySusds,omitempty"`
	GauntletUsdcPrime *map[string]interface{} `json:"GauntletUsdcPrime,omitempty"`
	SteakhouseUsdt *map[string]interface{} `json:"SteakhouseUsdt,omitempty"`
	GauntletUsdcPrimeBase *map[string]interface{} `json:"GauntletUsdcPrimeBase,omitempty"`
	SteakhouseUsdcBase *map[string]interface{} `json:"SteakhouseUsdcBase,omitempty"`
	SentoraPyusdMain *map[string]interface{} `json:"SentoraPyusdMain,omitempty"`
}
