// Code generated by go-sdk-generator. DO NOT EDIT.

package allocations

import (
	"github.com/dfns/dfns-sdk-go/types"
)

// List Allocations
type ListAllocationsResponse struct {
	Items []types.Allocation `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAllocationsQuery represents query parameters.
type ListAllocationsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// CreateAllocationRequest represents the request body for the createAllocation operation.
type CreateAllocationRequest = any

// Create Allocation
type CreateAllocationResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}

// List Allocation Actions
type ListAllocationActionsResponse struct {
	Items []types.AllocationAction `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListAllocationActionsQuery represents query parameters.
type ListAllocationActionsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Allocation Action
type CreateAllocationActionRequest struct {
	Kind string `json:"kind"`
	ExternalID *string `json:"externalId,omitempty"`
	SourceAsset map[string]interface{} `json:"sourceAsset"`
	TargetAsset map[string]interface{} `json:"targetAsset"`
	SlippageBps float64 `json:"slippageBps"`
}

// Create Allocation Action
type CreateAllocationActionResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}

// Get Allocation
type GetAllocationResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Protocol string `json:"protocol"`
	Amount map[string]interface{} `json:"amount"`
	Rewards map[string]interface{} `json:"rewards"`
	DateCreated string `json:"dateCreated"`
	Actions []types.AllocationAction `json:"actions"`
}
