// Code generated by go-sdk-generator. DO NOT EDIT.

package webhooks

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// WebhooksClient provides methods for webhooks operations.
type WebhooksClient struct {
	client *client.Client
}

// NewWebhooksClient creates a new WebhooksClient.
func NewWebhooksClient(c *client.Client) *WebhooksClient {
	return &WebhooksClient{client: c}
}

// List all webhooks for the authenticated user's organization. The results are paginated.
func (c *WebhooksClient) ListWebhooks(ctx context.Context, query *ListWebhooksQuery) (*ListWebhooksResponse, error) {
	path := "/webhooks"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListWebhooksResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Register a new webhook.
func (c *WebhooksClient) CreateWebhook(ctx context.Context, body CreateWebhookRequest) (*CreateWebhookResponse, error) {
	path := "/webhooks"
	var result CreateWebhookResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific webhook.
func (c *WebhooksClient) GetWebhook(ctx context.Context, webhookID string) (*GetWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	var result GetWebhookResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Update the definition of an existing webhook.
func (c *WebhooksClient) UpdateWebhook(ctx context.Context, webhookID string, body UpdateWebhookRequest) (*UpdateWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	var result UpdateWebhookResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Deletes an existing webhook registration.
func (c *WebhooksClient) DeleteWebhook(ctx context.Context, webhookID string) (*DeleteWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	var result DeleteWebhookResponse
	err := c.client.Do(ctx, "DELETE", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// This endpoint is meant for webhook setup and troubleshooting. Calling the endpoint will trigger a fake test event that will be pushed to the webhook url. The fake event will not be saved and not appear in further requests to Webhook Events.
func (c *WebhooksClient) PingWebhook(ctx context.Context, webhookID string) (*PingWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/ping"
	var result PingWebhookResponse
	err := c.client.Do(ctx, "POST", path, nil, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a specific webhook event details by its ID.
//   
// <Warning>
func (c *WebhooksClient) GetWebhookEvent(ctx context.Context, webhookID string, webhookEventID string) (*GetWebhookEventResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/events/" + url.PathEscape(webhookEventID)
	var result GetWebhookEventResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists all events for a given webhook. 
// 
// 
func (c *WebhooksClient) ListWebhookEvents(ctx context.Context, webhookID string, query *ListWebhookEventsQuery) (*ListWebhookEventsResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/events"
	if query != nil {
		q := url.Values{}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.DeliveryFailed != nil {
			q.Set("deliveryFailed", fmt.Sprintf("%v", *query.DeliveryFailed))
		}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListWebhookEventsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
