// Code generated by go-sdk-generator. DO NOT EDIT.

package webhooks

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedWebhooksClient provides delegated user action signing for webhooks operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedWebhooksClient struct {
	client *client.Client
}

// NewDelegatedWebhooksClient creates a new DelegatedWebhooksClient.
func NewDelegatedWebhooksClient(c *client.Client) *DelegatedWebhooksClient {
	return &DelegatedWebhooksClient{client: c}
}

// List all webhooks for the authenticated user's organization. The results are paginated.
func (c *DelegatedWebhooksClient) ListWebhooks(ctx context.Context, query *ListWebhooksQuery) (*ListWebhooksResponse, error) {
	path := "/webhooks"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListWebhooksResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateWebhookInit starts delegated user action signing for the createWebhook operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateWebhookComplete
// along with the same arguments given here.
func (c *DelegatedWebhooksClient) CreateWebhookInit(ctx context.Context, body CreateWebhookRequest) (*signer.UserActionChallenge, error) {
	path := "/webhooks"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateWebhookComplete finishes delegated signing for the createWebhook operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateWebhookInit challenge.
func (c *DelegatedWebhooksClient) CreateWebhookComplete(ctx context.Context, body CreateWebhookRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateWebhookResponse, error) {
	path := "/webhooks"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateWebhookResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve information about a specific webhook.
func (c *DelegatedWebhooksClient) GetWebhook(ctx context.Context, webhookID string) (*GetWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	var result GetWebhookResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWebhookInit starts delegated user action signing for the updateWebhook operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateWebhookComplete
// along with the same arguments given here.
func (c *DelegatedWebhooksClient) UpdateWebhookInit(ctx context.Context, webhookID string, body UpdateWebhookRequest) (*signer.UserActionChallenge, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateWebhookComplete finishes delegated signing for the updateWebhook operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateWebhookInit challenge.
func (c *DelegatedWebhooksClient) UpdateWebhookComplete(ctx context.Context, webhookID string, body UpdateWebhookRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateWebhookResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWebhookInit starts delegated user action signing for the deleteWebhook operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteWebhookComplete
// along with the same arguments given here.
func (c *DelegatedWebhooksClient) DeleteWebhookInit(ctx context.Context, webhookID string) (*signer.UserActionChallenge, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteWebhookComplete finishes delegated signing for the deleteWebhook operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteWebhookInit challenge.
func (c *DelegatedWebhooksClient) DeleteWebhookComplete(ctx context.Context, webhookID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteWebhookResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// PingWebhookInit starts delegated user action signing for the pingWebhook operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to PingWebhookComplete
// along with the same arguments given here.
func (c *DelegatedWebhooksClient) PingWebhookInit(ctx context.Context, webhookID string) (*signer.UserActionChallenge, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/ping"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, nil)
}

// PingWebhookComplete finishes delegated signing for the pingWebhook operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the PingWebhookInit challenge.
func (c *DelegatedWebhooksClient) PingWebhookComplete(ctx context.Context, webhookID string, challengeID string, assertion *signer.CredentialAssertion) (*PingWebhookResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/ping"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result PingWebhookResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a specific webhook event details by its ID.
//   
// <Warning>
func (c *DelegatedWebhooksClient) GetWebhookEvent(ctx context.Context, webhookID string, webhookEventID string) (*GetWebhookEventResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/events/" + url.PathEscape(webhookEventID)
	var result GetWebhookEventResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists all events for a given webhook. 
// 
// 
func (c *DelegatedWebhooksClient) ListWebhookEvents(ctx context.Context, webhookID string, query *ListWebhookEventsQuery) (*ListWebhookEventsResponse, error) {
	path := "/webhooks/" + url.PathEscape(webhookID) + "/events"
	if query != nil {
		q := url.Values{}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.DeliveryFailed != nil {
			q.Set("deliveryFailed", fmt.Sprintf("%v", *query.DeliveryFailed))
		}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListWebhookEventsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
