// Code generated by go-sdk-generator. DO NOT EDIT.

package webhooks

// List Webhooks
type ListWebhooksResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListWebhooksQuery represents query parameters.
type ListWebhooksQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Webhook
type CreateWebhookRequest struct {
	URL string `json:"url"`
	Status *string `json:"status,omitempty"`
	Description *string `json:"description,omitempty"`
	Events []interface{} `json:"events"`
}

// Create Webhook
type CreateWebhookResponse struct {
	ID string `json:"id"`
	URL string `json:"url"`
	Events []interface{} `json:"events"`
	Status string `json:"status"`
	Description *string `json:"description,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
	Secret string `json:"secret"`
}

// Get Webhook
type GetWebhookResponse struct {
	ID string `json:"id"`
	URL string `json:"url"`
	Events []interface{} `json:"events"`
	Status string `json:"status"`
	Description *string `json:"description,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

// Update Webhook
type UpdateWebhookRequest struct {
	URL *string `json:"url,omitempty"`
	Description *string `json:"description,omitempty"`
	Events []interface{} `json:"events,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Update Webhook
type UpdateWebhookResponse struct {
	ID string `json:"id"`
	URL string `json:"url"`
	Events []interface{} `json:"events"`
	Status string `json:"status"`
	Description *string `json:"description,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

// Delete Webhook
type DeleteWebhookResponse struct {
	Deleted string `json:"deleted"`
}

// Ping Webhook
type PingWebhookResponse struct {
	Status string `json:"status"`
	ErrorType *string `json:"error,omitempty"`
}

// Get Webhook Event
type GetWebhookEventResponse struct {
	ID string `json:"id"`
	Date string `json:"date"`
	Kind string `json:"kind"`
	Data map[string]map[string]interface{} `json:"data"`
	Status string `json:"status"`
	ErrorType *string `json:"error,omitempty"`
	TimestampSent int64 `json:"timestampSent"`
}

// List Webhook Events
type ListWebhookEventsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListWebhookEventsQuery represents query parameters.
type ListWebhookEventsQuery struct {
	Kind *string `json:"kind,omitempty"`
	DeliveryFailed *string `json:"deliveryFailed,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}
