// Code generated by go-sdk-generator. DO NOT EDIT.

package policies

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedPoliciesClient provides delegated user action signing for policies operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedPoliciesClient struct {
	client *client.Client
}

// NewDelegatedPoliciesClient creates a new DelegatedPoliciesClient.
func NewDelegatedPoliciesClient(c *client.Client) *DelegatedPoliciesClient {
	return &DelegatedPoliciesClient{client: c}
}

// Retrieve information about a specific policy.
func (c *DelegatedPoliciesClient) GetPolicy(ctx context.Context, policyID string) (*GetPolicyResponse, error) {
	path := "/v2/policies/" + url.PathEscape(policyID)
	var result GetPolicyResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdatePolicyInit starts delegated user action signing for the updatePolicy operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdatePolicyComplete
// along with the same arguments given here.
func (c *DelegatedPoliciesClient) UpdatePolicyInit(ctx context.Context, policyID string, body UpdatePolicyRequest) (*signer.UserActionChallenge, error) {
	path := "/v2/policies/" + url.PathEscape(policyID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdatePolicyComplete finishes delegated signing for the updatePolicy operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdatePolicyInit challenge.
func (c *DelegatedPoliciesClient) UpdatePolicyComplete(ctx context.Context, policyID string, body UpdatePolicyRequest, challengeID string, assertion *signer.CredentialAssertion) (interface{}, error) {
	path := "/v2/policies/" + url.PathEscape(policyID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return result, nil
}

// DeletePolicyInit starts delegated user action signing for the deletePolicy operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeletePolicyComplete
// along with the same arguments given here.
func (c *DelegatedPoliciesClient) DeletePolicyInit(ctx context.Context, policyID string) (*signer.UserActionChallenge, error) {
	path := "/v2/policies/" + url.PathEscape(policyID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeletePolicyComplete finishes delegated signing for the deletePolicy operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeletePolicyInit challenge.
func (c *DelegatedPoliciesClient) DeletePolicyComplete(ctx context.Context, policyID string, challengeID string, assertion *signer.CredentialAssertion) (interface{}, error) {
	path := "/v2/policies/" + url.PathEscape(policyID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return result, nil
}

// CreateApprovalDecisionInit starts delegated user action signing for the createApprovalDecision operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateApprovalDecisionComplete
// along with the same arguments given here.
func (c *DelegatedPoliciesClient) CreateApprovalDecisionInit(ctx context.Context, approvalID string, body CreateApprovalDecisionRequest) (*signer.UserActionChallenge, error) {
	path := "/v2/policy-approvals/" + url.PathEscape(approvalID) + "/decisions"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateApprovalDecisionComplete finishes delegated signing for the createApprovalDecision operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateApprovalDecisionInit challenge.
func (c *DelegatedPoliciesClient) CreateApprovalDecisionComplete(ctx context.Context, approvalID string, body CreateApprovalDecisionRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateApprovalDecisionResponse, error) {
	path := "/v2/policy-approvals/" + url.PathEscape(approvalID) + "/decisions"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateApprovalDecisionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of policies on your organization.
func (c *DelegatedPoliciesClient) ListPolicies(ctx context.Context, query *ListPoliciesQuery) (*ListPoliciesResponse, error) {
	path := "/v2/policies"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Status != nil {
			q.Set("status", fmt.Sprintf("%v", *query.Status))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPoliciesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePolicyInit starts delegated user action signing for the createPolicy operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePolicyComplete
// along with the same arguments given here.
func (c *DelegatedPoliciesClient) CreatePolicyInit(ctx context.Context, body CreatePolicyRequest) (*signer.UserActionChallenge, error) {
	path := "/v2/policies"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePolicyComplete finishes delegated signing for the createPolicy operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePolicyInit challenge.
func (c *DelegatedPoliciesClient) CreatePolicyComplete(ctx context.Context, body CreatePolicyRequest, challengeID string, assertion *signer.CredentialAssertion) (interface{}, error) {
	path := "/v2/policies"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result interface{}
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return result, nil
}

// Retrieve information about a specific approval request.
func (c *DelegatedPoliciesClient) GetApproval(ctx context.Context, approvalID string) (*GetApprovalResponse, error) {
	path := "/v2/policy-approvals/" + url.PathEscape(approvalID)
	var result GetApprovalResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of pending approval requests.
func (c *DelegatedPoliciesClient) ListApprovals(ctx context.Context, query *ListApprovalsQuery) (*ListApprovalsResponse, error) {
	path := "/v2/policy-approvals"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Status != nil {
			q.Set("status", fmt.Sprintf("%v", *query.Status))
		}
		if query.InitiatorID != nil {
			q.Set("initiatorId", fmt.Sprintf("%v", *query.InitiatorID))
		}
		if query.ApproverID != nil {
			q.Set("approverId", fmt.Sprintf("%v", *query.ApproverID))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListApprovalsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
