// Code generated by go-sdk-generator. DO NOT EDIT.

package keys

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedKeysClient provides delegated user action signing for keys operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedKeysClient struct {
	client *client.Client
}

// NewDelegatedKeysClient creates a new DelegatedKeysClient.
func NewDelegatedKeysClient(c *client.Client) *DelegatedKeysClient {
	return &DelegatedKeysClient{client: c}
}

// Retrieve all keys registered for your organization.
func (c *DelegatedKeysClient) ListKeys(ctx context.Context, query *ListKeysQuery) (*ListKeysResponse, error) {
	path := "/keys"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Owner != nil {
			q.Set("owner", fmt.Sprintf("%v", *query.Owner))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListKeysResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateKeyInit starts delegated user action signing for the createKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) CreateKeyInit(ctx context.Context, body CreateKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateKeyComplete finishes delegated signing for the createKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateKeyInit challenge.
func (c *DelegatedKeysClient) CreateKeyComplete(ctx context.Context, body CreateKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateKeyResponse, error) {
	path := "/keys"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DelegateKeyInit starts delegated user action signing for the delegateKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DelegateKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) DelegateKeyInit(ctx context.Context, keyID string, body DelegateKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/delegate"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// DelegateKeyComplete finishes delegated signing for the delegateKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DelegateKeyInit challenge.
func (c *DelegatedKeysClient) DelegateKeyComplete(ctx context.Context, keyID string, body DelegateKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*DelegateKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/delegate"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DelegateKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a key information by its ID.
func (c *DelegatedKeysClient) GetKey(ctx context.Context, keyID string) (*GetKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID)
	var result GetKeyResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateKeyInit starts delegated user action signing for the updateKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) UpdateKeyInit(ctx context.Context, keyID string, body UpdateKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateKeyComplete finishes delegated signing for the updateKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateKeyInit challenge.
func (c *DelegatedKeysClient) UpdateKeyComplete(ctx context.Context, keyID string, body UpdateKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteKeyInit starts delegated user action signing for the deleteKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeleteKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) DeleteKeyInit(ctx context.Context, keyID string) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// DeleteKeyComplete finishes delegated signing for the deleteKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeleteKeyInit challenge.
func (c *DelegatedKeysClient) DeleteKeyComplete(ctx context.Context, keyID string, challengeID string, assertion *signer.CredentialAssertion) (*DeleteKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeleteKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeriveKeyInit starts delegated user action signing for the deriveKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to DeriveKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) DeriveKeyInit(ctx context.Context, keyID string, body DeriveKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/derive"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// DeriveKeyComplete finishes delegated signing for the deriveKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the DeriveKeyInit challenge.
func (c *DelegatedKeysClient) DeriveKeyComplete(ctx context.Context, keyID string, body DeriveKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*DeriveKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/derive"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result DeriveKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// ExportKeyInit starts delegated user action signing for the exportKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ExportKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) ExportKeyInit(ctx context.Context, keyID string, body ExportKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/export"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// ExportKeyComplete finishes delegated signing for the exportKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ExportKeyInit challenge.
func (c *DelegatedKeysClient) ExportKeyComplete(ctx context.Context, keyID string, body ExportKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*ExportKeyResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/export"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ExportKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// List all signature requests for a key.
func (c *DelegatedKeysClient) ListSignatures(ctx context.Context, keyID string, query *ListSignaturesQuery) (*ListSignaturesResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/signatures"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListSignaturesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GenerateSignatureInit starts delegated user action signing for the generateSignature operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to GenerateSignatureComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) GenerateSignatureInit(ctx context.Context, keyID string, body GenerateSignatureRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/signatures"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// GenerateSignatureComplete finishes delegated signing for the generateSignature operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the GenerateSignatureInit challenge.
func (c *DelegatedKeysClient) GenerateSignatureComplete(ctx context.Context, keyID string, body GenerateSignatureRequest, challengeID string, assertion *signer.CredentialAssertion) (*GenerateSignatureResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/signatures"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result GenerateSignatureResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve a signature request details.
func (c *DelegatedKeysClient) GetSignature(ctx context.Context, keyID string, signatureID string) (*GetSignatureResponse, error) {
	path := "/keys/" + url.PathEscape(keyID) + "/signatures/" + url.PathEscape(signatureID)
	var result GetSignatureResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ImportKeyInit starts delegated user action signing for the importKey operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ImportKeyComplete
// along with the same arguments given here.
func (c *DelegatedKeysClient) ImportKeyInit(ctx context.Context, body ImportKeyRequest) (*signer.UserActionChallenge, error) {
	path := "/keys/import"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// ImportKeyComplete finishes delegated signing for the importKey operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ImportKeyInit challenge.
func (c *DelegatedKeysClient) ImportKeyComplete(ctx context.Context, body ImportKeyRequest, challengeID string, assertion *signer.CredentialAssertion) (*ImportKeyResponse, error) {
	path := "/keys/import"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ImportKeyResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
