// Code generated by go-sdk-generator. DO NOT EDIT.

package permissions

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
)

// PermissionsClient provides methods for permissions operations.
type PermissionsClient struct {
	client *client.Client
}

// NewPermissionsClient creates a new PermissionsClient.
func NewPermissionsClient(c *client.Client) *PermissionsClient {
	return &PermissionsClient{client: c}
}

// Retrieves a list of permission assignments (success) or gives a reason why it's not possible (failure).
func (c *PermissionsClient) ListPermissionAssignments(ctx context.Context, permissionID string) (*ListPermissionAssignmentsResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments"
	var result ListPermissionAssignmentsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Creates a permission that allows certain specified operations to be executed. 
//   
//   Response is either the permission object itself (success) or a reason why it was not possible to create the permission (failure).
func (c *PermissionsClient) AssignPermission(ctx context.Context, permissionID string, body AssignPermissionRequest) (*AssignPermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments"
	var result AssignPermissionResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Revokes a permission assignment (success) or gives reason why it’s not possible (failure).
func (c *PermissionsClient) RevokePermission(ctx context.Context, permissionID string, assignmentID string, query *RevokePermissionQuery) error {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments/" + url.PathEscape(assignmentID)
	if query != nil {
		q := url.Values{}
		if query.Force != nil {
			q.Set("force", fmt.Sprintf("%v", *query.Force))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	return c.client.Do(ctx, "DELETE", path, nil, nil, true)
}

// Delete a specific Permission.
func (c *PermissionsClient) DeletePermission(ctx context.Context, permissionID string, body DeletePermissionRequest) (*DeletePermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/archive"
	var result DeletePermissionResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a list of permissions (success) or gives a reason why it's not possible (failure).
func (c *PermissionsClient) ListPermissions(ctx context.Context, query *ListPermissionsQuery) (*ListPermissionsResponse, error) {
	path := "/permissions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPermissionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Creates a permission that allows certain specified operations to be executed.
func (c *PermissionsClient) CreatePermission(ctx context.Context, body CreatePermissionRequest) (*CreatePermissionResponse, error) {
	path := "/permissions"
	var result CreatePermissionResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a specific permission (success) or gives a reason why it's not possible (failure).
func (c *PermissionsClient) GetPermission(ctx context.Context, permissionID string) (*GetPermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID)
	var result GetPermissionResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Updates an existing permission. Response either returns the updated permission (success) or the reason why it was not possible to update (failure).
func (c *PermissionsClient) UpdatePermission(ctx context.Context, permissionID string, body UpdatePermissionRequest) (*UpdatePermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID)
	var result UpdatePermissionResponse
	err := c.client.Do(ctx, "PUT", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
