// Code generated by go-sdk-generator. DO NOT EDIT.

package permissions

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedPermissionsClient provides delegated user action signing for permissions operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedPermissionsClient struct {
	client *client.Client
}

// NewDelegatedPermissionsClient creates a new DelegatedPermissionsClient.
func NewDelegatedPermissionsClient(c *client.Client) *DelegatedPermissionsClient {
	return &DelegatedPermissionsClient{client: c}
}

// ArchivePermissionInit starts delegated user action signing for the archivePermission operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to ArchivePermissionComplete
// along with the same arguments given here.
func (c *DelegatedPermissionsClient) ArchivePermissionInit(ctx context.Context, permissionID string, body ArchivePermissionRequest) (*signer.UserActionChallenge, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/archive"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// ArchivePermissionComplete finishes delegated signing for the archivePermission operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the ArchivePermissionInit challenge.
func (c *DelegatedPermissionsClient) ArchivePermissionComplete(ctx context.Context, permissionID string, body ArchivePermissionRequest, challengeID string, assertion *signer.CredentialAssertion) (*ArchivePermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/archive"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result ArchivePermissionResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists all permission (role) assignments for a given permission.
func (c *DelegatedPermissionsClient) ListPermissionAssignments(ctx context.Context, permissionID string, query *ListPermissionAssignmentsQuery) (*ListPermissionAssignmentsResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPermissionAssignmentsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AssignPermissionInit starts delegated user action signing for the assignPermission operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to AssignPermissionComplete
// along with the same arguments given here.
func (c *DelegatedPermissionsClient) AssignPermissionInit(ctx context.Context, permissionID string, body AssignPermissionRequest) (*signer.UserActionChallenge, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// AssignPermissionComplete finishes delegated signing for the assignPermission operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the AssignPermissionInit challenge.
func (c *DelegatedPermissionsClient) AssignPermissionComplete(ctx context.Context, permissionID string, body AssignPermissionRequest, challengeID string, assertion *signer.CredentialAssertion) (*AssignPermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result AssignPermissionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists all permissions (roles) in the organization.
func (c *DelegatedPermissionsClient) ListPermissions(ctx context.Context, query *ListPermissionsQuery) (*ListPermissionsResponse, error) {
	path := "/permissions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListPermissionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreatePermissionInit starts delegated user action signing for the createPermission operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreatePermissionComplete
// along with the same arguments given here.
func (c *DelegatedPermissionsClient) CreatePermissionInit(ctx context.Context, body CreatePermissionRequest) (*signer.UserActionChallenge, error) {
	path := "/permissions"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreatePermissionComplete finishes delegated signing for the createPermission operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreatePermissionInit challenge.
func (c *DelegatedPermissionsClient) CreatePermissionComplete(ctx context.Context, body CreatePermissionRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreatePermissionResponse, error) {
	path := "/permissions"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreatePermissionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// RevokePermissionInit starts delegated user action signing for the revokePermission operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to RevokePermissionComplete
// along with the same arguments given here.
func (c *DelegatedPermissionsClient) RevokePermissionInit(ctx context.Context, permissionID string, assignmentID string, query *RevokePermissionQuery) (*signer.UserActionChallenge, error) {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments/" + url.PathEscape(assignmentID)
	if query != nil {
		q := url.Values{}
		if query.Force != nil {
			q.Set("force", fmt.Sprintf("%v", *query.Force))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, nil)
}

// RevokePermissionComplete finishes delegated signing for the revokePermission operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the RevokePermissionInit challenge.
func (c *DelegatedPermissionsClient) RevokePermissionComplete(ctx context.Context, permissionID string, assignmentID string, query *RevokePermissionQuery, challengeID string, assertion *signer.CredentialAssertion) error {
	path := "/permissions/" + url.PathEscape(permissionID) + "/assignments/" + url.PathEscape(assignmentID)
	if query != nil {
		q := url.Values{}
		if query.Force != nil {
			q.Set("force", fmt.Sprintf("%v", *query.Force))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return err
	}
	return c.client.DoWithUserActionToken(ctx, "DELETE", path, nil, nil, userAction)
}

// Retrieves a permission (role) by ID, including any pending change request.
func (c *DelegatedPermissionsClient) GetPermission(ctx context.Context, permissionID string) (*GetPermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID)
	var result GetPermissionResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdatePermissionInit starts delegated user action signing for the updatePermission operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdatePermissionComplete
// along with the same arguments given here.
func (c *DelegatedPermissionsClient) UpdatePermissionInit(ctx context.Context, permissionID string, body UpdatePermissionRequest) (*signer.UserActionChallenge, error) {
	path := "/permissions/" + url.PathEscape(permissionID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdatePermissionComplete finishes delegated signing for the updatePermission operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdatePermissionInit challenge.
func (c *DelegatedPermissionsClient) UpdatePermissionComplete(ctx context.Context, permissionID string, body UpdatePermissionRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdatePermissionResponse, error) {
	path := "/permissions/" + url.PathEscape(permissionID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdatePermissionResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
