// Code generated by go-sdk-generator. DO NOT EDIT.

package permissions

// List Permission Assignments
type ListPermissionAssignmentsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// Assign Permission
type AssignPermissionRequest struct {
	IdentityID string `json:"identityId"`
}

// Assign Permission
type AssignPermissionResponse struct {
	ID string `json:"id"`
	PermissionID string `json:"permissionId"`
	IdentityID string `json:"identityId"`
	IsImmutable bool `json:"isImmutable"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

// RevokePermissionQuery represents query parameters.
type RevokePermissionQuery struct {
	Force *bool `json:"force,omitempty"`
}

// Delete Permission
type DeletePermissionRequest struct {
	IsArchived bool `json:"isArchived"`
}

// Delete Permission
type DeletePermissionResponse struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Operations []string `json:"operations"`
	Status string `json:"status"`
	IsImmutable bool `json:"isImmutable"`
	IsArchived bool `json:"isArchived"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

// List Permissions
type ListPermissionsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListPermissionsQuery represents query parameters.
type ListPermissionsQuery struct {
	Limit *string `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Permission
type CreatePermissionRequest struct {
	Name string `json:"name"`
	Operations []interface{} `json:"operations"`
}

// Create Permission
type CreatePermissionResponse struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Operations []string `json:"operations"`
	Status string `json:"status"`
	IsImmutable bool `json:"isImmutable"`
	IsArchived bool `json:"isArchived"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}

// Get Permission
type GetPermissionResponse struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Operations []string `json:"operations"`
	Status string `json:"status"`
	IsImmutable bool `json:"isImmutable"`
	IsArchived bool `json:"isArchived"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
	PendingChangeRequest *map[string]interface{} `json:"pendingChangeRequest,omitempty"`
}

// Update Permission
type UpdatePermissionRequest struct {
	Name *string `json:"name,omitempty"`
	Operations []interface{} `json:"operations,omitempty"`
}

// Update Permission
type UpdatePermissionResponse struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Operations []string `json:"operations"`
	Status string `json:"status"`
	IsImmutable bool `json:"isImmutable"`
	IsArchived bool `json:"isArchived"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
}
