name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOLANG_VERSION: "1.22.1"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: true

      - name: Build
        run: go build ./...
