name: Go Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOLANG_VERSION: "1.22.2"
  TRIVY_VERSION: "v0.50.0"

jobs:
  sec-scan:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: true

      - name: Install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/.local/bin ${{ env.TRIVY_VERSION }}
      - name: Run security scan with aquasecurity trivy
        run: trivy fs --exit-code 1 --no-progress --severity CRITICAL ./

      - name: Install govuln
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run security scan with govuln
        run: |
          govulncheck ./...
