// Code generated by go-sdk-generator. DO NOT EDIT.

package vaults

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedVaultsClient provides delegated user action signing for vaults operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedVaultsClient struct {
	client *client.Client
}

// NewDelegatedVaultsClient creates a new DelegatedVaultsClient.
func NewDelegatedVaultsClient(c *client.Client) *DelegatedVaultsClient {
	return &DelegatedVaultsClient{client: c}
}

// Retrieves the list of Vaults in your organization.
func (c *DelegatedVaultsClient) ListVaults(ctx context.Context, query *ListVaultsQuery) (*ListVaultsResponse, error) {
	path := "/vaults"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListVaultsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateVaultInit starts delegated user action signing for the createVault operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateVaultComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) CreateVaultInit(ctx context.Context, body CreateVaultRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateVaultComplete finishes delegated signing for the createVault operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateVaultInit challenge.
func (c *DelegatedVaultsClient) CreateVaultComplete(ctx context.Context, body CreateVaultRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateVaultResponse, error) {
	path := "/vaults"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateVaultResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateVaultAddressInit starts delegated user action signing for the createVaultAddress operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateVaultAddressComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) CreateVaultAddressInit(ctx context.Context, vaultID string, body CreateVaultAddressRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/addresses"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateVaultAddressComplete finishes delegated signing for the createVaultAddress operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateVaultAddressInit challenge.
func (c *DelegatedVaultsClient) CreateVaultAddressComplete(ctx context.Context, vaultID string, body CreateVaultAddressRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateVaultAddressResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/addresses"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateVaultAddressResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateVaultTransferInit starts delegated user action signing for the createVaultTransfer operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateVaultTransferComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) CreateVaultTransferInit(ctx context.Context, vaultID string, body CreateVaultTransferRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/transfers"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateVaultTransferComplete finishes delegated signing for the createVaultTransfer operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateVaultTransferInit challenge.
func (c *DelegatedVaultsClient) CreateVaultTransferComplete(ctx context.Context, vaultID string, body CreateVaultTransferRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateVaultTransferResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/transfers"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateVaultTransferResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves a Vault by its ID.
func (c *DelegatedVaultsClient) GetVault(ctx context.Context, vaultID string) (*GetVaultResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID)
	var result GetVaultResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateVaultInit starts delegated user action signing for the updateVault operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UpdateVaultComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) UpdateVaultInit(ctx context.Context, vaultID string, body UpdateVaultRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID)
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// UpdateVaultComplete finishes delegated signing for the updateVault operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UpdateVaultInit challenge.
func (c *DelegatedVaultsClient) UpdateVaultComplete(ctx context.Context, vaultID string, body UpdateVaultRequest, challengeID string, assertion *signer.CredentialAssertion) (*UpdateVaultResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UpdateVaultResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists a vault's assets with balances (available/quarantined/locked) and USD valuation.
func (c *DelegatedVaultsClient) ListVaultAssets(ctx context.Context, vaultID string, query *ListVaultAssetsQuery) (*ListVaultAssetsResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/assets"
	if query != nil {
		q := url.Values{}
		if query.ShowUnverified != nil {
			q.Set("showUnverified", fmt.Sprintf("%v", *query.ShowUnverified))
		}
		if query.Network != nil {
			q.Set("network", fmt.Sprintf("%v", *query.Network))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListVaultAssetsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Lists a vault's balance entries.
func (c *DelegatedVaultsClient) ListVaultBalances(ctx context.Context, vaultID string, query *ListVaultBalancesQuery) (*ListVaultBalancesResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/balances"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if query.Kind != nil {
			q.Set("kind", fmt.Sprintf("%v", *query.Kind))
		}
		if query.Network != nil {
			q.Set("network", fmt.Sprintf("%v", *query.Network))
		}
		if query.Tid != nil {
			q.Set("tid", fmt.Sprintf("%v", *query.Tid))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListVaultBalancesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TagVaultInit starts delegated user action signing for the tagVault operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to TagVaultComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) TagVaultInit(ctx context.Context, vaultID string, body TagVaultRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/tags"
	return c.client.CreateUserActionChallenge(ctx, "PUT", path, body)
}

// TagVaultComplete finishes delegated signing for the tagVault operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the TagVaultInit challenge.
func (c *DelegatedVaultsClient) TagVaultComplete(ctx context.Context, vaultID string, body TagVaultRequest, challengeID string, assertion *signer.CredentialAssertion) (*TagVaultResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/tags"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result TagVaultResponse
	if err := c.client.DoWithUserActionToken(ctx, "PUT", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// UntagVaultInit starts delegated user action signing for the untagVault operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UntagVaultComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) UntagVaultInit(ctx context.Context, vaultID string, body UntagVaultRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/tags"
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, body)
}

// UntagVaultComplete finishes delegated signing for the untagVault operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UntagVaultInit challenge.
func (c *DelegatedVaultsClient) UntagVaultComplete(ctx context.Context, vaultID string, body UntagVaultRequest, challengeID string, assertion *signer.CredentialAssertion) (*UntagVaultResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/tags"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UntagVaultResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// UnquarantineInit starts delegated user action signing for the unquarantine operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to UnquarantineComplete
// along with the same arguments given here.
func (c *DelegatedVaultsClient) UnquarantineInit(ctx context.Context, vaultID string, quarantineID string, body UnquarantineRequest) (*signer.UserActionChallenge, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/quarantines/" + url.PathEscape(quarantineID)
	return c.client.CreateUserActionChallenge(ctx, "DELETE", path, body)
}

// UnquarantineComplete finishes delegated signing for the unquarantine operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the UnquarantineInit challenge.
func (c *DelegatedVaultsClient) UnquarantineComplete(ctx context.Context, vaultID string, quarantineID string, body UnquarantineRequest, challengeID string, assertion *signer.CredentialAssertion) (*UnquarantineResponse, error) {
	path := "/vaults/" + url.PathEscape(vaultID) + "/quarantines/" + url.PathEscape(quarantineID)
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result UnquarantineResponse
	if err := c.client.DoWithUserActionToken(ctx, "DELETE", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}
