// Code generated by go-sdk-generator. DO NOT EDIT.

package vaults

import (
	"github.com/dfns/dfns-sdk-go/v2/types"
)

// List Vaults
type ListVaultsResponse struct {
	Items []types.Vault `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListVaultsQuery represents query parameters.
type ListVaultsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Vault
type CreateVaultRequest struct {
	Name *string `json:"name,omitempty"`
	Tags []string `json:"tags,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Create Vault
type CreateVaultResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Name *string `json:"name,omitempty"`
	Tags []string `json:"tags"`
	ExternalID *string `json:"externalId,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
	Addresses []types.VaultAddress `json:"addresses,omitempty"`
}

// Create Vault Address
type CreateVaultAddressRequest struct {
	Network string `json:"network"`
}

// Create Vault Address
type CreateVaultAddressResponse struct {
	WalletID string `json:"walletId"`
	Network string `json:"network"`
	Address string `json:"address"`
}

// Create Vault Transfer
type CreateVaultTransferRequest struct {
	Network string `json:"network"`
	Tid string `json:"tid"`
	To string `json:"to"`
	Amount string `json:"amount"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Create Vault Transfer
type CreateVaultTransferResponse struct {
	ID string `json:"id"`
	WalletID string `json:"walletId"`
	Network types.Network `json:"network"`
	Requester types.Requester `json:"requester"`
	RequestBody interface{} `json:"requestBody"`
	Metadata map[string]interface{} `json:"metadata"`
	Status string `json:"status"`
	Reason *string `json:"reason,omitempty"`
	TxHash *string `json:"txHash,omitempty"`
	Fee *string `json:"fee,omitempty"`
	DateRequested string `json:"dateRequested"`
	DatePolicyResolved *string `json:"datePolicyResolved,omitempty"`
	DateBroadcasted *string `json:"dateBroadcasted,omitempty"`
	DateConfirmed *string `json:"dateConfirmed,omitempty"`
	ApprovalID *string `json:"approvalId,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	FeeSponsorID *string `json:"feeSponsorId,omitempty"`
	ReplacementID *string `json:"replacementId,omitempty"`
	Details map[string]map[string]interface{} `json:"details,omitempty"`
}

// Get Vault
type GetVaultResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Name *string `json:"name,omitempty"`
	Tags []string `json:"tags"`
	ExternalID *string `json:"externalId,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
	Addresses []types.VaultAddress `json:"addresses,omitempty"`
}

// Update Vault
type UpdateVaultRequest struct {
	Name *string `json:"name,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
}

// Update Vault
type UpdateVaultResponse struct {
	ID string `json:"id"`
	OrgID string `json:"orgId"`
	Name *string `json:"name,omitempty"`
	Tags []string `json:"tags"`
	ExternalID *string `json:"externalId,omitempty"`
	DateCreated string `json:"dateCreated"`
	DateUpdated string `json:"dateUpdated"`
	Addresses []types.VaultAddress `json:"addresses,omitempty"`
}

// List Vault Assets
type ListVaultAssetsResponse struct {
	Items []types.VaultAsset `json:"items"`
	NetWorth types.VaultNetWorth `json:"netWorth"`
}

// ListVaultAssetsQuery represents query parameters.
type ListVaultAssetsQuery struct {
	ShowUnverified *interface{} `json:"showUnverified,omitempty"`
	Network *string `json:"network,omitempty"`
}

// List Vault Balances
type ListVaultBalancesResponse struct {
	Items []types.VaultBalanceEntry `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListVaultBalancesQuery represents query parameters.
type ListVaultBalancesQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Network *string `json:"network,omitempty"`
	Tid *string `json:"tid,omitempty"`
}

// Tag Vault
type TagVaultRequest struct {
	Tags []string `json:"tags"`
}

// Tag Vault
type TagVaultResponse struct {
}

// Untag Vault
type UntagVaultRequest struct {
	Tags []string `json:"tags"`
}

// Untag Vault
type UntagVaultResponse struct {
}

// Unquarantine
type UnquarantineRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// Unquarantine
type UnquarantineResponse struct {
	Status string `json:"status"`
}
