// Code generated by go-sdk-generator. DO NOT EDIT.

package staking

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/internal/client"
)

// StakingClient provides methods for staking operations.
type StakingClient struct {
	client *client.Client
}

// NewStakingClient creates a new StakingClient.
func NewStakingClient(c *client.Client) *StakingClient {
	return &StakingClient{client: c}
}

// Retrieve the list of stakes.
func (c *StakingClient) ListStakes(ctx context.Context, query *ListStakesQuery) (*ListStakesResponse, error) {
	path := "/staking/stakes"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListStakesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new stake.
func (c *StakingClient) CreateStake(ctx context.Context, body CreateStakeRequest) (*CreateStakeResponse, error) {
	path := "/staking/stakes"
	var result CreateStakeResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of actions for a specific stake.
func (c *StakingClient) ListStakeActions(ctx context.Context, stakeID string, query *ListStakeActionsQuery) (*ListStakeActionsResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/actions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListStakeActionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Create a new action for an existing stake.
func (c *StakingClient) CreateStakeAction(ctx context.Context, stakeID string, body CreateStakeActionRequest) (*CreateStakeActionResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/actions"
	var result CreateStakeActionResponse
	err := c.client.Do(ctx, "POST", path, body, &result, true)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the details of a specific stake.
func (c *StakingClient) GetStakes(ctx context.Context, stakeID string, query *GetStakesQuery) (*GetStakesResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID)
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetStakesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the rewards linked to a specific stake.
func (c *StakingClient) GetStakeRewards(ctx context.Context, stakeID string) (*GetStakeRewardsResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/rewards"
	var result GetStakeRewardsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
