// Code generated by go-sdk-generator. DO NOT EDIT.

package staking

import (
	"context"
	"fmt"
	"net/url"

	"github.com/dfns/dfns-sdk-go/v2/internal/client"
	"github.com/dfns/dfns-sdk-go/v2/signer"
)

// DelegatedStakingClient provides delegated user action signing for staking operations.
// Signed operations are split into <Method>Init (returns a challenge to sign out-of-band)
// and <Method>Complete (submits the signed challenge and issues the request). Unsigned
// reads behave exactly like the regular client.
type DelegatedStakingClient struct {
	client *client.Client
}

// NewDelegatedStakingClient creates a new DelegatedStakingClient.
func NewDelegatedStakingClient(c *client.Client) *DelegatedStakingClient {
	return &DelegatedStakingClient{client: c}
}

// Retrieve the list of stakes.
func (c *DelegatedStakingClient) ListStakes(ctx context.Context, query *ListStakesQuery) (*ListStakesResponse, error) {
	path := "/staking/stakes"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListStakesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateStakeInit starts delegated user action signing for the createStake operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateStakeComplete
// along with the same arguments given here.
func (c *DelegatedStakingClient) CreateStakeInit(ctx context.Context, body CreateStakeRequest) (*signer.UserActionChallenge, error) {
	path := "/staking/stakes"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateStakeComplete finishes delegated signing for the createStake operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateStakeInit challenge.
func (c *DelegatedStakingClient) CreateStakeComplete(ctx context.Context, body CreateStakeRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateStakeResponse, error) {
	path := "/staking/stakes"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateStakeResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the list of actions for a specific stake.
func (c *DelegatedStakingClient) ListStakeActions(ctx context.Context, stakeID string, query *ListStakeActionsQuery) (*ListStakeActionsResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/actions"
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result ListStakeActionsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateStakeActionInit starts delegated user action signing for the createStakeAction operation.
// It returns the challenge to sign out-of-band; pass the signed assertion to CreateStakeActionComplete
// along with the same arguments given here.
func (c *DelegatedStakingClient) CreateStakeActionInit(ctx context.Context, stakeID string, body CreateStakeActionRequest) (*signer.UserActionChallenge, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/actions"
	return c.client.CreateUserActionChallenge(ctx, "POST", path, body)
}

// CreateStakeActionComplete finishes delegated signing for the createStakeAction operation:
// it submits the externally-signed challenge and issues the request. challengeID is the
// ChallengeIdentifier from the CreateStakeActionInit challenge.
func (c *DelegatedStakingClient) CreateStakeActionComplete(ctx context.Context, stakeID string, body CreateStakeActionRequest, challengeID string, assertion *signer.CredentialAssertion) (*CreateStakeActionResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/actions"
	userAction, err := c.client.CompleteUserActionSigning(ctx, challengeID, assertion)
	if err != nil {
		return nil, err
	}
	var result CreateStakeActionResponse
	if err := c.client.DoWithUserActionToken(ctx, "POST", path, body, &result, userAction); err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieve the details of a specific stake.
func (c *DelegatedStakingClient) GetStakes(ctx context.Context, stakeID string, query *GetStakesQuery) (*GetStakesResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID)
	if query != nil {
		q := url.Values{}
		if query.Limit != nil {
			q.Set("limit", fmt.Sprintf("%v", *query.Limit))
		}
		if query.PaginationToken != nil {
			q.Set("paginationToken", fmt.Sprintf("%v", *query.PaginationToken))
		}
		if len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var result GetStakesResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Retrieves the rewards linked to a specific stake.
func (c *DelegatedStakingClient) GetStakeRewards(ctx context.Context, stakeID string) (*GetStakeRewardsResponse, error) {
	path := "/staking/stakes/" + url.PathEscape(stakeID) + "/rewards"
	var result GetStakeRewardsResponse
	err := c.client.Do(ctx, "GET", path, nil, &result, false)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
