// Code generated by go-sdk-generator. DO NOT EDIT.

package staking

// List Stakes
type ListStakesResponse struct {
	Items []interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListStakesQuery represents query parameters.
type ListStakesQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Stake
type CreateStakeRequest struct {
	ExternalID *string `json:"externalId,omitempty"`
}

// Create Stake
type CreateStakeResponse struct {
	Actions []map[string]interface{} `json:"actions"`
}

// List Stake Actions
type ListStakeActionsResponse struct {
	Items []map[string]interface{} `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// ListStakeActionsQuery represents query parameters.
type ListStakeActionsQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Create Stake Action
type CreateStakeActionRequest struct {
	ExternalID *string `json:"externalId,omitempty"`
}

// Create Stake Action
type CreateStakeActionResponse struct {
	Actions []map[string]interface{} `json:"actions"`
}

// Get Stakes
type GetStakesResponse struct {
	Actions []map[string]interface{} `json:"actions"`
}

// GetStakesQuery represents query parameters.
type GetStakesQuery struct {
	Limit *int64 `json:"limit,omitempty"`
	PaginationToken *string `json:"paginationToken,omitempty"`
}

// Get Stake Rewards
type GetStakeRewardsResponse struct {
	Symbol string `json:"symbol"`
	Balance string `json:"balance"`
}
